

CREATE VIEW [ax_cus].[v_BOM_CONSUMPTION_HISTORY]
AS
SELECT 
    CAST(NULL AS NVARCHAR(255))                 AS [TRANSACTION_ID],
    CAST(it.ITEMID AS NVARCHAR(255))                AS [ITEM_NO],
    CAST(idim.INVENTLOCATIONID AS NVARCHAR(255))    AS [LOCATION_NO],
    CAST(it.DATEPHYSICAL AS DATE)                   AS [DATE],
    CAST(-SUM(it.QTY) AS DECIMAL(18,4))                  AS [UNIT_QTY]
FROM ax_cus.INVENTTRANS it
INNER JOIN ax_cus.INVENTDIM idim ON it.INVENTDIMID = idim.INVENTDIMID AND it.DATAAREAID = idim.DATAAREAID AND (it.PARTITION = idim.PARTITION OR (it.PARTITION IS NULL AND idim.PARTITION IS NULL))
INNER JOIN ax_cus.INVENTTRANSORIGIN ito ON it.INVENTTRANSORIGIN = ito.RECID AND it.DATAAREAID = ito.DATAAREAID AND (it.PARTITION = ito.PARTITION OR (it.PARTITION IS NULL AND ito.PARTITION IS NULL))
INNER JOIN core.location_mapping_setup lms ON lms.locationNo=idim.INVENTLOCATIONID
GROUP BY
	it.ITEMID, idim.INVENTLOCATIONID, it.DATEPHYSICAL
HAVING  
    CAST(-SUM(it.QTY) AS DECIMAL(18,4))>0


