CREATE VIEW [ax_cus].[v_bom_component] AS
	
	WITH cte AS (
		SELECT
			CAST(bv.ITEMID AS NVARCHAR(255))    AS [ITEM_NO],
			CAST(b.ITEMID AS NVARCHAR(255))     AS [COMPONENT_ITEM_NO],
			CAST(b.BOMQTY AS DECIMAL(18,4))     AS [QUANTITY],
			CAST(b.DATAAREAID AS NVARCHAR(4))   AS [COMPANY],
			ROW_NUMBER() OVER (
				PARTITION BY bv.ITEMID, b.ITEMID, b.DATAAREAID
				ORDER BY bv.MODIFIEDDATETIME DESC
			) AS rn
		FROM ax.BOM b
		INNER JOIN ax.BOMVERSION bv 
			ON bv.BOMID       = b.BOMID
		   AND bv.DATAAREAID  = b.DATAAREAID
		   AND (b.PARTITION = bv.PARTITION 
			   OR (b.PARTITION IS NULL AND bv.PARTITION IS NULL))
		WHERE 
			bv.ACTIVE   = 1
			AND bv.APPROVED = 1
			AND bv.ITEMID <> b.ITEMID
			AND bv.TODATE = '1900-01-01 00:00:00.000' OR bv.TODATE > GETDATE()
			AND bv.FROMDATE >GETDATE()
	)
	SELECT
		ITEM_NO,
		COMPONENT_ITEM_NO,
		QUANTITY,
		COMPANY
	FROM cte
	WHERE cte.rn = 1


