create VIEW [ax_cus].[v_CUSTOMER] 
AS
	SELECT DISTINCT
        CAST(c.ACCOUNTNUM AS NVARCHAR(255)) AS [no],
        CAST(c.NAME AS NVARCHAR(255)) 		AS [name],
		CAST(c.DATAAREAID AS NVARCHAR(4))  AS [COMPANY],
		CAST(NULL AS NVARCHAR(255))        AS [CUSTOMER_GROUP_NO]
	FROM
		[ax].CUSTOMERVIEW c
	WHERE 1=0
