
CREATE VIEW [ax_cus].[v_LOCATION] AS

	
		SELECT 
			CAST(il.INVENTLOCATIONID AS NVARCHAR(255)) AS [NO],
			CAST(il.NAME AS NVARCHAR(255)) 			   AS [NAME],
			CAST(il.DATAAREAID AS NVARCHAR(4))         AS [COMPANY]
		FROM ax_cus.INVENTLOCATION il
		WHERE il.name <> 'Tollur'

