CREATE VIEW [ax_cus].[v_OPEN_SALES_ORDER] 
AS
   SELECT
         CAST(sal.SALESID AS NVARCHAR(255))								AS [SALES_ORDER_NO],
         CAST(sal.ITEMID AS NVARCHAR(255)) 								AS [ITEM_NO],
         CAST(ivd.INVENTLOCATIONID AS NVARCHAR(255))                    AS [LOCATION_NO],
         SUM(CAST(sal.QTYORDERED AS DECIMAL(18,4)))                     AS [QUANTITY],
         CAST(a.CUSTACCOUNT AS NVARCHAR(255))                           AS [CUSTOMER_NO],
         CAST(a.DELIVERYDATE AS DATE)									AS [DELIVERY_DATE],
		 CAST('mfk' AS NVARCHAR(4))               						AS [COMPANY]
   FROM [ax_cus].[SALESLINE] sal
inner join ax_cus.SALESTABLE a on a.SALESID = sal.SALESID and a.PARTITION =sal.PARTITION
INNER JOIN [ax_cus].INVENTDIM ivd on ivd.INVENTDIMID = sal.INVENTDIMID
WHERE sal.DATAAREAID = 'mfk'
AND ivd.DATAAREAID = 'mfk'
AND ivd.PARTITION = 5637144576
AND sal.PARTITION = 5637144576
AND sal.SALESTYPE = 3 
AND sal.SALESSTATUS = 1
and sal.QTYORDERED >0
GROUP BY  sal.SALESID, sal.ITEMID, ivd.INVENTLOCATIONID, a.DELIVERYDATE, a.CUSTACCOUNT
