CREATE VIEW [ax_cus].[v_STOCK_LEVEL] 
AS

       SELECT
            CAST(t1.ITEMID AS NVARCHAR(255)) 					AS [ITEM_NO],
            CAST(case when t2.inventlocationid = 'TOLL' then 'Myl 'else t2.INVENTLOCATIONID END  AS NVARCHAR(255)) 			AS [LOCATION_NO],
			CAST(ISNULL(CASE WHEN IB.EXPDATE = '1900-01-01' 
					THEN '2100-01-01' 
					ELSE DATEADD(dd,-IT.PDSBESTBEFORE, IB.EXPDATE) 
					END, '2100-01-01')
			AS DATE)     		AS [EXPIRE_DATE],
            CAST(SUM(CAST(t1.PHYSICALINVENT AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [STOCK_UNITS]
       FROM ax.INVENTSUM t1 -- ITAMID
	INNER JOIN	ax_cus.InventDim t2  
		ON	t2.INVENTDIMID = t1.INVENTDIMID
		AND t2.DATAAREAID = t1.DATAAREAID 
		AND t2.PARTITION = t1.PARTITION
		AND t2.INVENTLOCATIONID <> ''
	INNER JOIN ax_cus.INVENTTABLE AS IT
		ON t1.ITEMID = IT.ITEMID
	LEFT OUTER JOIN ax_cus.INVENTBATCH AS IB 
		ON 	IB.INVENTBATCHID = t2.INVENTBATCHID 
		AND IB.ITEMID = t1.ITEMID 
	WHERE t1.CLOSED = 0
		AND	CAST(t1.PHYSICALINVENT AS DECIMAL(18,4)) <> 0
		AND t2.INVENTLOCATIONID <> ''
		AND ISNULL(CASE WHEN IB.EXPDATE = '1900-01-01' 
					THEN '2100-01-01' 
					ELSE DATEADD(dd,-IT.PDSBESTBEFORE, IB.EXPDATE) 
					END, '2100-01-01') > GETDATE()
		AND t2.inventstatusid NOT IN ('Merktvv', 'Ómerktvv', 'Gallað', 'Útrunnið', 'Aðföng','Krónan','Samkaup')
		and t2.WMSLOCATIONID not in ('FÖ1','S')  
	GROUP BY 
		t1.ITEMID,
		CAST(case when t2.inventlocationid = 'TOLL' then 'Myl 'else t2.INVENTLOCATIONID END  AS NVARCHAR(255)) ,
		ISNULL(CASE WHEN IB.EXPDATE = '1900-01-01' 
				THEN '2100-01-01' 
				ELSE DATEADD(dd,-IT.PDSBESTBEFORE, IB.EXPDATE) 
				END, '2100-01-01')	

