CREATE VIEW [ax_cus].[v_STOCK_HISTORY] 
AS
       SELECT
            CAST(NULL AS BIGINT) AS [TRANSACTION_ID],
            CAST(it.ITEMID AS NVARCHAR(255))            AS [ITEM_NO],
            CAST(CASE WHEN id.inventlocationid = 'TOll' THEN 'Myl 'ELSE id.INVENTLOCATIONID END AS NVARCHAR(255))  AS [LOCATION_NO],
            CAST(it.DATEPHYSICAL AS DATE)               AS [DATE],
            CAST(SUM(CAST(it.QTY AS DECIMAL(18,4))) AS DECIMAL(18,4))        AS [STOCK_MOVE],
            CAST(NULL AS DECIMAL(18, 4))                AS [STOCK_LEVEL]
      FROM ax_cus.INVENTTRANS it
	INNER JOIN ax_cus.INVENTTRANSORIGIN ito 
		ON it.INVENTTRANSORIGIN = ito.RECID
		AND it.DATAAREAID = ito.DATAAREAID
		AND it.[PARTITION] = ito.[PARTITION]
		AND CAST(it.DATEPHYSICAL AS DATE) <> '1900-01-01 00:00:00.000'
	INNER JOIN ax_cus.INVENTDIM id
		ON id.INVENTDIMID = it.INVENTDIMID
		AND id.DATAAREAID = it.DATAAREAID
		AND id.[PARTITION] = it.[PARTITION]
	GROUP BY
		it.DATEPHYSICAL,
		it.ITEMID,
		CASE WHEN id.inventlocationid = 'TOll' THEN 'Myl 'ELSE id.INVENTLOCATIONID END
