CREATE TABLE [cus].[CheckItemLine] (
    [TxnID] NVARCHAR(36) NULL,
    [TimeCreated] DATETIME2 NULL,
    [TimeModified] DATETIME2 NULL,
    [EditSequence] NVARCHAR(16) NULL,
    [TxnNumber] INT NULL,
    [TxnDate] DATETIME2 NULL,
    [RefNumber] NVARCHAR(11) NULL,
    [ItemLineType] NVARCHAR(11) NULL,
    [ItemLineSeqNo] INT NULL,
    [ItemLineTxnLineID] NVARCHAR(36) NULL,
    [ItemLineItemRefListID] NVARCHAR(36) NULL,
    [ItemLineItemRefFullName] NVARCHAR(159) NULL,
    [ItemLineDesc] NVARCHAR(MAX) NULL,
    [ItemLineQuantity] DECIMAL(16,5) NULL,
    [ItemLineUnitOfMeasure] NVARCHAR(31) NULL,
    [ItemLineOverrideUOMSetRefListID] NVARCHAR(36) NULL,
    [ItemLineOverrideUOMSetRefFullName] NVARCHAR(31) NULL,
    [ItemLineInventorySiteRefListID] NVARCHAR(36) NULL,
    [ItemLineInventorySiteLocationRefListID] NVARCHAR(36) NULL,
    [ItemLineInventorySiteLocationRefFullName] NVARCHAR(31) NULL,
    [FQPrimaryKey] NVARCHAR(110) NULL,
    [FQTxnLinkKey] NVARCHAR(110) NULL
);
