CREATE TABLE [cus].[InvoiceLine] (
    [TxnID] NVARCHAR(36) NULL,
    [TimeCreated] DATETIME2 NULL,
    [TimeModified] DATETIME2 NULL,
    [EditSequence] NVARCHAR(16) NULL,
    [TxnNumber] INT NULL,
    [CustomerRefListID] NVARCHAR(36) NULL,
    [CustomerRefFullName] NVARCHAR(209) NULL,
    [TxnDate] DATETIME2 NULL,
    [RefNumber] NVARCHAR(11) NULL,
    [InvoiceLineType] NVARCHAR(11) NULL,
    [InvoiceLineSeqNo] INT NULL,
    [InvoiceLineTxnLineID] NVARCHAR(36) NULL,
    [InvoiceLineItemRefListID] NVARCHAR(36) NULL,
    [InvoiceLineItemRefFullName] NVARCHAR(159) NULL,
    [InvoiceLineDesc] NVARCHAR(MAX) NULL,
    [InvoiceLineQuantity] DECIMAL(16,5) NULL,
    [InvoiceLineUnitOfMeasure] NVARCHAR(31) NULL,
    [InvoiceLineOverrideUOMSetRefListID] NVARCHAR(36) NULL,
    [InvoiceLineOverrideUOMSetRefFullName] NVARCHAR(31) NULL,
    [InvoiceLineInventorySiteRefListID] NVARCHAR(36) NULL,
    [InvoiceLineInventorySiteLocationRefListID] NVARCHAR(36) NULL,
    [InvoiceLineInventorySiteLocationRefFullName] NVARCHAR(31) NULL,
    [FQPrimaryKey] NVARCHAR(110) NULL,
    [FQTxnLinkKey] NVARCHAR(110) NULL
);
