CREATE TABLE [cus].[ItemInventory] (
    [ListID] NVARCHAR(255) NOT NULL,
    [Name] NVARCHAR(255) NOT NULL,
    [FullName] NVARCHAR(255) NULL,
    [EditSequence] NVARCHAR(255) NULL,
    [BarCodeValue] NVARCHAR(255) NULL,
    [BarCodeAssignEvenIfUsed] BIT NULL,
    [BarCodeAllowOverride] BIT NULL,
    [IsActive] BIT NULL,
    [ClassRefListID] NVARCHAR(255) NULL,
    [ClassRefFullName] NVARCHAR(255) NULL,
    [ParentRefListID] NVARCHAR(255) NULL,
    [ParentRefFullName] NVARCHAR(255) NULL,
    [Sublevel] INT NULL,
    [ManufacturerPartNumber] NVARCHAR(255) NULL,
    [UnitOfMeasureSetRefListID] NVARCHAR(255) NULL,
    [UnitOfMeasureSetRefFullName] NVARCHAR(255) NULL,
    [ForceUOMChange] BIT NULL,
    [SalesTaxCodeRefListID] NVARCHAR(255) NULL,
    [SalesTaxCodeRefFullName] NVARCHAR(255) NULL,
    [SalesDesc] NVARCHAR(MAX) NULL,
    [SalesPrice] DECIMAL(16,5) NULL,
    [IncomeAccountRefListID] NVARCHAR(255) NULL,
    [IncomeAccountRefFullName] NVARCHAR(255) NULL,
    [ApplyIncomeAccountRefToExistingTxns] BIT NULL,
    [PurchaseDesc] NVARCHAR(MAX) NULL,
    [PurchaseCost] DECIMAL(16,5) NULL,
    [COGSAccountRefListID] NVARCHAR(255) NULL,
    [COGSAccountRefFullName] NVARCHAR(255) NULL,
    [PrefVendorRefListID] NVARCHAR(255) NULL,
    [PrefVendorRefFullName] NVARCHAR(255) NULL,
    [AssetAccountRefListID] NVARCHAR(255) NULL,
    [AssetAccountRefFullName] NVARCHAR(255) NULL,
    [ReorderPoint] DECIMAL(16,5) NULL,
    [Maximum] DECIMAL(16,5) NULL,
    [QuantityOnHand] DECIMAL(16,5) NULL,
    [TotalValue] DECIMAL(16,2) NULL,
    [InventoryDate] DATETIME2 NULL,
    [AverageCost] DECIMAL(16,5) NULL,
    [QuantityOnOrder] DECIMAL(16,5) NULL,
    [QuantityOnSalesOrder] DECIMAL(16,5) NULL,
    [ExternalGUID] NVARCHAR(255) NULL,
    [TimeCreated] DATETIME2 NULL,
    [TimeModified] DATETIME2 NULL,
    CONSTRAINT [PK_cus_ItemInventory] PRIMARY KEY (ListID)
);
