CREATE TABLE [cus].[Vendor] (
    [ListID] NVARCHAR(36) NOT NULL,
    [TimeCreated] DATETIME2 NULL,
    [TimeModified] DATETIME2 NULL,
    [EditSequence] NVARCHAR(16) NULL,
    [Name] NVARCHAR(41) NULL,
    [IsActive] BIT NULL,
    [ClassRefListID] NVARCHAR(36) NULL,
    [ClassRefFullName] NVARCHAR(209) NULL,
    [CompanyName] NVARCHAR(41) NULL,
    [Salutation] NVARCHAR(15) NULL,
    [NameOnCheck] NVARCHAR(41) NULL,
    [AccountNumber] NVARCHAR(99) NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [VendorTypeRefListID] NVARCHAR(36) NULL,
    [VendorTypeRefFullName] NVARCHAR(159) NULL,
    [TermsRefListID] NVARCHAR(36) NULL,
    [TermsRefFullName] NVARCHAR(31) NULL,
    [CreditLimit] DECIMAL(15,2) NULL,
    [OpenBalance] DECIMAL(16,2) NULL,
    [OpenBalanceDate] DATETIME2 NULL,
    [Balance] DECIMAL(16,2) NULL,
    [ExternalGUID] NVARCHAR(40) NULL,
    [BusinessNumber] NVARCHAR(99) NULL,
    CONSTRAINT [PK_Vendor] PRIMARY KEY (ListID)
);
