CREATE TABLE [nav_cus].[Afhendingastaða] (
    [timestamp] TIMESTAMP NOT NULL,
    [Verknúmer] VARCHAR(20) NULL,
    [Vörunúmer] VARCHAR(20) NULL,
    [Línunúmer] INT NULL,
    [Lýsing] VARCHAR(50) NULL,
    [Magn] DECIMAL(38,20) NULL,
    [Magn til afhendingar] DECIMAL(38,20) NULL,
    [Magn til skila] DECIMAL(38,20) NULL,
    [Service Item] VARCHAR(20) NULL,
    [Lýsing2] VARCHAR(30) NULL,
    [Þjónustupöntun] VARCHAR(20) NULL,
    [Einingarverð] DECIMAL(38,20) NULL,
    [Afsláttar%] DECIMAL(38,20) NULL,
    [Upphæð] DECIMAL(38,20) NULL,
    [Lánað] TINYINT NULL,
    [Sölutilboð] VARCHAR(20) NULL,
    [Frá lager] VARCHAR(10) NULL,
    [Til lagers] VARCHAR(10) NULL,
    [Tegund] INT NULL,
    [Magn til móttöku] DECIMAL(38,20) NULL,
    [Kostnaðarverð] DECIMAL(38,20) NULL,
    [Frá staðsetning] VARCHAR(10) NULL,
    [Til staðsetning] VARCHAR(10) NULL,
    [Verkliður] VARCHAR(10) NULL,
    [Raðnúmer] VARCHAR(20) NULL,
    [Beiðni númer] VARCHAR(20) NULL,
    [Afhendingarnúmer] INT NULL,
    [UppfæraVörunúmer] TINYINT NULL,
    [Tilboðsmagn] DECIMAL(38,20) NULL,
    [Lokið] TINYINT NULL,
    [StaðsetningVöru] VARCHAR(20) NULL,
    [Tínsla] TINYINT NULL,
    [IceLinkBokun] TINYINT NULL,
    [Vantar magn í staðsetningu] TINYINT NULL,
    [Vöntun] TINYINT NULL,
    [Shortcut Dimension 1 Code] VARCHAR(20) NULL,
    [Shortcut Dimension 2 Code] VARCHAR(20) NULL,
    [OrderLineId] VARCHAR(30) NULL
);
