CREATE TABLE [nav_cus].[ServiceHeader] (
    [timestamp] TIMESTAMP NOT NULL,
    [Document Type] INT NULL,
    [No_] VARCHAR(20) NULL,
    [Customer No_] VARCHAR(20) NULL,
    [Bill-to Customer No_] VARCHAR(20) NULL,
    [Bill-to Name] VARCHAR(50) NULL,
    [Bill-to Name 2] VARCHAR(50) NULL,
    [Bill-to Address] VARCHAR(50) NULL,
    [Bill-to Address 2] VARCHAR(50) NULL,
    [Bill-to City] VARCHAR(30) NULL,
    [Bill-to Contact] VARCHAR(50) NULL,
    [Your Reference] VARCHAR(30) NULL,
    [Ship-to Code] VARCHAR(10) NULL,
    [Ship-to Name] VARCHAR(50) NULL,
    [Ship-to Name 2] VARCHAR(50) NULL,
    [Ship-to Address] VARCHAR(50) NULL,
    [Ship-to Address 2] VARCHAR(50) NULL,
    [Ship-to City] VARCHAR(30) NULL,
    [Ship-to Contact] VARCHAR(50) NULL,
    [Order Date] DATETIME NULL,
    [Posting Date] DATETIME NULL,
    [Posting Description] VARCHAR(50) NULL,
    [Payment Terms Code] VARCHAR(10) NULL,
    [Due Date] DATETIME NULL,
    [Payment Discount %] DECIMAL(38,20) NULL,
    [Pmt_ Discount Date] DATETIME NULL,
    [Location Code] VARCHAR(10) NULL,
    [Shortcut Dimension 1 Code] VARCHAR(20) NULL,
    [Shortcut Dimension 2 Code] VARCHAR(20) NULL,
    [Customer Posting Group] VARCHAR(10) NULL,
    [Currency Code] VARCHAR(10) NULL,
    [Currency Factor] DECIMAL(38,20) NULL,
    [Customer Price Group] VARCHAR(10) NULL,
    [Prices Including VAT] TINYINT NULL,
    [Invoice Disc_ Code] VARCHAR(20) NULL,
    [Customer Disc_ Group] VARCHAR(10) NULL,
    [Language Code] VARCHAR(10) NULL,
    [Salesperson Code] VARCHAR(10) NULL,
    [No_ Printed] INT NULL,
    [Applies-to Doc_ Type] INT NULL,
    [Applies-to Doc_ No_] VARCHAR(20) NULL,
    [Bal_ Account No_] VARCHAR(20) NULL,
    [Shipping No_] VARCHAR(20) NULL,
    [Posting No_] VARCHAR(20) NULL,
    [Last Shipping No_] VARCHAR(20) NULL,
    [Last Posting No_] VARCHAR(20) NULL,
    [VAT Registration No_] VARCHAR(20) NULL,
    [Reason Code] VARCHAR(10) NULL,
    [Gen_ Bus_ Posting Group] VARCHAR(10) NULL,
    [EU 3-Party Trade] TINYINT NULL,
    [Transaction Type] VARCHAR(10) NULL,
    [Transport Method] VARCHAR(10) NULL,
    [VAT Country_Region Code] VARCHAR(10) NULL,
    [Name] VARCHAR(50) NULL,
    [Name 2] VARCHAR(50) NULL,
    [Address] VARCHAR(50) NULL,
    [Address 2] VARCHAR(50) NULL,
    [City] VARCHAR(30) NULL,
    [Contact Name] VARCHAR(50) NULL,
    [Bill-to Post Code] VARCHAR(20) NULL,
    [Bill-to County] VARCHAR(30) NULL,
    [Bill-to Country_Region Code] VARCHAR(10) NULL,
    [Post Code] VARCHAR(20) NULL,
    [County] VARCHAR(30) NULL,
    [Country_Region Code] VARCHAR(10) NULL,
    [Ship-to Post Code] VARCHAR(20) NULL,
    [Ship-to County] VARCHAR(30) NULL,
    [Ship-to Country_Region Code] VARCHAR(10) NULL,
    [Bal_ Account Type] INT NULL,
    [Exit Point] VARCHAR(10) NULL,
    [Correction] TINYINT NULL,
    [Document Date] DATETIME NULL,
    [Area] VARCHAR(10) NULL,
    [Transaction Specification] VARCHAR(10) NULL,
    [Payment Method Code] VARCHAR(10) NULL,
    [No_ Series] VARCHAR(10) NULL,
    [Posting No_ Series] VARCHAR(10) NULL,
    [Shipping No_ Series] VARCHAR(10) NULL,
    [Tax Area Code] VARCHAR(20) NULL,
    [Tax Liable] TINYINT NULL,
    [VAT Bus_ Posting Group] VARCHAR(10) NULL,
    [Reserve] INT NULL,
    [Applies-to ID] VARCHAR(20) NULL,
    [VAT Base Discount %] DECIMAL(38,20) NULL,
    [Status] INT NULL,
    [Invoice Discount Calculation] INT NULL,
    [Invoice Discount Value] DECIMAL(38,20) NULL,
    [Contact No_] VARCHAR(20) NULL,
    [Bill-to Contact No_] VARCHAR(20) NULL,
    [Responsibility Center] VARCHAR(10) NULL,
    [Shipping Advice] INT NULL,
    [Description] VARCHAR(50) NULL,
    [Service Order Type] VARCHAR(10) NULL,
    [Link Service to Service Item] TINYINT NULL,
    [Priority] INT NULL,
    [Phone No_] VARCHAR(30) NULL,
    [E-Mail] VARCHAR(80) NULL,
    [Phone No_ 2] VARCHAR(30) NULL,
    [Fax No_] VARCHAR(30) NULL,
    [Order Time] DATETIME NULL,
    [Default Response Time (Hours)] DECIMAL(38,20) NULL,
    [Actual Response Time (Hours)] DECIMAL(38,20) NULL,
    [Service Time (Hours)] DECIMAL(38,20) NULL,
    [Response Date] DATETIME NULL,
    [Response Time] DATETIME NULL,
    [Starting Date] DATETIME NULL,
    [Starting Time] DATETIME NULL,
    [Finishing Date] DATETIME NULL,
    [Finishing Time] DATETIME NULL,
    [Notify Customer] INT NULL,
    [Max_ Labor Unit Price] DECIMAL(38,20) NULL,
    [Warning Status] INT NULL,
    [Contract No_] VARCHAR(20) NULL,
    [Ship-to Fax No_] VARCHAR(30) NULL,
    [Ship-to E-Mail] VARCHAR(80) NULL,
    [Ship-to Phone] VARCHAR(30) NULL,
    [Ship-to Phone 2] VARCHAR(30) NULL,
    [Service Zone Code] VARCHAR(10) NULL,
    [Expected Finishing Date] DATETIME NULL,
    [Allow Line Disc_] TINYINT NULL,
    [Assigned User ID] VARCHAR(20) NULL,
    [Framhaldsþjónustupöntun úr] VARCHAR(20) NULL,
    [Kenni notanda] VARCHAR(30) NULL,
    [Þjónustuvara] VARCHAR(30) NULL,
    [Þjon_vöru línunr] INT NULL,
    [Sölupöntun] VARCHAR(20) NULL,
    [Umbeðið] VARCHAR(11) NULL,
    [Umbeðið af nafn] VARCHAR(31) NULL,
    [Pro-Forma] TINYINT NULL,
    [Bakfærð Þjónustupöntun] VARCHAR(20) NULL,
    [Vinna skv_ tilboði] DECIMAL(38,20) NULL,
    [Vinna kostnaður] DECIMAL(38,20) NULL,
    [Vinna framlegð] DECIMAL(38,20) NULL,
    [Búnaður skv_ tilboði] DECIMAL(38,20) NULL,
    [Búnaður kostnaður] DECIMAL(38,20) NULL,
    [Búnaður framlegð] DECIMAL(38,20) NULL,
    [Sleppa áríðandi upplýsingar] TINYINT NULL,
    [Úthlutað á forða] VARCHAR(20) NULL,
    [Birgðargeymsla] VARCHAR(20) NULL,
    [GreiðlsuhátturLagerBókun] VARCHAR(20) NULL,
    [zPóstnúmer þjónustuvöru] VARCHAR(10) NULL,
    [Efni til útskuldunar] DECIMAL(38,20) NULL,
    [Vinna til útskuldunar] DECIMAL(38,20) NULL,
    [Annað til útskuldunar] DECIMAL(38,20) NULL,
    [Nr_ aðalþjónustuvöru] VARCHAR(20) NULL,
    [TilboðRukkað] TINYINT NULL,
    [Tilboðsreikn] VARCHAR(20) NULL,
    [UppTilboðsreikn] DECIMAL(38,20) NULL,
    [PopUP] TINYINT NULL,
    [Prenta tilboð með reikningi] TINYINT NULL,
    [Prenta vinnulýsingu með reikn] TINYINT NULL,
    [Prenta athugasemd með vinnul] TINYINT NULL,
    [Hafa samband við Nafn] VARCHAR(80) NULL,
    [Hafa samband við Sími] VARCHAR(30) NULL,
    [ÞP undirrituð við útskuldun] TINYINT NULL,
    [Fastur kóði vinnutegundar] VARCHAR(10) NULL,
    [TilkynningSendNotandi] VARCHAR(20) NULL,
    [TilkynningSendDags] DATETIME NULL,
    [TilkynningSendTimi] DATETIME NULL,
    [Framvindunúmer] INT NULL,
    [FES Niðurtekt _ Aftenging] TINYINT NULL,
    [FES Forgangsviðgerð] TINYINT NULL,
    [FES Eigendaskipti] TINYINT NULL,
    [FES Almennar viðgerðir] TINYINT NULL,
    [FES Ný kerfi vantar búnað] TINYINT NULL,
    [FES Viðbætur] TINYINT NULL,
    [FES Uppsetning] TINYINT NULL,
    [Strikamerki] VARCHAR(20) NULL,
    [Fjöldi pakka] INT NULL,
    [Verknúmer] VARCHAR(20) NULL,
    [External Document No_] VARCHAR(20) NULL,
    [SlítaSamnFrá] TINYINT NULL,
    [Samningsreikningur] TINYINT NULL,
    [Ekki draga saman vörur] TINYINT NULL,
    [Ekki draga saman forða] TINYINT NULL,
    [RSM Provider] INT NULL,
    [Loka án bókun á notkun] TINYINT NULL,
    [POS Sale] TINYINT NULL,
    [Till No_] VARCHAR(20) NULL,
    [Social Security No_] VARCHAR(20) NULL,
    [Cashier Code] VARCHAR(10) NULL,
    [Date Time Posted] DATETIME NULL,
    [Sértexti á reikningi] VARCHAR(40) NULL,
    [Fyrirframgreitt] TINYINT NULL,
    [GeopalJobId] VARCHAR(10) NULL,
    [isGeopalReady] TINYINT NULL,
    [zStaðsetning þjónustuvöru] VARCHAR(80) NULL,
    [dateTimeChanged] TINYINT NULL,
    [GeopalAssignedTo] VARCHAR(10) NULL,
    [SalesforceOrderId] VARCHAR(30) NULL,
    [WorkOrderNumber] VARCHAR(8) NULL
);
