

    CREATE VIEW [cus].[v_ITEM_LOCATION] AS
     SELECT
            CAST(i.ItemCode AS NVARCHAR(255))						AS [ITEM_NO],
            CAST(loc.WhsCode AS NVARCHAR(255))						AS [LOCATION_NO],

			CAST(NULL AS DECIMAL(18,4))								AS [SAFETY_STOCK_UNITS],
			CAST(NULL AS DECIMAL(18,4))								AS [MIN_DISPLAY_STOCK],

			CAST(NULL AS DECIMAL(18,4))								AS [MAX_STOCK],
			CAST(0 AS BIT)											AS [CLOSED],
			CAST(0 AS BIT)											AS [CLOSED_FOR_ORDERING],
			CAST(NULL AS NVARCHAR(255))								AS [RESPONSIBLE],
			CAST(NULL AS NVARCHAR(255))								AS [NAME],
			CAST(NULL AS NVARCHAR(1000))							AS [DESCRIPTION],
			CAST(NULL AS NVARCHAR(255))								AS [PRIMARY_VENDOR_NO],
			CAST(NULL AS INT)										AS [PURCHASE_LEAD_TIME_DAYS],
			CAST(NULL AS SMALLINT)									AS [TRANSFER_LEAD_TIME_DAYS],
			CAST(NULL AS SMALLINT)									AS [ORDER_FREQUENCY_DAYS],
			CAST(NULL AS SMALLINT)									AS [ORDER_COVERAGE_DAYS],
			-- Patrick "Would you please set the MOQ for all locations except GEN to 1" 2024-12-10
			CASE 
			WHEN loc.WhsCode = 'GEN' THEN 
				CAST(ISNULL(i.[MinOrdrQty],1) AS DECIMAL(18,4))
			ELSE 1 END												AS [MIN_ORDER_QTY],
			CAST(NULL AS NVARCHAR(255)) 							AS [ORIGINAL_NO],
			CAST(NULL AS DECIMAL(18,4))								AS [SALE_PRICE],
			CAST(NULL AS DECIMAL(18,4))								AS [COST_PRICE],
			CAST(NULL AS DECIMAL(18,4))								AS [PURCHASE_PRICE],
			NULL 													AS [ORDER_MULTIPLE],
			CAST(NULL AS DECIMAL(18,4))								AS [QTY_PALLET],
			CAST(NULL AS DECIMAL(18,6))								AS [VOLUME],
			CAST(NULL AS DECIMAL(18,6))								AS [WEIGHT],
			CAST(0 AS DECIMAL(18,4))								AS [REORDER_POINT],
			CAST(1 AS BIT)											AS [INCLUDE_IN_AGR],
			CAST(NULL AS BIT)										AS [SPECIAL_ORDER]
	   FROM cus.OITM i
 CROSS JOIN cus.OWHS loc
	  WHERE loc.WhsCode IN ('GEN','NB','NBL','NR','NRL','SPECIALS','WB', 'NSW', 'CST', 'Z-CST')
		AND i.[ItemCode] IS NOT NULL 
		AND i.[ItemName] IS NOT NULL 
		AND i.[ItemName] <> 'DO NOT USE'


