CREATE TABLE [ax_cus].[ECORESCATEGORYHIERARCHY] (
    [NAME] NVARCHAR(128) NOT NULL,
    [HIERARCHYMODIFIER] INT NOT NULL,
    [MODIFIEDDATETIME] DATETIME NOT NULL,
    [MODIFIEDBY] NVARCHAR(8) NOT NULL,
    [CREATEDDATETIME] DATETIME NOT NULL,
    [CREATEDBY] NVARCHAR(8) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_ECORESCATEGORYHIERARCHY] PRIMARY KEY (RECID)
);
