CREATE TABLE [ax_cus].[INVENTTABLE] (
    [ITEMID] NVARCHAR(20) NULL,
    [NAMEALIAS] NVARCHAR(20) NULL,
    [PRIMARYVENDORID] NVARCHAR(20) NULL,
    [ITEMBUYERGROUPID] NVARCHAR(15) NULL,
    [NETWEIGHT] DECIMAL(32,10) NULL,
    [UNITVOLUME] DECIMAL(32,10) NULL,
    [PRODUCT] BIGINT NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [CEPALLETQTY] DECIMAL(32,10) NULL,
    [SPAFACTOR] INT NULL,
    [PDSBESTBEFORE] INT NOT NULL
);
