CREATE VIEW [cus].[v_ITEM]
AS
	WITH RankedItems AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY NO ORDER BY ORIGINAL_NO DESC) AS RowNum FROM cus.ITEM)
	SELECT DISTINCT
        CAST(ri.NO AS NVARCHAR(255))											AS [NO],
        CAST(ri.NAME AS NVARCHAR(255))											AS [NAME],
        CAST(ri.DESCRIPTION AS NVARCHAR(1000))									AS [DESCRIPTION],
        CAST(ri.PRIMARY_VENDOR_NO AS NVARCHAR(255))								AS [PRIMARY_VENDOR_NO],
        CAST(NULLIF(ri.LEAD_TIME_DAYS,'') AS SMALLINT)                AS [PURCHASE_LEAD_TIME_DAYS],
        CAST(NULL AS SMALLINT)													AS [TRANSFER_LEAD_TIME_DAYS],
        CAST(NULLIF(ri.ORDER_FREQUENCY_DAYS,'') AS SMALLINT )         AS [ORDER_FREQUENCY_DAYS],
        CAST(NULLIF(ri.ORDER_COVERAGE_DAYS,'') AS SMALLINT )          AS [ORDER_COVERAGE_DAYS],
        CAST(NULLIF(ri.MIN_ORDER_QTY,'') AS DECIMAL(18,4))            AS [MIN_ORDER_QTY],
        CAST(ri.ORIGINAL_NO AS NVARCHAR(255))									AS [ORIGINAL_NO],
        CAST(NULLIF(ri.CLOSED_FOR_ORDERING,'') AS BIT)                AS [CLOSED],
        CAST(NULLIF(ri.CLOSED_FOR_ORDERING,'') AS BIT)                AS [CLOSED_FOR_ORDERING],
        CAST(ri.RESPONSIBLE AS NVARCHAR(255))									AS [RESPONSIBLE],
        CAST(NULLIF(ri.SALE_PRICE,'') AS DECIMAL(18,4))				AS [SALE_PRICE],
        CAST(NULLIF(ri.COST_PRICE,'') AS DECIMAL(18,4))               AS [COST_PRICE],
        CAST(NULLIF(ri.PURCHASE_PRICE,'') AS DECIMAL(18,4))           AS [PURCHASE_PRICE],
        CAST(NULLIF(ri.ORDER_MULTIPLE,'') AS DECIMAL(18,4))           AS [ORDER_MULTIPLE],
        CAST(NULLIF(ri.QTY_PALLET,'') AS DECIMAL(18,4))               AS [QTY_PALLET],
        CAST(NULLIF(ri.VOLUME,'') AS DECIMAL(18,6))                   AS [VOLUME],
        CAST(NULLIF(ri.WEIGHT,'') AS DECIMAL(18,6))                   AS [WEIGHT],
        CAST(NULLIF(ri.MIN_STOCK,'') AS DECIMAL(18,4))                AS [SAFETY_STOCK_UNITS],
        CAST(NULL AS DECIMAL(18,4))												AS [MIN_DISPLAY_STOCK],
        CAST(NULLIF(ri.MAX_STOCK,'') AS DECIMAL(18,4))                AS [MAX_STOCK],
        CAST(ri.ITEM_GROUP_NO_LVL_1 AS NVARCHAR(255))							AS [ITEM_GROUP_NO_LVL_1],
        CAST(ri.ITEM_GROUP_NO_LVL_2 AS NVARCHAR(255))							AS [ITEM_GROUP_NO_LVL_2],
        CAST(ri.ITEM_GROUP_NO_LVL_3 AS NVARCHAR(255))							AS [ITEM_GROUP_NO_LVL_3],
        CAST(ri.BASE_UNIT_OF_MEASURE AS NVARCHAR(50))							AS [BASE_UNIT_OF_MEASURE],
        CAST(ri.PURCHASE_UNIT_OF_MEASURE AS NVARCHAR(50))						AS [PURCHASE_UNIT_OF_MEASURE],
        CAST(NULLIF(ri.QTY_PER_PURCHASE_UNIT,'') AS DECIMAL(18,4))    AS [QTY_PER_PURCHASE_UNIT],
        CAST(ISNULL(NULLIF(ri.REORDER_POINT,''),0) AS DECIMAL(18,4))			AS [REORDER_POINT],
        CAST(NULLIF(ri.SPECIAL_ORDER,'') AS BIT)                      AS [SPECIAL_ORDER],
        CAST(1 AS BIT)															AS [INCLUDE_IN_AGR]
	FROM
        [cus].[ITEM] i
		LEFT JOIN (SELECT * FROM RankedItems WHERE RowNum = 1) AS ri ON i.NO = ri.NO

