CREATE VIEW cus.v_OPEN_SALES_ORDER
AS

	SELECT 
		CAST(SALES_ORDER_NO AS NVARCHAR(128))           AS SALES_ORDER_NO,
		CAST(ITEM_NO AS NVARCHAR(255))                  AS ITEM_NO,
		CAST(LOCATION_NO AS NVARCHAR(255))              AS LOCATION_NO,
		SUM(CAST(QUANTITY AS DECIMAL(18,4)))            AS QUANTITY,
		CAST(CUSTOMER_NO AS NVARCHAR(255))               AS CUSTOMER_NO,
		CAST(ISNULL(DELIVERY_DATE, GETDATE()) AS DATE)  AS DELIVERY_DATE
	FROM 
		cus.OPEN_SALES_ORDER
	WHERE CAST(ISNULL(DELIVERY_DATE, GETDATE()) AS DATE) > DATEADD(month, -2, Convert(date, GetDate()))
	GROUP BY
		SALES_ORDER_NO,
		ITEM_NO,
		LOCATION_NO,
		CUSTOMER_NO,
		DELIVERY_DATE

