CREATE VIEW cus.v_PURCHASE_ORDER_ROUTE
AS
	WITH RankedPOR AS (
    SELECT 
        CAST(ITEM_NO AS NVARCHAR(255))          AS [ITEM_NO],
        CAST(LOCATION_NO AS NVARCHAR(255))      AS [LOCATION_NO],
        CAST(VENDOR_NO AS NVARCHAR(255))        AS [VENDOR_NO],
        CAST(1 AS BIT)                  AS [PRIMARY],
        CAST(LEAD_TIME_DAYS AS SMALLINT)        AS [LEAD_TIME_DAYS],
        CAST(NULLIF(ORDER_FREQUENCY_DAYS,'') AS SMALLINT)  AS [ORDER_FREQUENCY_DAYS],
        CAST(MIN_ORDER_QTY AS DECIMAL(18,4))    AS [MIN_ORDER_QTY],    
        CAST(NULLIF(COST_PRICE,'') AS DECIMAL(18,4))       AS [COST_PRICE],
        CAST(PURCHASE_PRICE AS DECIMAL(18,4))   AS [PURCHASE_PRICE],
        CAST(NULLIF(ORDER_MULTIPLE,'') AS DECIMAL(18,4))   AS [ORDER_MULTIPLE],  
        CAST(NULLIF(QTY_PALLET,'') AS DECIMAL(18,4))       AS [QTY_PALLET],
		ROW_NUMBER() OVER (PARTITION BY ITEM_NO ORDER BY DATE DESC) AS [RANK]
    FROM [cus].[PURCHASE_ORDER_ROUTE])
	SELECT  RankedPOR.ITEM_NO, 
			RankedPOR.LOCATION_NO, 
			RankedPOR.VENDOR_NO, 
			RankedPOR.[PRIMARY], 
			RankedPOR.LEAD_TIME_DAYS, 
			RankedPOR.ORDER_FREQUENCY_DAYS, 
			RankedPOR.MIN_ORDER_QTY, 
			RankedPOR.COST_PRICE,
			RankedPOR.PURCHASE_PRICE,
			RankedPOR.[ORDER_MULTIPLE],
			RankedPOR.QTY_PALLET
	FROM RankedPOR
	WHERE RankedPOR.[RANK] = 1

