-- ===============================================================================
CREATE VIEW [cus].[v_UNDELIVERED_PURCHASE_ORDER]
AS

  SELECT
    CAST(PURCHASE_ORDER_NO AS NVARCHAR(128))              AS [PURCHASE_ORDER_NO],
    CAST(ITEM_NO AS NVARCHAR(255))                        AS [ITEM_NO],
    CAST(LOCATION_NO AS NVARCHAR(255))                    AS [LOCATION_NO],
    MIN(CAST(ISNULL(DELIVERY_DATE, GETDATE()) AS DATE))   AS [DELIVERY_DATE],
    SUM(CAST(QUANTITY AS DECIMAL(18,4)))              AS [QUANTITY]
  FROM [cus].[UNDELIVERED_PURCHASE_ORDER]
  WHERE DELIVERY_DATE >= GETDATE()
	GROUP BY 
    PURCHASE_ORDER_NO, ITEM_NO, LOCATION_NO, DELIVERY_DATE
