CREATE VIEW [cus].[v_ITEM] AS
	   SELECT
        CAST(i.[ITEMNUMBER]												AS NVARCHAR(255)) AS [NO],
        CAST(i.[ITEMNAME1]												AS NVARCHAR(255)) AS [NAME],
        CAST(i.[ITEMNAME1]												AS NVARCHAR(1000)) AS [DESCRIPTION],
        CAST(TRIM(i.[PRIMARYVENDOR])									AS NVARCHAR(255)) AS [PRIMARY_VENDOR_NO],
        CAST(v.LEADTIME AS SMALLINT)									AS [PURCHASE_LEAD_TIME_DAYS],
        CAST(NULL AS SMALLINT)											AS [TRANSFER_LEAD_TIME_DAYS],
        CAST(NULL AS SMALLINT )											AS [ORDER_FREQUENCY_DAYS],
        CAST(NULL AS SMALLINT )											AS [ORDER_COVERAGE_DAYS],
        CAST(i.[PURCHSERIESSIZE]										AS DECIMAL(18,4)) AS [MIN_ORDER_QTY],
        CAST(i.[VENDITEMNUMBER]											AS NVARCHAR(50)) AS [ORIGINAL_NO],
        CAST(i.[BLOCKED] AS BIT)										AS [CLOSED_FOR_ORDERING],
        CAST(ISNULL(v.PURCHASER,'') AS NVARCHAR(255))					AS [RESPONSIBLE],
        CAST(0 AS DECIMAL(18,4))										AS [SALE_PRICE],
        CAST(i.[COSTPRICE] AS DECIMAL(18,4))							AS [COST_PRICE],
        CAST(i.[COSTPRICE] AS DECIMAL(18,4))							AS [PURCHASE_PRICE],
        CAST(ISNULL(NULLIF(i.PURCHSERIESSIZE,0),1) AS DECIMAL(18,4))	AS [ORDER_MULTIPLE],
        CAST(1 AS DECIMAL(18,4))										AS [QTY_PALLET],
        CAST(i.[VOLUME] AS DECIMAL(18,6))								AS [VOLUME],
        CAST(i.[NETWEIGHT] AS DECIMAL(18,6))							AS [WEIGHT],

        CAST(i.[ANTAL1] AS DECIMAL(18,4))								AS [SAFETY_STOCK_UNITS],
        CAST(NULL AS DECIMAL(18,4))										AS [MIN_DISPLAY_STOCK],

        CAST(NULL AS DECIMAL(18,4))										AS [MAX_STOCK],
        CAST(ig.[GROUP_] AS NVARCHAR(255))								AS [ITEM_GROUP_NO_LVL_1],
        CAST(NULL AS NVARCHAR(255))										AS [ITEM_GROUP_NO_LVL_2],
        CAST(NULL AS NVARCHAR(255))										AS [ITEM_GROUP_NO_LVL_3],
        CAST(i.COSTPRICEUNIT AS NVARCHAR(50))							AS [BASE_UNIT_OF_MEASURE],
        CAST(i.COSTPRICEUNIT AS NVARCHAR(50))							AS [PURCHASE_UNIT_OF_MEASURE],
        CAST(1 AS DECIMAL(18,4))										AS [QTY_PER_PURCHASE_UNIT],
        CASE WHEN i.[CHEMICALSAFETY] = 1 
		THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END						AS [SPECIAL_ORDER],
        CAST(0 AS DECIMAL(18,4))										AS [REORDER_POINT],
		CAST(1 AS BIT)													AS [INCLUDE_IN_AGR],
		CASE WHEN i.BLOCKED = 1 OR i.UDGXR = 1
		THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END 					AS [CLOSED]
    FROM
        [cus].[INVENTABLE] i
        LEFT JOIN [cus].[INVENITEMGROUP] ig ON ig.GROUP_ = i.GROUP_ AND i.DATASET = ig.DATASET
		LEFT JOIN [cus].[VENDTABLE] v ON v.ACCOUNT = i.PRIMARYVENDOR AND i.DATASET = v.DATASET
		LEFT JOIN [cus].[INVENTORYSUM] ivs ON ivs.ITEMNUMBER = i.ITEMNUMBER AND ivs.DATASET = i.DATASET AND ivs.INVENLOCATION LIKE '%' + CHAR(2) + '%'
   WHERE i.[DATASET] = 'DAT'
		 AND i.[ITEMNUMBER] NOT LIKE ('981%')  AND i.[ITEMNUMBER] NOT LIKE ('SG %')     AND i.[ITEMNUMBER] NOT LIKE ('DB %')          AND i.[ITEMNUMBER] NOT LIKE ('CS %') 
		 AND i.[ITEMNUMBER] NOT LIKE ('DA %')  AND i.[ITEMNUMBER] NOT LIKE ('241 %')    AND i.[ITEMNUMBER] NOT LIKE ('WEBFRAGT%')    AND i.[ITEMNUMBER] NOT LIKE ('999%') 
		 AND i.[ITEMNUMBER] NOT LIKE ('996 %') AND i.[ITEMNUMBER] NOT LIKE ('99009%')  AND i.[ITEMNUMBER] NOT LIKE ('982 %')         AND i.[ITEMNUMBER] NOT LIKE ('983 %') 
		 AND i.[ITEMNUMBER] NOT LIKE ('984 %') AND i.[ITEMNUMBER] NOT LIKE ('985 %')    AND i.[ITEMNUMBER] NOT LIKE ('986 %') 
		 AND i.[ITEMTYPE] = 0
		 -- Karolina - Items that start with 981, SG , DB , CS , DA , 241 , WEBFRAGT, 999, 996 , 99009, 982 , 983 , 984 , 985 , 986 should be excluded

