

CREATE VIEW [cus].[v_SALES_HISTORY] 
AS

      SELECT
            CAST([ROWNUMBER] AS NVARCHAR(255)) AS [TRANSACTION_ID],
            CAST([ITEMNUMBER] AS NVARCHAR(255)) AS [ITEM_NO],
            CAST([INVENLOCATION] AS NVARCHAR(255)) AS [LOCATION_NO],
            CAST(CONVERT(DATE, [DATE_], 103) AS DATE) AS [DATE],
            CAST(-SUM(QTY) AS DECIMAL(18, 4)) AS [SALE],
            CAST([ACCOUNT] AS NVARCHAR(255)) AS [CUSTOMER_NO],
            CAST([NUMBER_] AS NVARCHAR(255)) AS [REFERENCE_NO],
            CAST(0 AS BIT) AS [IS_EXCLUDED]
       FROM [cus].[INVENTRANS] 
	   WHERE [DATASET] = 'DAT' AND ACCOUNT  IS NOT NULL
	   AND [MODULE]  = '5'
	   GROUP BY [ROWNUMBER], [ITEMNUMBER], [INVENLOCATION], CONVERT(DATE, [DATE_], 103), ACCOUNT, [NUMBER_]  

