CREATE TABLE [ax_cus].[CUSTINVOICEJOUR] (
    [RECID] BIGINT NOT NULL,
    [INVOICEID] NVARCHAR(20) NULL,
    [INVOICEDATE] DATETIME NULL,
    [ORDERACCOUNT] NVARCHAR(20) NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTITION] NVARCHAR(100) NULL,
    CONSTRAINT [pk_CUSTINVOICEJOUR] PRIMARY KEY (RECID)
);
