CREATE TABLE [ax_cus].[Customer_nor_sve] (
    [ACCOUNTNUM] NVARCHAR(20) NULL,
    [NAME] NVARCHAR(100) NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL
);
