CREATE TABLE [ax_cus].[CUSTINVOICETRANS] (
    [RECID] BIGINT NOT NULL,
    [INVOICEID] NVARCHAR(20) NULL,
    [INVOICEDATE] DATETIME NULL,
    [ITEMID] NVARCHAR(20) NULL,
    [SALESID] NVARCHAR(50) NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTITION] NVARCHAR(100) NULL,
    CONSTRAINT [pk_CUSTINVOICETRANS] PRIMARY KEY (RECID)
);
