CREATE TABLE [ax_cus].[INVENTTABLE_extra] (
    [ITEMID] NVARCHAR(20) NULL,
    [STANDARDPALLETQUANTITY] DECIMAL(32,10) NULL,
    [TARAWEIGHT] DECIMAL(32,10) NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL,
    [DATAAREAID] NVARCHAR(4) NULL
);
