CREATE TABLE [cus].[ItemSupplier] (
    [fkStockItemId] NVARCHAR(255) NULL,
    [fkSupplierId] NVARCHAR(255) NULL,
    [rowid] NVARCHAR(255) NULL,
    [IsDefault] NVARCHAR(255) NULL,
    [SupplierCode] NVARCHAR(255) NULL,
    [SupplierCode2] NVARCHAR(255) NULL,
    [SupplierBarcode] NVARCHAR(255) NULL,
    [LeadTime] NVARCHAR(255) NULL,
    [KnownPurchasePrice] NVARCHAR(255) NULL,
    [AvgPurchasePrice] NVARCHAR(255) NULL,
    [AvgLeadTime] NVARCHAR(255) NULL,
    [MaxLeadTime] NVARCHAR(255) NULL,
    [MinOrder] NVARCHAR(255) NULL,
    [OnHand] NVARCHAR(255) NULL,
    [MinPurchasePrice] NVARCHAR(255) NULL,
    [MaxPurchasePrice] NVARCHAR(255) NULL,
    [AvgPurchaseQty] NVARCHAR(255) NULL,
    [SupplierMinOrderQty] NVARCHAR(255) NULL,
    [SupplierPackSize] NVARCHAR(255) NULL,
    [LeadTimeVector] NVARCHAR(255) NULL,
    [Currency] NVARCHAR(255) NULL,
    [fkStockLocationId] NVARCHAR(255) NULL
);
