CREATE TABLE [cus].[Open_OrderItem] (
    [rowid] NVARCHAR(255) NULL,
    [fkOrderID] NVARCHAR(255) NULL,
    [fPricePerUnit] NVARCHAR(255) NULL,
    [nQty] NVARCHAR(255) NULL,
    [ItemNumber] NVARCHAR(255) NULL,
    [fkLocationId] NVARCHAR(255) NULL,
    [fkCompositeParentRowId] NVARCHAR(255) NULL,
    [ChannelSKU] NVARCHAR(255) NULL,
    [fkStockItemId] NVARCHAR(255) NULL,
    [SalesTax] NVARCHAR(255) NULL,
    [TaxRate] NVARCHAR(255) NULL,
    [TaxCostInclusive] NVARCHAR(255) NULL,
    [Cost] NVARCHAR(255) NULL,
    [CostIncTax] NVARCHAR(255) NULL,
    [PartShipped] NVARCHAR(255) NULL,
    [LineDiscount] NVARCHAR(255) NULL,
    [IsService] NVARCHAR(255) NULL,
    [ItemSource] NVARCHAR(255) NULL,
    [PartShippedQty] NVARCHAR(255) NULL,
    [OriginalTitle] NVARCHAR(1000) NULL,
    [AffectingStockLevel] NVARCHAR(255) NULL,
    [fkStockId] NVARCHAR(255) NULL,
    [fkImageId] NVARCHAR(255) NULL,
    [AddedDate] NVARCHAR(255) NULL
);
