CREATE TABLE [cus].[Purchase] (
    [pkPurchaseID] NVARCHAR(255) NULL,
    [fkSupplierId] NVARCHAR(255) NULL,
    [fkLocationId] NVARCHAR(255) NULL,
    [DateOfPurchase] NVARCHAR(255) NULL,
    [DateOfDelivery] NVARCHAR(255) NULL,
    [QuotedDeliveryDate] NVARCHAR(255) NULL,
    [ExternalInvoiceNumber] NVARCHAR(255) NULL,
    [PostagePaid] NVARCHAR(255) NULL,
    [TotalCost] NVARCHAR(255) NULL,
    [taxPaid] NVARCHAR(255) NULL,
    [Status] NVARCHAR(255) NULL,
    [PaymentStatus] NVARCHAR(255) NULL,
    [Currency] NVARCHAR(255) NULL,
    [ShippingTaxRate] NVARCHAR(255) NULL,
    [ConversionRate] NVARCHAR(255) NULL,
    [SupplierReferenceNumber] NVARCHAR(255) NULL,
    [Locked] NVARCHAR(255) NULL,
    [UnitAmountTaxIncludedType] NVARCHAR(255) NULL,
    [ConvertedShippingCost] NVARCHAR(255) NULL,
    [ConvertedShippingTax] NVARCHAR(255) NULL,
    [ConvertedOtherCost] NVARCHAR(255) NULL,
    [ConvertedOtherTax] NVARCHAR(255) NULL,
    [ConvertedGrandTotal] NVARCHAR(255) NULL
);
