CREATE TABLE [ax_cus].[BYKPRODUCTCATEGORYINCLUDEVARIANT] (
    [CATEGORY] BIGINT NOT NULL,
    [ITEMID] NVARCHAR(20) NOT NULL,
    [RETAILSTOREID] NVARCHAR(10) NOT NULL,
    [VARIANT] BIGINT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [SIZEID] NVARCHAR(20) NULL,
    CONSTRAINT [PK_erp_cus_BYKPRODUCTCATEGORYINCLUDEVARIANT] PRIMARY KEY (RECID)
);
