CREATE TABLE [ax_cus].[DIRPARTYTABLE] (
    [NAME] NVARCHAR(100) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_erp_cus_DIRPARTYTABLE] PRIMARY KEY (RECID)
);
