CREATE TABLE [ax_cus].[ECORESCATEGORY] (
    [CATEGORYHIERARCHY] BIGINT NOT NULL,
    [PARENTCATEGORY] BIGINT NOT NULL,
    [NAME] NVARCHAR(254) NOT NULL,
    [CODE] NVARCHAR(20) NOT NULL,
    [ISACTIVE] INT NOT NULL,
    [CHANGESTATUS] INT NOT NULL,
    [LEVEL_] BIGINT NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RELATIONTYPE] BIGINT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [BYKRETAILSTORENO] NVARCHAR(10) NULL,
    CONSTRAINT [PK_ax_cus_ECORESCATEGORY] PRIMARY KEY (RECID)
);
