CREATE TABLE [ax_cus].[ECORESCATEGORYHIERARCHYROLE] (
    [NAMEDCATEGORYHIERARCHYROLE] INT NOT NULL,
    [CATEGORYHIERARCHY] BIGINT NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_ECORESCATEGORYHIERARCHYROLE] PRIMARY KEY (RECID)
);
