CREATE TABLE [ax_cus].[INVENTITEMPURCHSETUP] (
    [ITEMID] NVARCHAR(20) NOT NULL,
    [INVENTDIMID] NVARCHAR(20) NOT NULL,
    [INVENTDIMIDDEFAULT] NVARCHAR(20) NOT NULL,
    [MULTIPLEQTY] NUMERIC(32,16) NOT NULL,
    [LOWESTQTY] NUMERIC(32,16) NOT NULL,
    [HIGHESTQTY] NUMERIC(32,16) NOT NULL,
    [STANDARDQTY] NUMERIC(32,16) NOT NULL,
    [LEADTIME] INT NOT NULL,
    [STOPPED] INT NOT NULL,
    [OVERRIDE] INT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_INVENTITEMPURCHSETUP] PRIMARY KEY (DATAAREAID,INVENTDIMID,ITEMID,PARTITION)
);
