CREATE TABLE [ax_cus].[INVENTDIMCOMBINATION] (
    [ITEMID] NVARCHAR(20) NOT NULL,
    [INVENTDIMID] NVARCHAR(20) NOT NULL,
    [DISTINCTPRODUCTVARIANT] BIGINT NOT NULL,
    [RETAILVARIANTID] NVARCHAR(10) NOT NULL,
    [CREATEDDATETIME] DATETIME NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_INVENTDIMCOMBINATION] PRIMARY KEY (DATAAREAID,INVENTDIMID,ITEMID,PARTITION)
);
