CREATE TABLE [ax_cus].[INVENTJOURNALTABLE] (
    [JOURNALID] NVARCHAR(10) NOT NULL,
    [DESCRIPTION] NVARCHAR(60) NOT NULL,
    [POSTED] INT NOT NULL,
    [RESERVATION] INT NOT NULL,
    [POSTEDDATETIME] DATETIME NOT NULL,
    [JOURNALTYPE] INT NOT NULL,
    [NUMOFLINES] INT NOT NULL,
    [INVENTLOCATIONID] NVARCHAR(10) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [BYKDOLPHININVENTJOURNALSTATUS] INT NOT NULL,
    [BYKINVENTJOURNALTABLECOMMENT] NVARCHAR(250) NOT NULL,
    [BYKWORKERINVENTJOURNALRESPONSIBLE] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_INVENTJOURNALTABLE] PRIMARY KEY (DATAAREAID,JOURNALID,PARTITION)
);
