CREATE TABLE [ax_cus].[INVENTBUYERGROUP] (
    [DESCRIPTION] NVARCHAR(60) NOT NULL,
    [GROUP_] NVARCHAR(10) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_erp_cus_INVENTBUYERGROUP] PRIMARY KEY (DATAAREAID,GROUP_,PARTITION)
);
