CREATE TABLE [ax_cus].[INVENTTRANSFERLINE] (
    [TRANSFERID] NVARCHAR(20) NULL,
    [ITEMID] NVARCHAR(20) NULL,
    [INVENTDIMID] NVARCHAR(20) NULL,
    [QTYREMAINRECEIVE] DECIMAL(32,10) NULL,
    [RECEIVEDATE] DATETIME NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL
);
