CREATE TABLE [ax_cus].[PRICEDISCTABLE] (
    [ITEMCODE] INT NOT NULL,
    [ACCOUNTCODE] INT NOT NULL,
    [ITEMRELATION] NVARCHAR(20) NOT NULL,
    [ACCOUNTRELATION] NVARCHAR(20) NOT NULL,
    [FROMDATE] DATETIME NOT NULL,
    [TODATE] DATETIME NOT NULL,
    [AMOUNT] NUMERIC(32,16) NOT NULL,
    [CURRENCY] NVARCHAR(3) NOT NULL,
    [RELATION] INT NOT NULL,
    [UNITID] NVARCHAR(10) NOT NULL,
    [INVENTDIMID] NVARCHAR(20) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_PRICEDISCTABLE] PRIMARY KEY (RECID)
);
