CREATE TABLE [ax_cus].[REQGROUP] (
    [REQGROUPID] NVARCHAR(10) NOT NULL,
    [NAME] NVARCHAR(60) NOT NULL,
    [COVTIMEFENCE] INT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_REQGROUP] PRIMARY KEY (DATAAREAID,PARTITION,REQGROUPID)
);
