CREATE TABLE [ax_cus].[REQSAFETYLINE] (
    [SAFETYFACTOR] NUMERIC(32,16) NOT NULL,
    [SAFETYKEYID] NVARCHAR(10) NOT NULL,
    [FREQCODE] INT NOT NULL,
    [FREQ] INT NOT NULL,
    [SORT1980] DATETIME NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_REQSAFETYLINE] PRIMARY KEY (RECID)
);
