CREATE TABLE [ax_cus].[REQSAFETYKEY] (
    [FIXED] INT NOT NULL,
    [NAME] NVARCHAR(60) NOT NULL,
    [SAFETYKEYID] NVARCHAR(10) NOT NULL,
    [FIXEDDATE] DATETIME NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_REQSAFETYKEY] PRIMARY KEY (DATAAREAID,PARTITION,SAFETYKEYID)
);
