CREATE TABLE [ax_cus].[RETAILASSORTMENTLOOKUPCHANNELGROUP] (
    [ASSORTMENTID] BIGINT NOT NULL,
    [OMOPERATINGUNITID] BIGINT NOT NULL,
    [RETAILCHANNELTABLE] BIGINT NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_RETAILASSORTMENTLOOKUPCHANNELGROUP] PRIMARY KEY (RECID)
);
