CREATE TABLE [ax_cus].[UNITOFMEASURE] (
    [SYMBOL] NVARCHAR(10) NOT NULL,
    [UNITOFMEASURECLASS] INT NOT NULL,
    [SYSTEMOFUNITS] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_UNITOFMEASURE] PRIMARY KEY (RECID)
);
