
CREATE VIEW [ax_cus].[v_STOCK_LEVEL] 
AS



	SELECT
        CAST(t1.ITEMID AS NVARCHAR(255))								AS ITEM_NO,
        CAST(t2.INVENTLOCATIONID AS NVARCHAR(255))						AS LOCATION_NO,
        CAST(ISNULL(CASE WHEN IB.EXPDATE = '1900-01-01' 
					THEN '2100-01-01' 
					ELSE DATEADD(dd,-IT.PDSBESTBEFORE, IB.EXPDATE) 
					END, '2100-01-01')
			AS DATE)													AS EXPIRE_DATE,
        CAST(SUM(t1.PHYSICALINVENT)  AS DECIMAL(18,4))					AS STOCK_UNITS
    FROM ax.INVENTSUM t1 -- ITAMID
	INNER JOIN ax_cus.DataAreas AS DA 
		ON DA.DataAreaId  = t1.DATAAREAID
		AND DA.Partition = t1.PARTITION
	INNER JOIN	ax_cus.InventDim t2  
		ON	t2.INVENTDIMID = t1.INVENTDIMID
		AND t2.DATAAREAID = t1.DATAAREAID 
		AND t2.PARTITION = t1.PARTITION
		AND t2.INVENTLOCATIONID <> ''
	INNER JOIN ax_cus.INVENTTABLE AS IT
		ON t1.ITEMID = IT.ITEMID
		AND DA.DATAAREAID = IT.DATAAREAID
		AND DA.PARTITION = IT.PARTITION
	LEFT OUTER JOIN ax_cus.INVENTBATCH AS IB 
		ON 	IB.INVENTBATCHID = t2.INVENTBATCHID 
		AND IB.ITEMID = t1.ITEMID 
		AND IB.DATAAREAID = DA.DataAreaId
		AND IB.PARTITION = DA.Partition
	WHERE t1.CLOSED = 0
		AND	t1.PHYSICALINVENT <> 0
		AND t2.INVENTLOCATIONID <> ''
		AND ISNULL(CASE WHEN IB.EXPDATE = '1900-01-01' 
					THEN '2100-01-01' 
					ELSE DATEADD(dd,-IT.PDSBESTBEFORE, IB.EXPDATE) 
					END, '2100-01-01') > GETDATE()
		AND t2.inventstatusid NOT IN ('Merktvv', 'Ómerktvv', 'Gallað', 'Útrunnið', 'Aðföng','Krónan','Samkaup')
	GROUP BY 
		t1.ITEMID,
		t2.INVENTLOCATIONID,
		ISNULL(CASE WHEN IB.EXPDATE = '1900-01-01' 
				THEN '2100-01-01' 
				ELSE DATEADD(dd,-IT.PDSBESTBEFORE, IB.EXPDATE) 
				END, '2100-01-01')		


