CREATE TABLE [cus].[CUSTTABLE] (
    [ROWNUMBER] INT NOT NULL,
    [ACCOUNT] VARCHAR(10) NOT NULL,
    [NAME] VARCHAR(50) NOT NULL,
    [BLOCKED] INT NOT NULL,
    [DATASET] VARCHAR(3) NOT NULL,
    CONSTRAINT [PK_CUSTTABLE] PRIMARY KEY (DATASET,ROWNUMBER)
);
