CREATE TABLE [cus].[INVENLOCATION] (
    [DATASET] VARCHAR(3) NOT NULL,
    [ROWNUMBER] INT NOT NULL,
    [LASTCHANGED] DATETIME NOT NULL,
    [INVENLOCATION] VARCHAR(10) NOT NULL,
    [NAME] VARCHAR(30) NOT NULL,
    [RESERVED1] VARCHAR(10) NOT NULL,
    CONSTRAINT [PK_INVENLOCATION] PRIMARY KEY (DATASET,ROWNUMBER)
);
