CREATE TABLE [cus].[INVENPRICE] (
    [DATASET] VARCHAR(3) NOT NULL,
    [ROWNUMBER] INT NOT NULL,
    [LASTCHANGED] DATETIME NOT NULL,
    [ITEMNUMBER] VARCHAR(20) NOT NULL,
    [PRICE] NUMERIC(28,12) NOT NULL,
    [PRICEUNIT] NUMERIC(28,12) NOT NULL,
    [CURRENCY] VARCHAR(3) NOT NULL,
    [PRICEGROUP] VARCHAR(10) NOT NULL,
    [CONTRIBUTIONRATIO] NUMERIC(28,12) NOT NULL,
    [DATE_] DATETIME NOT NULL,
    [SALESVAT] VARCHAR(10) NOT NULL,
    [PRICE_ORIG] NUMERIC(28,12) NOT NULL,
    CONSTRAINT [PK_INVENPRICE] PRIMARY KEY (DATASET,ROWNUMBER)
);
