CREATE TABLE [cus].[SALESTABLE] (
    [DATASET] VARCHAR(3) NOT NULL,
    [ROWNUMBER] INT NOT NULL,
    [NUMBER_] VARCHAR(10) NOT NULL,
    [ORDERPHASE] INT NULL,
    CONSTRAINT [PK_SALESTABLE] PRIMARY KEY (DATASET,ROWNUMBER)
);
