CREATE TABLE [cus].[VENDTABLE] (
    [DATASET] VARCHAR(3) NOT NULL,
    [ROWNUMBER] INT NOT NULL,
    [LASTCHANGED] DATETIME NOT NULL,
    [ACCOUNT] VARCHAR(10) NOT NULL,
    [NAME] VARCHAR(50) NOT NULL,
    [COUNTRY] VARCHAR(30) NOT NULL,
    [DELIVERY] VARCHAR(10) NOT NULL,
    [BLOCKED] INT NOT NULL,
    [PURCHASER] VARCHAR(10) NOT NULL,
    [LEADTIME] INT NULL,
    CONSTRAINT [PK_VENDTABLE] PRIMARY KEY (DATASET,ROWNUMBER)
);
