

CREATE VIEW [bc_rest_cus].[v_SALES_HISTORY_LEGACY] --schema used in tenant
AS
	SELECT
          CAST(shl.ITEM_NO AS NVARCHAR(255)) AS [ITEM_NO],
          CAST('VARAHLUTIR' AS NVARCHAR(255)) AS [LOCATION_NO],
          CAST(shl.DATE AS DATE) AS [DATE],
          CAST(SUM(shl.SALE) AS DECIMAL(18,4)) AS [SALE],
		  CAST(ISNULL(shl.CUSTOMER_NO, 'agr_no_customer') AS NVARCHAR(255)) AS CUSTOMER_NO,
		  CAST(ISNULL(shl.REFERENCE_NO,'' )AS NVARCHAR(255)) AS REFERENCE_NO
    FROM
         bc_rest_cus.MC_LEGACY_SALES_01072025_DFS shl
    GROUP BY
         shl.ITEM_NO,
		 shl.DATE,
		 CAST(ISNULL(shl.CUSTOMER_NO, 'agr_no_customer') AS NVARCHAR(255)),
		 CAST(ISNULL(shl.REFERENCE_NO,'' )AS NVARCHAR(255))

UNION ALL

	SELECT
          CAST(shl.ITEM_NO AS NVARCHAR(255)) AS [ITEM_NO],
          CAST('VARAHLUTIR' AS NVARCHAR(255)) AS [LOCATION_NO],
          CAST(shl.DATE AS DATE) AS [DATE],
          CAST(SUM(shl.SALE) AS DECIMAL(18,4)) AS [SALE],
		  CAST('agr_no_customer' AS NVARCHAR(255)) AS CUSTOMER_NO,
		  CAST('' AS NVARCHAR(255)) AS REFERENCE_NO
    FROM
         dbo.SALE_HISTORY_LEGACY_20250128 shl
    GROUP BY
         shl.ITEM_NO,
		 shl.DATE

   

