
CREATE VIEW [fo_cus].[v_ITEM_GROUP]
AS

    SELECT DISTINCT
        CAST(p.PRODUCTGROUPID AS NVARCHAR(255)) AS [NO],
        CAST(p.PRODUCTGROUPID  AS NVARCHAR(255))AS [NAME]
    FROM fo_cus.Products p

