
CREATE VIEW [fo_cus].[v_stock_history]
AS


   SELECT
    CAST(NULL AS NVARCHAR(128)) AS [TRANSACTION_ID],
    CAST(pol.ITEMNUMBER AS NVARCHAR(255)) AS [ITEM_NO],
    CAST(ISNULL(pol.RECEIVINGWAREHOUSEID,'') AS NVARCHAR(255)) AS [location_no],
	CAST(pol.CONFIRMEDDELIVERYDATE AS DATE) AS [date],
    CAST(SUM(CAST(pol.ORDEREDPURCHASEQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [STOCK_MOVE],
	CAST(NULL AS NVARCHAR(255)) AS STOCK_LEVEL
FROM fo_cus.[PurchaseOrderLines] pol
WHERE 
    CAST(pol.ITEMNUMBER AS NVARCHAR(255)) IS NOT NULL
GROUP BY 
    pol.PURCHASEORDERNUMBER,
    pol.ITEMNUMBER,
    pol.RECEIVINGWAREHOUSEID,
    pol.CONFIRMEDDELIVERYDATE
	
	UNION ALL

	SELECT
    CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
    CAST(sol.ITEMNUMBER AS NVARCHAR(255)) AS ITEM_NO,
    CAST(ISNULL(sol.SHIPPINGWAREHOUSEID,'') AS NVARCHAR(255)) AS LOCATION_NO,
    CAST(sol.CONFIRMEDRECEIPTDATE AS DATE) AS [DATE],
    CAST(-SUM(CAST(sol.ORDEREDSALESQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS STOCK_MOVE,
    CAST(NULL AS NVARCHAR(255)) AS STOCK_LEVEL
FROM fo.SalesOrderLines sol 
WHERE
    sol.SALESORDERLINESTATUS <> 'Canceled' AND sol.CONFIRMEDRECEIPTDATE <= CAST(GETUTCDATE() AS DATE)
GROUP BY
    sol.ITEMNUMBER,
	sol.SHIPPINGWAREHOUSEID,
	sol.CONFIRMEDRECEIPTDATE

