CREATE TABLE [cus].[OINM] (
    [TransNum] INT NULL,
    [TransType] INT NULL,
    [CreatedBy] INT NULL,
    [BASE_REF] NVARCHAR(11) NULL,
    [DocLineNum] INT NULL,
    [DocDate] DATETIME NULL,
    [DocDueDate] DATETIME NULL,
    [CardCode] NVARCHAR(15) NULL,
    [CardName] NVARCHAR(100) NULL,
    [Ref1] NVARCHAR(11) NULL,
    [Ref2] NVARCHAR(100) NULL,
    [Comments] NVARCHAR(254) NULL,
    [JrnlMemo] NVARCHAR(50) NULL,
    [DocTime] SMALLINT NULL,
    [ItemCode] NVARCHAR(50) NULL,
    [Dscription] NVARCHAR(200) NULL,
    [InQty] NUMERIC(19,6) NULL,
    [OutQty] NUMERIC(19,6) NULL,
    [Price] NUMERIC(19,6) NULL,
    [Currency] NVARCHAR(3) NULL,
    [Rate] NUMERIC(19,6) NULL,
    [VendorNum] NVARCHAR(50) NULL,
    [SerialNum] NVARCHAR(17) NULL,
    [Warehouse] NVARCHAR(8) NULL,
    [TreeType] CHAR(1) NULL,
    [SlpCode] INT NULL,
    [TaxDate] DATETIME NULL,
    [DataSource] CHAR(1) NULL,
    [PrjCode] NVARCHAR(20) NULL,
    [UserSign] SMALLINT NULL,
    [BlockNum] NVARCHAR(100) NULL,
    [ImportLog] NVARCHAR(20) NULL,
    [UseDocPric] CHAR(1) NULL,
    [Location] INT NULL,
    [CalcPrice] NUMERIC(19,6) NULL,
    [OpenQty] NUMERIC(19,6) NULL,
    [Instance] INT NULL,
    [LastInst] INT NOT NULL,
    [RevalTotal] NUMERIC(19,6) NULL,
    [BaseCurr] NVARCHAR(1) NOT NULL,
    [ApplObj] INT NULL,
    [AppObjAbs] INT NULL,
    [AppObjType] CHAR(1) NULL,
    [StockAct] NVARCHAR(1) NOT NULL,
    [TrnsfrAct] NVARCHAR(15) NULL,
    [PriceDifAc] NVARCHAR(15) NULL,
    [VarianceAc] NVARCHAR(15) NULL,
    [ReturnAct] NVARCHAR(15) NULL,
    [ExcRateAct] NVARCHAR(15) NULL,
    [ClearAct] NVARCHAR(15) NULL,
    [CostAct] NVARCHAR(15) NULL,
    [WipAct] NVARCHAR(15) NULL,
    [Balance] NUMERIC(19,6) NULL,
    [CreateDate] DATETIME NULL,
    [BaseLine] INT NULL,
    [TransValue] NUMERIC(19,6) NULL,
    [PriceDiff] NUMERIC(19,6) NULL,
    [TransSeq] INT NOT NULL,
    [InvntAct] NVARCHAR(15) NULL,
    [RemMethod] NVARCHAR(1) NULL,
    [OpenValue] NUMERIC(19,6) NULL,
    [SubLineNum] INT NULL,
    [AppObjLine] INT NULL,
    [Expenses] NUMERIC(19,6) NULL,
    [OpenExp] NUMERIC(19,6) NULL,
    [Allocation] NUMERIC(19,6) NULL,
    [OpenAlloc] NUMERIC(19,6) NULL,
    [ExpAlloc] NUMERIC(19,6) NULL,
    [OExpAlloc] NUMERIC(19,6) NULL,
    [OpenPDiff] NUMERIC(19,6) NULL,
    [ExchDiff] NUMERIC(19,6) NULL,
    [OpenEDiff] NUMERIC(19,6) NULL,
    [NegInvAdjs] NUMERIC(19,6) NULL,
    [OpenNegInv] NUMERIC(19,6) NULL,
    [NegStckAct] NVARCHAR(15) NULL,
    [BTransVal] INT NOT NULL,
    [VarVal] NUMERIC(19,6) NULL,
    [BExpVal] NUMERIC(19,6) NULL,
    [CogsVal] NUMERIC(19,6) NULL,
    [BNegAVal] NUMERIC(19,6) NULL,
    [IOffIncAcc] NVARCHAR(15) NULL,
    [IOffIncVal] NUMERIC(19,6) NULL,
    [DOffDecAcc] NVARCHAR(15) NULL,
    [DOffDecVal] NUMERIC(19,6) NULL,
    [DecAcc] NVARCHAR(15) NULL,
    [DecVal] NUMERIC(19,6) NULL,
    [WipVal] NUMERIC(19,6) NULL,
    [WipVarAcc] NVARCHAR(15) NULL,
    [WipVarVal] NUMERIC(19,6) NULL,
    [IncAct] NVARCHAR(15) NULL,
    [IncVal] NUMERIC(19,6) NULL,
    [ExpCAcc] NVARCHAR(15) NULL,
    [CostMethod] CHAR(1) NULL,
    [OcrCode] NVARCHAR(8) NULL,
    [BaseQty] INT NOT NULL,
    [PrevTrans] INT NOT NULL,
    [HTransSeq] INT NOT NULL,
    [OcrCode2] NVARCHAR(8) NULL,
    [OcrCode3] NVARCHAR(8) NULL,
    [OcrCode4] NVARCHAR(8) NULL,
    [OcrCode5] NVARCHAR(8) NULL,
    [StgSeqNum] INT NULL,
    [StgEntry] INT NULL,
    [StgDesc] NVARCHAR(100) NULL
);
