CREATE TABLE [cus].[POR1] (
    [DocEntry] INT NOT NULL,
    [LineNum] INT NOT NULL,
    [TargetType] INT NULL,
    [TrgetEntry] INT NULL,
    [BaseRef] NVARCHAR(16) NULL,
    [BaseType] INT NULL,
    [BaseEntry] INT NULL,
    [BaseLine] INT NULL,
    [LineStatus] CHAR(1) NULL,
    [ItemCode] NVARCHAR(50) NULL,
    [Dscription] NVARCHAR(200) NULL,
    [Quantity] NUMERIC(19,6) NULL,
    [ShipDate] DATETIME NULL,
    [OpenQty] NUMERIC(19,6) NULL,
    [Price] NUMERIC(19,6) NULL,
    [Currency] NVARCHAR(3) NULL,
    [Rate] NUMERIC(19,6) NULL,
    [DiscPrcnt] NUMERIC(19,6) NULL,
    [LineTotal] NUMERIC(19,6) NULL,
    [TotalFrgn] NUMERIC(19,6) NULL,
    [OpenSum] NUMERIC(19,6) NULL,
    [OpenSumFC] NUMERIC(19,6) NULL,
    [VendorNum] NVARCHAR(50) NULL,
    [SerialNum] NVARCHAR(17) NULL,
    [WhsCode] NVARCHAR(8) NULL,
    [SlpCode] INT NULL,
    [Commission] NUMERIC(19,6) NULL,
    [TreeType] CHAR(1) NULL,
    [AcctCode] NVARCHAR(15) NULL,
    [TaxStatus] CHAR(1) NULL,
    [GrossBuyPr] NUMERIC(19,6) NULL,
    [PriceBefDi] NUMERIC(19,6) NULL,
    [DocDate] DATETIME NULL,
    [Flags] INT NULL,
    [OpenCreQty] NUMERIC(19,6) NULL,
    [InvQty] NUMERIC(19,6) NULL,
    [OpenInvQty] NUMERIC(19,6) NULL,
    CONSTRAINT [PK_erp_cus_POR1] PRIMARY KEY (DocEntry,LineNum)
);
