CREATE TABLE [fo_cus].[PurchaseOrderHeaders] (
    [PURCHASEORDERNUMBER] NVARCHAR(155) NULL,
    [DEFAULTRECEIVINGWAREHOUSEID] NVARCHAR(155) NULL,
    [ORDERVENDORACCOUNTNUMBER] NVARCHAR(155) NULL,
    [REQUESTEDDELIVERYDATE] NVARCHAR(155) NULL
);
