CREATE TABLE [cus].[BOM] (
    [BOMID] NVARCHAR(MAX) NULL,
    [ITEMID] NVARCHAR(MAX) NULL,
    [BOMQTY] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL
);
