CREATE TABLE [cus].[BOMVERSION] (
    [TODATE] NVARCHAR(MAX) NULL,
    [FROMDATE] NVARCHAR(MAX) NULL,
    [ITEMID] NVARCHAR(MAX) NULL,
    [BOMID] NVARCHAR(MAX) NULL,
    [NAME] NVARCHAR(MAX) NULL,
    [ACTIVE] NVARCHAR(MAX) NULL,
    [MODIFIEDDATETIME] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL
);
