CREATE TABLE [cus].[CUSTVENDEXTERNALITEM] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [MODULETYPE] NVARCHAR(MAX) NULL,
    [CUSTVENDRELATION] NVARCHAR(MAX) NULL,
    [INVENTDIMID] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [EXTERNALITEMID] NVARCHAR(MAX) NULL
);
