CREATE TABLE [cus].[INVENTBUYERGROUP] (
    [DESCRIPTION] NVARCHAR(MAX) NULL,
    [GROUP_] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
