CREATE TABLE [cus].[INVENTSUM] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [PHYSICALINVENT] NVARCHAR(MAX) NULL,
    [INVENTDIMID] NVARCHAR(MAX) NULL,
    [CLOSED] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
