CREATE TABLE [cus].[INVENTITEMGROUP] (
    [ITEMGROUPID] NVARCHAR(MAX) NULL,
    [NAME] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
