CREATE TABLE [cus].[INVENTITEMGROUPITEM] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [ITEMDATAAREAID] NVARCHAR(MAX) NULL,
    [ITEMGROUPID] NVARCHAR(MAX) NULL,
    [ITEMGROUPDATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
