CREATE TABLE [cus].[INVENTTRANSFERLINE] (
    [TRANSFERID] NVARCHAR(MAX) NULL,
    [ITEMID] NVARCHAR(MAX) NULL,
    [QTYREMAINRECEIVE] NVARCHAR(MAX) NULL,
    [RECEIVEDATE] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
