CREATE TABLE [cus].[INVENTLOCATION] (
    [INVENTLOCATIONID] NVARCHAR(MAX) NULL,
    [NAME] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [dataareaid] NVARCHAR(MAX) NULL,
    [INVENTLOCATIONTYPE] NVARCHAR(MAX) NULL
);
