CREATE TABLE [cus].[INVENTTABLEMODULE] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [MODULETYPE] NVARCHAR(MAX) NULL,
    [UNITID] NVARCHAR(MAX) NULL,
    [PRICE] NVARCHAR(MAX) NULL,
    [PRICEUNIT] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
