CREATE TABLE [cus].[INVENTTRANS] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [STATUSISSUE] NVARCHAR(MAX) NULL,
    [DATEPHYSICAL] NVARCHAR(MAX) NULL,
    [QTY] NVARCHAR(MAX) NULL,
    [DATEEXPECTED] NVARCHAR(MAX) NULL,
    [INVENTDIMID] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [inventTransOrigin] NVARCHAR(MAX) NULL,
    [INVOICEID] NVARCHAR(MAX) NULL,
    [PROJID] NVARCHAR(MAX) NULL,
    [MODIFIEDDATETIME] DATETIME NULL
);
