CREATE TABLE [cus].[INVENTDIM] (
    [INVENTDIMID] NVARCHAR(MAX) NULL,
    [INVENTLOCATIONID] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
