CREATE TABLE [cus].[INVENTTABLE] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [NAMEALIAS] NVARCHAR(MAX) NULL,
    [PRIMARYVENDORID] NVARCHAR(MAX) NULL,
    [ITEMBUYERGROUPID] NVARCHAR(MAX) NULL,
    [NETWEIGHT] NVARCHAR(MAX) NULL,
    [UNITVOLUME] NVARCHAR(MAX) NULL,
    [PRODUCT] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL
);
