CREATE TABLE [cus].[INVENTITEMPURCHSETUP] (
    [ITEMID] NVARCHAR(MAX) NULL,
    [MULTIPLEQTY] NVARCHAR(MAX) NULL,
    [INVENTDIMID] NVARCHAR(MAX) NULL,
    [LEADTIME] NVARCHAR(MAX) NULL,
    [CALENDARDAYS] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [STOPPED] NVARCHAR(MAX) NULL,
    [OVERRIDE] NVARCHAR(MAX) NULL
);
