CREATE TABLE [cus].[INVENTTRANSFERTABLE] (
    [TRANSFERID] NVARCHAR(MAX) NULL,
    [INVENTLOCATIONIDFROM] NVARCHAR(MAX) NULL,
    [INVENTLOCATIONIDTO] NVARCHAR(MAX) NULL,
    [TRANSFERSTATUS] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
