CREATE TABLE [cus].[MCSENUMS] (
    [ENUMITEMLABEL] NVARCHAR(MAX) NULL,
    [ENUMITEMNAME] NVARCHAR(MAX) NULL,
    [ENUMITEMVALUE] NVARCHAR(MAX) NULL,
    [ENUMNAME] NVARCHAR(MAX) NULL,
    [LANGUAGEID] NVARCHAR(MAX) NULL,
    [RECVERSION] NVARCHAR(MAX) NULL,
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL
);
