CREATE TABLE [cus].[PRICEDISCTABLE] (
    [ITEMCODE] NVARCHAR(MAX) NULL,
    [ACCOUNTCODE] NVARCHAR(MAX) NULL,
    [ITEMRELATION] NVARCHAR(MAX) NULL,
    [ACCOUNTRELATION] NVARCHAR(MAX) NULL,
    [DELIVERYTIME] NVARCHAR(MAX) NULL
);
