CREATE TABLE [cus].[VENDTABLE] (
    [PARTITION] NVARCHAR(MAX) NULL,
    [RECID] NVARCHAR(MAX) NULL,
    [ACCOUNTNUM] NVARCHAR(MAX) NULL,
    [BLOCKED] NVARCHAR(MAX) NULL,
    [ItemBuyerGroupId] NVARCHAR(MAX) NULL,
    [DATAAREAID] NVARCHAR(MAX) NULL,
    [PARTY] NVARCHAR(MAX) NULL
);
