CREATE TABLE [nav_cus].[Item_TEST_DFS] (
    [No_] NVARCHAR(20) NOT NULL,
    [Vendor No_] NVARCHAR(20) NOT NULL,
    [Vendor Item No_] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(255) NOT NULL,
    [Description 2] NVARCHAR(1000) NULL,
    [Type] NVARCHAR(MAX) NULL,
    [Product Group Code] NVARCHAR(10) NOT NULL,
    [Item Category Code] NVARCHAR(20) NOT NULL,
    [Blocked] NVARCHAR(MAX) NOT NULL,
    [Gross Weight] NVARCHAR(MAX) NOT NULL,
    [Unit Volume] NVARCHAR(MAX) NOT NULL,
    [Unit Cost] NVARCHAR(MAX) NOT NULL,
    [Order Multiple] DECIMAL(38,20) NOT NULL,
    [Maximum Inventory] NVARCHAR(MAX) NOT NULL,
    [Unit Price] NVARCHAR(MAX) NOT NULL,
    [Base Unit of Measure] NVARCHAR(10) NOT NULL,
    [Minimum Order Quantity] NVARCHAR(MAX) NOT NULL,
    [Price Includes VAT] NVARCHAR(MAX) NOT NULL,
    [Production BOM No_] NVARCHAR(20) NOT NULL,
    [Last Direct Cost] NVARCHAR(MAX) NOT NULL,
    [Lead Time Calculation] VARCHAR(32) NOT NULL,
    [Replenishment System] INT NULL,
    [Purch_ Unit of Measure] NVARCHAR(10) NOT NULL,
    [Reordering Policy] INT NOT NULL,
    [Safety Stock Quantity] DECIMAL(38,20) NOT NULL,
    [Reorder Point] NVARCHAR(MAX) NOT NULL,
    CONSTRAINT [PK_nav_Item_TEST_DFS] PRIMARY KEY (No_)
);
