CREATE TABLE [cus].[BLANKET_PURCHASE_ORDER] (
    [PURCHASE_ORDER_NO] VARCHAR(128) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DELIVERY_DATE] DATE NOT NULL,
    [QUANTITY] DECIMAL(18,4) NULL,
    CONSTRAINT [pk_adi_blanket_purchase_order] PRIMARY KEY (DELIVERY_DATE,ITEM_NO,LOCATION_NO,PURCHASE_ORDER_NO)
);
