CREATE TABLE [cus].[BOM_CONSUMPTION_HISTORY] (
    [TRANSACTION_ID] BIGINT NOT NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [DATE] NVARCHAR(255) NULL,
    [UNIT_QTY] NVARCHAR(255) NULL
);
