CREATE TABLE [cus].[COMMITTED_BOM_DEMAND] (
    [BOM_ORDER_NO] NVARCHAR(128) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [QUANTITY] DECIMAL(18,4) NOT NULL,
    [DEMAND_DATE] DATE NOT NULL,
    CONSTRAINT [pk_adi_committed_bom_demand] PRIMARY KEY (BOM_ORDER_NO,DEMAND_DATE,ITEM_NO,LOCATION_NO)
);
