CREATE TABLE [cus].[OPEN_SALES_ORDER] (
    [SALES_ORDER_NO] NVARCHAR(255) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [DELIVERY_DATE] NVARCHAR(255) NULL,
    [QUANTITY] NVARCHAR(255) NULL,
    [CUSTOMER_NO] NVARCHAR(255) NULL
);
