CREATE TABLE [cus].[PROMOTION] (
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [PERIOD_START] DATE NOT NULL,
    [PERIOD_END] DATE NOT NULL,
    CONSTRAINT [pk_adi_promotion] PRIMARY KEY (ITEM_NO,LOCATION_NO,PERIOD_END,PERIOD_START)
);
