CREATE TABLE [cus].[PURCHASE_ORDER_ROUTE] (
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [VENDOR_NO] NVARCHAR(255) NULL,
    [PRIMARY] NVARCHAR(255) NULL,
    [LEAD_TIME_DAYS] NVARCHAR(255) NULL,
    [ORDER_FREQUENCY_DAYS] NVARCHAR(255) NULL,
    [MIN_ORDER_QTY] NVARCHAR(255) NULL,
    [COST_PRICE] NVARCHAR(255) NULL,
    [PURCHASE_PRICE] NVARCHAR(255) NULL,
    [ORDER_MULTIPLE] NVARCHAR(255) NULL,
    [QTY_PALLET] NVARCHAR(255) NULL,
    [Date] NVARCHAR(255) NULL
);
