CREATE TABLE [cus].[PURCHASE_ORDER_RECEIVED_HISTORY] (
    [PURCHASE_ORDER_NO] VARCHAR(128) NOT NULL,
    [AGR_ORDER_ID] VARCHAR(128) NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [VENDOR_NO] NVARCHAR(255) NOT NULL,
    [ORDER_DATE] DATE NOT NULL,
    [DELIVERY_DATE] DATE NOT NULL,
    [ORDERED_QTY] DECIMAL(18,4) NOT NULL,
    [DELIVERED_QTY] DECIMAL(18,4) NOT NULL,
    CONSTRAINT [pk_adi_purchase_order_received_history] PRIMARY KEY (ITEM_NO,LOCATION_NO,PURCHASE_ORDER_NO,VENDOR_NO)
);
