CREATE TABLE [cus].[SALES_HISTORY] (
    [TRANSACTION_ID] BIGINT NOT NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [DATE] NVARCHAR(255) NULL,
    [SALE] NVARCHAR(255) NULL,
    [CUSTOMER_NO] NVARCHAR(255) NULL,
    [REFERENCE_NO] NVARCHAR(255) NULL
);
