CREATE TABLE [cus].[STOCK_HISTORY] (
    [TRANSACTION_ID] BIGINT NOT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DATE] NVARCHAR(255) NOT NULL,
    [STOCK_MOVE] NVARCHAR(255) NOT NULL
);
