CREATE TABLE [cus].[TRANSFER_HISTORY] (
    [TRANSACTION_ID] NVARCHAR(255) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [FROM_LOCATION_NO] NVARCHAR(255) NULL,
    [TO_LOCATION_NO] NVARCHAR(255) NULL,
    [DATE] NVARCHAR(255) NOT NULL,
    [TRANSFER] NVARCHAR(255) NOT NULL
);
