CREATE TABLE [cus].[UNDELIVERED_BOM_ORDER] (
    [BOM_ORDER_NO] NVARCHAR(128) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DELIVERY_DATE] DATE NOT NULL,
    [QUANTITY] DECIMAL(18,4) NULL,
    CONSTRAINT [pk_adi_undelivered_bom_order] PRIMARY KEY (BOM_ORDER_NO,DELIVERY_DATE,ITEM_NO,LOCATION_NO)
);
