CREATE TABLE [cus].[UNDELIVERED_TRANSFER_ORDER] (
    [TRANSFER_ORDER_NO] NVARCHAR(255) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [ORDER_FROM_LOCATION_NO] NVARCHAR(255) NULL,
    [DELIVERY_DATE] NVARCHAR(255) NULL,
    [QUANTITY] NVARCHAR(255) NULL
);
