CREATE TABLE [cus].[UNDELIVERED_PURCHASE_ORDER] (
    [PURCHASE_ORDER_NO] NVARCHAR(255) NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [DELIVERY_DATE] NVARCHAR(255) NULL,
    [QUANTITY] NVARCHAR(255) NULL
);
