CREATE TABLE [cos_cus].[AGR_SALES_HISTORY_JOSE_BKP] (
    [TRANSACTION_ID] NVARCHAR(255) NOT NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [DATE] DATE NULL,
    [SALE] DECIMAL(18,4) NULL,
    [CUSTOMER_NO] NVARCHAR(255) NULL,
    [REFERENCE_NO] NVARCHAR(255) NULL,
    [IS_SALES_ORDER] BIT NULL,
    [IS_EXCLUDED] BIT NOT NULL
);
