CREATE TABLE [cus].[IV00103] (
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [VENDORID] VARCHAR(20) NOT NULL,
    [ITMVNDTY] INT NULL,
    [VNDITNUM] VARCHAR(50) NULL,
    [MINORQTY] DECIMAL(18,4) NULL,
    [LRCPTCST] DECIMAL(18,4) NULL,
    [AVRGLDTM] INT NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_IV00103] PRIMARY KEY (Company,ITEMNMBR,VENDORID)
);
