CREATE TABLE [cus].[IV00101] (
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [ITMSHNAM] VARCHAR(20) NULL,
    [ITEMDESC] VARCHAR(255) NULL,
    [LOCNCODE] VARCHAR(20) NULL,
    [INACTIVE] INT NULL,
    [CURRCOST] DECIMAL(18,4) NULL,
    [UOMSCHDL] VARCHAR(20) NULL,
    [ITEMSHWT] INT NULL,
    [PRCHSUOM] VARCHAR(20) NULL,
    [USCATVLS_5] VARCHAR(20) NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_IV00101] PRIMARY KEY (Company,ITEMNMBR)
);
