CREATE TABLE [cus].[IV00102] (
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [LOCNCODE] VARCHAR(50) NOT NULL,
    [PRIMVNDR] VARCHAR(50) NOT NULL,
    [PRCHSNGLDTM] DECIMAL(18,4) NULL,
    [BUYERID] VARCHAR(20) NULL,
    [ORDRPNTQTY] DECIMAL(18,4) NULL,
    [ORDRUPTOLVL] DECIMAL(18,4) NULL,
    [REPLENISHMENTMETHOD] INT NULL,
    [ORDERMULTIPLE] DECIMAL(18,4) NULL,
    [MNFCTRNGFXDLDTM] DECIMAL(18,4) NULL,
    [MNFCTRNGVRBLLDTM] DECIMAL(18,4) NULL,
    [ORDERPOLICY] INT NULL,
    [QTYONHND] DECIMAL(18,4) NULL,
    [MNMMORDRQTY] DECIMAL(18,4) NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_IV00102] PRIMARY KEY (Company,ITEMNMBR,LOCNCODE,PRIMVNDR)
);
