CREATE TABLE [cus].[IV30300] (
    [DEX_ROW_ID] BIGINT NOT NULL,
    [TRXSORCE] VARCHAR(20) NOT NULL,
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [TRXLOCTN] VARCHAR(20) NULL,
    [TRNSTLOC] VARCHAR(20) NULL,
    [DOCDATE] DATETIME NULL,
    [TRFQTYTY] INT NULL,
    [Company] VARCHAR(15) NULL
);
