CREATE TABLE [cus].[IV30701] (
    [DEX_ROW_ID] BIGINT NOT NULL,
    [STCKCNTID] VARCHAR(20) NOT NULL,
    [SEQNUMBR] INT NOT NULL,
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [LOCNCODE] VARCHAR(20) NULL,
    [CPTRDT] DATETIME NULL,
    [CAPTUREDQTY] DECIMAL(18,4) NULL,
    [COUNTEDQTY] DECIMAL(18,4) NULL,
    [Company] VARCHAR(15) NULL
);
