CREATE TABLE [cus].[IV40700] (
    [LOCNCODE] VARCHAR(20) NOT NULL,
    [LOCNDSCR] VARCHAR(50) NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_IV40700] PRIMARY KEY (Company,LOCNCODE)
);
