CREATE TABLE [cus].[MOP1110] (
    [MOPRCTNM] VARCHAR(50) NOT NULL,
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [DEX_ROW_ID] BIGINT NOT NULL,
    [BACKFLUSHSITEID] VARCHAR(50) NULL,
    [QTYTOCONSUME] DECIMAL(18,4) NULL,
    [Company] VARCHAR(15) NULL
);
