CREATE TABLE [cus].[PM00200] (
    [VENDORID] VARCHAR(20) NOT NULL,
    [VENDNAME] VARCHAR(100) NULL,
    [HOLD] INT NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_PM00200] PRIMARY KEY (Company,VENDORID)
);
