CREATE TABLE [cus].[POP10110] (
    [PONUMBER] VARCHAR(20) NOT NULL,
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [VENDORID] VARCHAR(20) NULL,
    [LOCNCODE] VARCHAR(20) NULL,
    [PRMDATE] DATETIME NULL,
    [QTYORDER] DECIMAL(18,4) NULL,
    [Company] VARCHAR(15) NULL,
    [POLNESTA] INT NULL,
    [QTYUNCMTBASE] DECIMAL(18,4) NULL
);
