CREATE TABLE [cus].[SOP10100] (
    [SOPTYPE] INT NOT NULL,
    [SOPNUMBE] VARCHAR(30) NOT NULL,
    [ORIGTYPE] INT NULL,
    [ORIGNUMB] VARCHAR(30) NULL,
    [DOCID] VARCHAR(20) NULL,
    [DOCDATE] DATETIME NULL,
    [LOCNCODE] VARCHAR(20) NULL,
    [CUSTNMBR] VARCHAR(20) NULL,
    [REQSHIPDATE] DATETIME NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_SOP10100] PRIMARY KEY (Company,SOPNUMBE,SOPTYPE)
);
