CREATE TABLE [cus].[SOP10200] (
    [SOPTYPE] INT NOT NULL,
    [SOPNUMBE] VARCHAR(30) NOT NULL,
    [ITEMNMBR] VARCHAR(50) NOT NULL,
    [LOCNCODE] VARCHAR(20) NULL,
    [REQSHIPDATE] DATETIME NULL,
    [QTYFULFI] DECIMAL(18,4) NULL,
    [QUANTITY] DECIMAL(18,4) NULL,
    [FUFILDAT] DATETIME NULL,
    [Company] VARCHAR(15) NULL
);
