CREATE TABLE [cus].[SOP30300] (
    [DEX_ROW_ID] BIGINT NOT NULL,
    [SOPTYPE] INT NOT NULL,
    [SOPNUMBE] VARCHAR(30) NOT NULL,
    [ITEMNMBR] VARCHAR(50) NULL,
    [LOCNCODE] VARCHAR(20) NULL,
    [ACTLSHIP] DATETIME NULL,
    [ReqShipDate] DATETIME NULL,
    [QTYFULFI] DECIMAL(18,4) NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_SOP30300] PRIMARY KEY (Company,DEX_ROW_ID)
);
