CREATE TABLE [cus].[SOP30200] (
    [SOPTYPE] INT NOT NULL,
    [SOPNUMBE] VARCHAR(30) NOT NULL,
    [DOCID] VARCHAR(20) NULL,
    [DOCDATE] DATETIME NULL,
    [CUSTNMBR] VARCHAR(20) NULL,
    [VOIDSTTS] INT NULL,
    [Company] VARCHAR(15) NOT NULL,
    CONSTRAINT [PK_cus_SOP30200] PRIMARY KEY (Company,SOPNUMBE,SOPTYPE)
);
