CREATE TABLE [cus].[SALES_HISTORY_LEGACY_20250606] (
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DATE] DATE NOT NULL,
    [CUSTOMER_NO] NVARCHAR(255) NOT NULL,
    [REFERENCE_NO] NVARCHAR(255) NOT NULL,
    [SALE] DECIMAL(18,4) NOT NULL,
    CONSTRAINT [PK_cus_SALES_HISTORY_LEGACY_20250606] PRIMARY KEY (CUSTOMER_NO,DATE,ITEM_NO,LOCATION_NO,REFERENCE_NO)
);
