CREATE PROCEDURE [ax_cus].[populate_item_location]
AS
BEGIN
    SET NOCOUNT ON;
    
    TRUNCATE TABLE [ax_cus].[ITEM_LOCATION];

    INSERT INTO [ax_cus].[ITEM_LOCATION] (ITEM_NO, LOCATION_NO, SAFETY_STOCK_UNITS, MIN_DISPLAY_STOCK, MAX_STOCK, CLOSED_FOR_ORDERING, RESPONSIBLE, NAME, DESCRIPTION, PRIMARY_VENDOR_NO, PURCHASE_LEAD_TIME_DAYS, TRANSFER_LEAD_TIME_DAYS, ORDER_FREQUENCY_DAYS, ORDER_COVERAGE_DAYS, MIN_ORDER_QTY, ORIGINAL_NO, SALE_PRICE, COST_PRICE, PURCHASE_PRICE, ORDER_MULTIPLE, QTY_PALLET, VOLUME, WEIGHT, REORDER_POINT, INCLUDE_IN_AGR, CLOSED, SPECIAL_ORDER, COMPANY)
    SELECT ITEM_NO,
           LOCATION_NO,
           SAFETY_STOCK_UNITS,
           MIN_DISPLAY_STOCK,
           MAX_STOCK,
           CLOSED_FOR_ORDERING,
           RESPONSIBLE,
           NAME,
           DESCRIPTION,
           PRIMARY_VENDOR_NO,
           PURCHASE_LEAD_TIME_DAYS,
           TRANSFER_LEAD_TIME_DAYS,
           ORDER_FREQUENCY_DAYS,
           ORDER_COVERAGE_DAYS,
           MIN_ORDER_QTY,
           ORIGINAL_NO,
           SALE_PRICE,
           COST_PRICE,
           PURCHASE_PRICE,
           ORDER_MULTIPLE,
           QTY_PALLET,
           VOLUME,
           WEIGHT,
           REORDER_POINT,
           INCLUDE_IN_AGR,
           CLOSED,
           SPECIAL_ORDER,
           COMPANY
    FROM ax_cus.[v_T_ITEM_LOCATION];

    DELETE T
    FROM
        (
            SELECT *, DupRank = ROW_NUMBER() OVER (
                PARTITION BY PARTITION, DATAAREAID, REFERENCECATEGORY, RECID
                ORDER BY PARTITION
                )
            FROM ax.INVENTTRANSORIGIN
        ) AS T
    WHERE DupRank > 1;

    SELECT 1
END;
