CREATE TABLE [nav_cus].[nav_columns] (
    [table_name] NVARCHAR(MAX) NULL,
    [object_id] NVARCHAR(MAX) NULL,
    [name] NVARCHAR(MAX) NULL,
    [column_id] NVARCHAR(MAX) NULL,
    [system_type_id] NVARCHAR(MAX) NULL,
    [user_type_id] NVARCHAR(MAX) NULL,
    [max_length] NVARCHAR(MAX) NULL,
    [precision] NVARCHAR(MAX) NULL,
    [scale] NVARCHAR(MAX) NULL,
    [collation_name] NVARCHAR(MAX) NULL,
    [is_nullable] NVARCHAR(MAX) NULL,
    [is_ansi_padded] NVARCHAR(MAX) NULL,
    [is_rowguidcol] NVARCHAR(MAX) NULL,
    [is_identity] NVARCHAR(MAX) NULL,
    [is_computed] NVARCHAR(MAX) NULL,
    [is_filestream] NVARCHAR(MAX) NULL,
    [is_replicated] NVARCHAR(MAX) NULL,
    [is_non_sql_subscribed] NVARCHAR(MAX) NULL,
    [is_merge_published] NVARCHAR(MAX) NULL,
    [is_dts_replicated] NVARCHAR(MAX) NULL,
    [is_xml_document] NVARCHAR(MAX) NULL,
    [xml_collection_id] NVARCHAR(MAX) NULL,
    [default_object_id] NVARCHAR(MAX) NULL,
    [rule_object_id] NVARCHAR(MAX) NULL,
    [is_sparse] NVARCHAR(MAX) NULL,
    [is_column_set] NVARCHAR(MAX) NULL
);
