CREATE TABLE [cus].[ReservationEntry] (
    [Entry No_] INT NOT NULL,
    [Positive] INT NOT NULL,
    [Item No_] NVARCHAR(20) NOT NULL,
    [Location Code] NVARCHAR(10) NULL,
    [Quantity] DECIMAL(38,20) NULL,
    [Qty_ to Invoice (Base)] DECIMAL(38,20) NULL,
    [Quantity Invoiced (Base)] DECIMAL(38,20) NULL,
    [Quantity (Base)] DECIMAL(38,20) NULL,
    [Reservation Status] NVARCHAR(20) NULL,
    [Source Type] INT NULL,
    [Creation Date] DATETIME NULL,
    [Expected Receipt Date] DATETIME NULL,
    [Shipment Date] DATETIME NULL,
    [Qty_ per Unit of Measure] DECIMAL(38,20) NULL,
    [Company] NVARCHAR(3) NOT NULL,
    [Source Subtype] NVARCHAR(50) NULL,
    [Transferred from Entry No_] NVARCHAR(50) NULL,
    [Source ID] NVARCHAR(50) NULL,
    [Source Ref_ No_] NVARCHAR(50) NULL,
    [Appl_-to Item Entry] NVARCHAR(50) NULL,
    [Appl_-from Item Entry] NVARCHAR(50) NULL,
    [Correction] NVARCHAR(50) NULL,
    [Item Tracking] NVARCHAR(50) NULL,
    CONSTRAINT [PK_cus_ReservationEntry] PRIMARY KEY (Company,Entry No_,Positive)
);
