CREATE TABLE [cus].[ProductDetails] (
    [ID] BIGINT NOT NULL,
    [Code] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(100) NULL,
    [Category.Code] NVARCHAR(50) NULL,
    [Category.Description] NVARCHAR(100) NULL,
    [Purchasing.DefaultSupplier.Code] NVARCHAR(50) NULL,
    [ReplenishmentSetup.LeadTimeQuantity] DECIMAL(18,4) NULL,
    [SellingPrice1] DECIMAL(18,4) NULL,
    [Purchasing.SellingBaseCost] DECIMAL(18,4) NULL,
    [P_BranchInfo_STS.Costings.AverageCost] DECIMAL(18,4) NULL,
    [PalletQuantity] DECIMAL(18,4) NULL,
    [Purchasing.SupplierProductCode] NVARCHAR(50) NULL,
    [$StockBinStatistics] NVARCHAR(MAX) NULL,
    [Buyer.Name] NVARCHAR(50) NOT NULL,
    [Buyer.Code] NVARCHAR(50) NOT NULL,
    [Costings.D_CMACCost] DECIMAL(18,4) NULL,
    [Department.Code] NVARCHAR(100) NULL,
    [Department.Description] NVARCHAR(100) NULL,
    [P_BranchInfo_STS.D_MinimumOrderQuantity] DECIMAL(18,4) NULL,
    [Purchasing.PackSize] DECIMAL(18,4) NULL,
    [P_BranchInfo_STS.MinimumStockLevel] DECIMAL(18,4) NULL,
    [P_BranchInfo_STS.MaximumStockLevel] DECIMAL(18,4) NULL,
    [CALC_AGRClosed] BIT NULL,
    [WorkflowStatus.Code] NVARCHAR(50) NULL,
    [WorkflowStatus.Description] NVARCHAR(50) NULL
);
