CREATE TABLE [cus].[AGR_STOCK_HISTORY] (
    [TRANSACTION_ID] NVARCHAR(MAX) NULL,
    [ITEM_NO] NVARCHAR(MAX) NULL,
    [LOCATION_NO] NVARCHAR(MAX) NULL,
    [DATE] NVARCHAR(MAX) NULL,
    [STOCK_MOVE] NVARCHAR(MAX) NULL,
    [STOCK_LEVEL] NVARCHAR(MAX) NULL
);
