CREATE TABLE [cus].[AGR_UNDELIVERED_TRANSFER_ORDERS] (
    [TRANSFER_ORDER_NO] NVARCHAR(MAX) NULL,
    [ITEM_NO] NVARCHAR(MAX) NULL,
    [LOCATION_NO] NVARCHAR(MAX) NULL,
    [ORDER_FROM_LOCATION_NO] NVARCHAR(MAX) NULL,
    [DELIVERY_DATE] NVARCHAR(MAX) NULL,
    [QUANTITY] NVARCHAR(MAX) NULL
);
