CREATE TABLE [cus].[AGR_SALES_ORDERS] (
    [NO] NVARCHAR(MAX) NULL,
    [LOCATION_NO] NVARCHAR(MAX) NULL,
    [CUSTOMER_NO] NVARCHAR(MAX) NULL,
    [DELIVERY_DATE] NVARCHAR(MAX) NULL,
    [DELIVERY_STATUS] NVARCHAR(MAX) NULL
);
