CREATE TABLE [cus].[AGR_PURCHASE_ORDER_ROUTE] (
    [ITEM_NO] NVARCHAR(MAX) NULL,
    [LOCATION_NO] NVARCHAR(MAX) NULL,
    [VENDOR_NO] NVARCHAR(MAX) NULL,
    [PRIMARY] NVARCHAR(MAX) NULL,
    [LEAD_TIME_DAYS] NVARCHAR(MAX) NULL,
    [ORDER_FREQUENCY_DAYS] NVARCHAR(MAX) NULL,
    [MIN_ORDER_QTY] NVARCHAR(MAX) NULL,
    [COST_PRICE] NVARCHAR(MAX) NULL,
    [PURCHASE_PRICE] NVARCHAR(MAX) NULL,
    [ORDER_MULTIPLE] NVARCHAR(MAX) NULL,
    [QTY_PALLET] NVARCHAR(MAX) NULL
);
