CREATE TABLE [cus].[AGR_SALES_HISTORY] (
    [TRANSACTION_ID] NVARCHAR(MAX) NULL,
    [ITEM_NO] NVARCHAR(MAX) NULL,
    [LOCATION_NO] NVARCHAR(MAX) NULL,
    [DATE] NVARCHAR(MAX) NULL,
    [SALE_QTY] NVARCHAR(MAX) NULL,
    [CUSTOMER_NO] NVARCHAR(MAX) NULL,
    [REFERENCE_NO] NVARCHAR(MAX) NULL,
    [IS_SALES_ORDER] NVARCHAR(MAX) NULL,
    [IS_EXCLUDED] NVARCHAR(MAX) NULL
);
