CREATE TABLE [cus].[AGR_SALES_ORDERS_LINE] (
    [SALES_ORDER_NO] NVARCHAR(MAX) NULL,
    [PRODUCT_ITEM_NO] NVARCHAR(MAX) NULL,
    [LOCATION_NO] NVARCHAR(MAX) NULL,
    [QUANTITY] NVARCHAR(MAX) NULL,
    [EXPIRE_DATE] NVARCHAR(MAX) NULL,
    [DELIVERY_DATE] NVARCHAR(MAX) NULL,
    [DELIVERY_STATUS] NVARCHAR(MAX) NULL
);
