CREATE TABLE [ax_cus].[ECORESPRODUCT] (
    [PRODUCTMASTER] BIGINT NULL,
    [RETAITOTALWEIGHT] INT NULL,
    [VARIANTCONFIGURATIONTECHNOLOGY] INT NULL,
    [RETAILCOLORGROUPID] NVARCHAR(10) NULL,
    [RETAILSIZEGROUPID] NVARCHAR(10) NULL,
    [RETAILSTYLEGROUPID] NVARCHAR(10) NULL,
    [INSTANCERELATIONTYPE] BIGINT NOT NULL,
    [DISPLAYPRODUCTNUMBER] NVARCHAR(70) NOT NULL,
    [SEARCHNAME] NVARCHAR(20) NOT NULL,
    [PRODUCTTYPE] INT NOT NULL,
    [PDSCWPRODUCT] INT NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RELATIONTYPE] BIGINT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_ECORESPRODUCT] PRIMARY KEY (RECID)
);
