CREATE TABLE [ax_cus].[INVENTLOCATION] (
    [INVENTLOCATIONID] NVARCHAR(10) NOT NULL,
    [NAME] NVARCHAR(60) NOT NULL,
    [MANUAL] INT NOT NULL,
    [INVENTLOCATIONIDREQMAIN] NVARCHAR(10) NOT NULL,
    [REQREFILL] INT NOT NULL,
    [INVENTLOCATIONTYPE] INT NOT NULL,
    [INVENTSITEID] NVARCHAR(10) NOT NULL,
    [RETAILWEIGHTEX1] NUMERIC(32,16) NOT NULL,
    [FSHSTORE] INT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_INVENTLOCATION] PRIMARY KEY (DATAAREAID,INVENTLOCATIONID,PARTITION)
);
