CREATE TABLE [ax_cus].[SALESTABLE] (
    [SALESID] NVARCHAR(20) NOT NULL,
    [SALESNAME] NVARCHAR(60) NOT NULL,
    [CUSTACCOUNT] NVARCHAR(20) NOT NULL,
    [DELIVERYDATE] DATETIME NOT NULL,
    [SALESSTATUS] INT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_SALESTABLE] PRIMARY KEY (DATAAREAID,PARTITION,SALESID)
);
