CREATE TABLE [ax_cus].[UNITOFMEASURECONVERSION] (
    [FROMUNITOFMEASURE] BIGINT NOT NULL,
    [TOUNITOFMEASURE] BIGINT NOT NULL,
    [PRODUCT] BIGINT NOT NULL,
    [FACTOR] NUMERIC(32,16) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_UNITOFMEASURECONVERSION] PRIMARY KEY (RECID)
);
