CREATE TABLE [cos_cus].[AGR_ITEM_CUSTOM] (
    [NO] NVARCHAR(255) NOT NULL,
    [BRAND_NAME] NVARCHAR(255) NULL,
    [EAN] NVARCHAR(255) NULL,
    [DATE_AVAILABLE] DATETIME NULL,
    [IS_BACKORDER] NVARCHAR(20) NULL
);
