CREATE VIEW [cus].v_ITEM
             AS
            SELECT
               CAST(No AS nvarchar(255)) AS [NO],
               CAST(Name AS nvarchar(255)) AS [NAME],
               CAST(description AS nvarchar(1000)) AS [DESCRIPTION],
               CAST(primary_vendor_no AS nvarchar(255)) AS [PRIMARY_VENDOR_NO],
               CAST(lead_time_days AS smallint) AS [PURCHASE_LEAD_TIME_DAYS],
               CAST(NULL AS smallint) AS [TRANSFER_LEAD_TIME_DAYS],
               CAST(order_frequency_days AS smallint) AS [ORDER_FREQUENCY_DAYS],
               CAST(order_coverage_days AS smallint) AS [ORDER_COVERAGE_DAYS],
               CAST(min_order_qty AS decimal(18,4)) AS [MIN_ORDER_QTY],
               CAST(original_no AS nvarchar(50)) AS [ORIGINAL_NO],
               CAST(closed AS bit) AS [CLOSED],
               CAST(closed_for_ordering AS bit) AS [CLOSED_FOR_ORDERING],
               CAST(responsible AS nvarchar(255)) AS [RESPONSIBLE],
               CAST(sale_price AS decimal(18,4)) AS [SALE_PRICE],
               CAST(cost_price AS decimal(18,4)) AS [COST_PRICE],
               CAST(purchase_price AS decimal(18,4)) AS [PURCHASE_PRICE],
               CAST(order_multiple AS decimal(18,4)) AS [ORDER_MULTIPLE],
               CAST(qty_pallet AS decimal(18,4)) AS [QTY_PALLET],
               CAST(volume AS decimal(18,4)) AS [VOLUME],
               CAST(weight AS decimal(18,4)) AS [WEIGHT],
               CAST(min_stock AS decimal(18,4)) AS [SAFETY_STOCK_UNITS],
               CAST(NULL AS decimal(18,4)) AS [MIN_DISPLAY_STOCK],
               CAST(max_stock AS decimal(18,4)) AS [MAX_STOCK],
               CAST(product_group_no_level_1 AS nvarchar(255)) AS [ITEM_GROUP_NO_LVL_1],
               CAST(product_group_no_level_2 AS nvarchar(255)) AS [ITEM_GROUP_NO_LVL_2],
               CAST(NULL AS nvarchar(255)) AS [ITEM_GROUP_NO_LVL_3],
               CAST(base_unit_of_measure AS nvarchar(50)) AS [BASE_UNIT_OF_MEASURE],
               CAST(purchase_unit_of_measure AS nvarchar(50)) AS [PURCHASE_UNIT_OF_MEASURE],
               CAST(qty_per_purchase_unit AS decimal(18,4)) AS [QTY_PER_PURCHASE_UNIT],
               CAST(reorder_point AS decimal(18,4)) AS [REORDER_POINT],
               CAST(special_order AS bit) AS [SPECIAL_ORDER],
               CAST(1 AS bit) AS [INCLUDE_IN_AGR]
            FROM cus.product_info
