CREATE TABLE [cus].[SQL_Interprise_Columns] (
    [TABLE_CATALOG] NVARCHAR(50) NULL,
    [TABLE_SCHEMA] NVARCHAR(50) NULL,
    [TABLE_NAME] NVARCHAR(50) NULL,
    [COLUMN_NAME] NVARCHAR(50) NULL,
    [ORDINAL_POSITION] INT NULL,
    [COLUMN_DEFAULT] NVARCHAR(50) NULL,
    [IS_NULLABLE] NVARCHAR(50) NULL,
    [DATA_TYPE] NVARCHAR(50) NULL,
    [CHARACTER_MAXIMUM_LENGTH] INT NULL,
    [NUMERIC_PRECISION] INT NULL,
    [NUMERIC_SCALE] INT NULL,
    [DATETIME_PRECISION] INT NULL,
    [IsPrimaryKey] NVARCHAR(50) NULL,
    [IsForeignKey] NVARCHAR(50) NULL
);
