CREATE TABLE [ax_cus].[INVENTBATCH] (
    [INVENTBATCHID] NVARCHAR(20) NOT NULL,
    [EXPDATE] DATETIME NOT NULL,
    [ITEMID] NVARCHAR(20) NOT NULL,
    [PRODDATE] DATETIME NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_INVENTBATCH] PRIMARY KEY (DATAAREAID,INVENTBATCHID,ITEMID,PARTITION)
);
