CREATE TABLE [ax_cus].[PRICEDISCTABLE] (
    [ACCOUNTCODE] INT NOT NULL,
    [ITEMRELATION] NVARCHAR(20) NOT NULL,
    [FROMDATE] DATETIME NOT NULL,
    [TODATE] DATETIME NOT NULL,
    [AMOUNT] NUMERIC(32,16) NOT NULL,
    [RELATION] INT NOT NULL,
    [MODULE] INT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_PRICEDISCTABLE] PRIMARY KEY (RECID)
);
