CREATE TABLE [ax_cus].[PurchTable] (
    [PURCHID] NVARCHAR(20) NOT NULL,
    [PURCHNAME] NVARCHAR(60) NOT NULL,
    [INVENTLOCATIONID] NVARCHAR(10) NOT NULL,
    [ORDERACCOUNT] NVARCHAR(20) NOT NULL,
    [INVOICEACCOUNT] NVARCHAR(20) NOT NULL,
    [DELIVERYDATE] DATETIME NOT NULL,
    [PAYMENT] NVARCHAR(10) NOT NULL,
    [VENDGROUP] NVARCHAR(10) NOT NULL,
    [PURCHSTATUS] INT NOT NULL,
    [STATPROCID] NVARCHAR(10) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_PurchTable] PRIMARY KEY (DATAAREAID,PARTITION,PURCHID)
);
