CREATE TABLE [ax_cus].[VENDTABLE] (
    [ACCOUNTNUM] NVARCHAR(20) NOT NULL,
    [VENDGROUP] NVARCHAR(10) NOT NULL,
    [CURRENCY] NVARCHAR(3) NOT NULL,
    [BLOCKED] INT NOT NULL,
    [ONETIMEVENDOR] INT NOT NULL,
    [INVENTLOCATION] NVARCHAR(10) NOT NULL,
    [ITEMBUYERGROUPID] NVARCHAR(10) NOT NULL,
    [PURCHPOOLID] NVARCHAR(10) NOT NULL,
    [PARTY] BIGINT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [AGRORDERFREQUENCY] INT NOT NULL,
    [AGRDeliveryTime] INT NULL,
    CONSTRAINT [PK_ax_cus_VENDTABLE] PRIMARY KEY (ACCOUNTNUM,DATAAREAID,PARTITION)
);
