





-- ===============================================================================
-- Author:      José Sucena
-- Description: Item Data mapping from CUS
--
--  23.09.2024.HMH   Created
-- ===============================================================================

CREATE VIEW [cus].[v_ITEM] AS

WITH FilteredItems AS (
    SELECT  * 
    FROM [cus].INVENTTABLE it
    WHERE it.dataareaid = 'rar'
      AND it.ITEMID NOT LIKE '6%'
      AND it.ITEMID NOT LIKE '7%'
      AND it.ITEMID NOT LIKE 'Þ%'
      AND it.ITEMID NOT LIKE 'TR%'
      AND it.ITEMID NOT LIKE 'Hlutd%'
      AND it.ITEMID NOT LIKE 'N%'
      AND it.ITEMID NOT LIKE 'S%'
      AND it.ITEMID NOT LIKE '4%'
      AND it.ITEMID NOT LIKE '5%'
      AND it.ITEMID NOT LIKE '8%'
      AND it.ITEMID NOT LIKE '9%'
      AND it.ITEMID NOT IN ('1','1000','102','V100')
      AND it.ITEMID NOT LIKE '99%'
)

	   SELECT DISTINCT
        CAST(fi.ITEMID AS NVARCHAR(255)) AS [NO],
        CAST(COALESCE(TRIM(erpt.Name), TRIM(fi.NAMEALIAS)) AS NVARCHAR(255)) AS [NAME],
        CAST(NULL AS NVARCHAR(1000)) AS [DESCRIPTION],
		CASE 
			WHEN NOT EXISTS (SELECT 1 FROM [cus].VENDTABLE v WHERE v.ACCOUNTNUM = fi.PRIMARYVENDORID) THEN CAST('vendor_missing' AS NVARCHAR(255))
			ELSE IIF(fi.PRIMARYVENDORID='', CAST('vendor_missing' AS NVARCHAR(255)),CAST( fi.PRIMARYVENDORID AS NVARCHAR(255))) 
		END AS [PRIMARY_VENDOR_NO],
        CAST(ISNULL(ips.LEADTIME,0) AS SMALLINT) AS [PURCHASE_LEAD_TIME_DAYS],
        CAST(NULL AS SMALLINT) AS [TRANSFER_LEAD_TIME_DAYS],
        CAST(NULL AS SMALLINT ) AS [ORDER_FREQUENCY_DAYS],
        CAST(NULL AS SMALLINT ) AS [ORDER_COVERAGE_DAYS],
        CAST(NULL AS DECIMAL(18,4)) AS [MIN_ORDER_QTY],
        CAST(ISNULL(cv.EXTERNALITEMID, '') AS NVARCHAR(50)) AS [ORIGINAL_NO],
        CAST(0 AS BIT) AS [CLOSED_FOR_ORDERING],
        CAST(fi.ITEMBUYERGROUPID AS NVARCHAR(255)) AS [RESPONSIBLE],
        CAST(itm.Price AS DECIMAL(18,4)) AS [SALE_PRICE],
        CAST(itm.PRICE AS DECIMAL(18,4)) / (CASE WHEN CAST(itm.PRICEUNIT AS DECIMAL(18,4)) = 0 THEN 1 ELSE CAST(itm.PRICEUNIT AS DECIMAL(18,4)) END) AS [COST_PRICE],
        CAST(itm2.PRICE AS DECIMAL(18,4)) / (CASE WHEN CAST(itm2.PRICEUNIT AS DECIMAL(18,4)) = 0 THEN 1 ELSE CAST(itm2.PRICEUNIT AS DECIMAL(18,4)) END) AS [PURCHASE_PRICE],
        CASE WHEN ISNULL(CAST(ips.MULTIPLEQTY AS DECIMAL(18,4)),0) < 1 THEN 1 ELSE ISNULL(CAST(ips.MULTIPLEQTY AS DECIMAL(18,4)),0) END AS [ORDER_MULTIPLE],
        CAST(NULL AS DECIMAL(18,4)) AS [QTY_PALLET],
        CAST(fi.UNITVOLUME AS DECIMAL(18,6)) AS [VOLUME],
        CAST(fi.NETWEIGHT AS DECIMAL(18,6)) AS [WEIGHT],

        CAST(0 AS DECIMAL(18,4)) AS [SAFETY_STOCK_UNITS],
        CAST(NULL AS DECIMAL(18,4)) AS [MIN_DISPLAY_STOCK],

        CAST(NULL AS DECIMAL(18,4)) AS [MAX_STOCK],
        CAST((LEFT(fi.ITEMID,1)) AS NVARCHAR(255)) AS [ITEM_GROUP_NO_LVL_1],
        CAST(NULL AS NVARCHAR(255)) AS [ITEM_GROUP_NO_LVL_2],
        CAST(NULL AS NVARCHAR(255)) AS [ITEM_GROUP_NO_LVL_3],
        CAST(NULL AS NVARCHAR(50)) AS [BASE_UNIT_OF_MEASURE],
        CAST(NULL AS NVARCHAR(50)) AS [PURCHASE_UNIT_OF_MEASURE],
        CAST(NULL AS DECIMAL(18,4)) AS [QTY_PER_PURCHASE_UNIT],
        CAST(0 AS BIT) AS [SPECIAL_ORDER],
        CAST(0 AS DECIMAL(18,4)) AS [REORDER_POINT],
		CAST(1 AS BIT) AS [INCLUDE_IN_AGR],
		CAST(ips.stopped AS BIT) AS [CLOSED]
    FROM FilteredItems fi
JOIN [cus].EcoResProduct erp ON fi.PRODUCT = erp.recid AND fi.PARTITION = erp.PARTITION
LEFT JOIN [cus].EcoResProductTranslation erpt ON erp.RECID = erpt.PRODUCT AND erp.PARTITION = erpt.PARTITION AND erpt.LANGUAGEID = 'is'
LEFT JOIN [cus].VENDTABLE v ON fi.PRIMARYVENDORID = v.ACCOUNTNUM AND v.DATAAREAID = fi.DATAAREAID
LEFT JOIN [cus].INVENTITEMPURCHSETUP ips ON fi.ITEMID = ips.ITEMID AND ips.DATAAREAID = fi.DATAAREAID
LEFT JOIN [cus].CUSTVENDEXTERNALITEM cv ON fi.ITEMID = cv.ITEMID AND fi.PRIMARYVENDORID = cv.CUSTVENDRELATION AND cv.DATAAREAID = fi.DATAAREAID AND cv.MODULETYPE = 3
LEFT JOIN [cus].INVENTTABLEMODULE itm ON fi.ITEMID = itm.ITEMID AND itm.DATAAREAID = fi.DATAAREAID AND itm.ModuleType = 2 -- Moduletype = ‘Sölupöntun’
LEFT JOIN [cus].INVENTTABLEMODULE itm2 ON fi.ITEMID = itm2.ITEMID AND itm2.DATAAREAID = fi.DATAAREAID AND itm2.ModuleType = 1
LEFT JOIN [cus].INVENTITEMINVENTSETUP iis ON fi.ITEMID = iis.ITEMID AND iis.DATAAREAID = fi.DATAAREAID -- Correct JOIN for [cus].INVENTITEMINVENTSETUP
WHERE ips.INVENTDIMID = 'AllBlank' AND ISNULL(iis.stopped, 0) = 0 


