CREATE TABLE [bc_rest_cus].[SALE_HISTORY_LEGACY_20241209] (
    [PRODUCT_ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DATE] DATE NOT NULL,
    [SALE] NUMERIC(18,4) NOT NULL,
    CONSTRAINT [PK_SALE_HISTORY_LEGACY_20241209] PRIMARY KEY (DATE,LOCATION_NO,PRODUCT_ITEM_NO)
);
