CREATE TABLE [bc_rest_cus].[SALE_HISTORY_LEGACY_20241213] (
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DATE] DATE NOT NULL,
    [SALE] DECIMAL(18,4) NOT NULL
);
