CREATE TABLE [cus].[Inventory] (
    [sku] NVARCHAR(50) NULL,
    [warehouseCode] NVARCHAR(50) NULL,
    [inventory] NVARCHAR(50) NULL,
    [reservedInventory] NVARCHAR(50) NULL,
    [atp_date] NVARCHAR(100) NULL,
    [atp_quantity] DECIMAL(18,4) NULL,
    [atp_reservedQuantity] DECIMAL(18,4) NULL,
    [atp_availableQuantity] DECIMAL(18,4) NULL,
    [atp_purchaseOrderId] NVARCHAR(100) NULL,
    [atp_deliveryId] NVARCHAR(100) NULL,
    [atp_purchaseOrderLineId] NVARCHAR(100) NULL,
    [calculatedInventory] NVARCHAR(50) NULL,
    [maxQuantity] NVARCHAR(50) NULL,
    [minQuantity] NVARCHAR(50) NULL,
    [created] NVARCHAR(50) NULL,
    [modified] NVARCHAR(50) NULL,
    [reorderMinQuantity] NVARCHAR(50) NULL,
    [cost] NVARCHAR(50) NULL,
    [costTotal] NVARCHAR(50) NULL,
    [costCurrency] NVARCHAR(10) NULL
);
