CREATE TABLE [cus].[OrdersLines] (
    [id] NVARCHAR(50) NULL,
    [orderNumber] NVARCHAR(50) NULL,
    [customerId] NVARCHAR(50) NULL,
    [customerNumber] NVARCHAR(50) NULL,
    [customerName] NVARCHAR(255) NULL,
    [marketId] NVARCHAR(50) NULL,
    [orderForm_shipments_shipmentId] NVARCHAR(50) NULL,
    [orderForm_shipments_status] NVARCHAR(50) NULL,
    [orderForm_shipments_orderStatus] NVARCHAR(50) NULL,
    [orderForm_shipments_warehouseCode] NVARCHAR(50) NULL,
    [orderForm_lineItems_lineItemId] NVARCHAR(100) NULL,
    [orderForm_lineItems_code] NVARCHAR(50) NULL,
    [orderForm_lineItems_displayName] NVARCHAR(255) NULL,
    [orderForm_lineItems_quantity] DECIMAL(18,2) NULL,
    [orderForm_lineItems_unit] NVARCHAR(20) NULL,
    [orderForm_lineItems_placedPrice] DECIMAL(18,2) NULL,
    [orderForm_lineItems_extendedPrice] DECIMAL(18,2) NULL,
    [orderForm_lineItems_cost] DECIMAL(18,2) NULL,
    [orderForm_lineItems_supplierId] NVARCHAR(50) NULL,
    [orderForm_lineItems_supplierName] NVARCHAR(255) NULL,
    [orderForm_lineItems_productId] NVARCHAR(50) NULL,
    [status] NVARCHAR(50) NULL,
    [remainingPayment] DECIMAL(18,2) NULL,
    [modified] DATETIME2 NULL,
    [created] DATETIME2 NULL,
    [requestedDeliveryDate] DATETIME2 NULL
);
