CREATE TABLE [cus].[Products] (
    [isSku] BIT NOT NULL,
    [customsCode] NVARCHAR(50) NULL,
    [id] NVARCHAR(50) NOT NULL,
    [skuId] NVARCHAR(50) NULL,
    [productId] NVARCHAR(50) NOT NULL,
    [name] NVARCHAR(255) NULL,
    [startDate] DATETIME2 NOT NULL,
    [endDate] DATETIME2 NOT NULL,
    [created] DATETIME2 NOT NULL,
    [modified] DATETIME2 NOT NULL,
    [published] DATETIME2 NOT NULL,
    [isActive] BIT NOT NULL,
    [categories_categoryId] NVARCHAR(50) NULL,
    [categories_name] NVARCHAR(255) NULL,
    [categories_description] NVARCHAR(255) NULL,
    [categories_parentId] NVARCHAR(50) NULL,
    [categories_isMainCategory] NVARCHAR(50) NULL,
    [isBundle] BIT NOT NULL,
    [isKit] BIT NOT NULL,
    [isPackage] BIT NOT NULL,
    [isWriteProtected] BIT NOT NULL,
    [isInStock] BIT NOT NULL,
    [minQuantity] DECIMAL(18,4) NULL,
    [availableInventory] DECIMAL(18,4) NULL,
    [maxQuantity] DECIMAL(18,4) NULL,
    [weight] DECIMAL(18,4) NULL,
    [price_marketId] NVARCHAR(50) NULL,
    [price_storeId] NVARCHAR(50) NULL,
    [price_code] NVARCHAR(50) NULL,
    [price_validFrom] DATETIME2 NULL,
    [price_minQuantity] DECIMAL(18,4) NULL,
    [price_unitPrice] DECIMAL(18,4) NULL,
    [price_currencyCode] NVARCHAR(50) NULL,
    [price_originalUnitPrice] DECIMAL(18,4) NULL,
    [price_recommendedRetailPrice] DECIMAL(18,4) NULL,
    [price_skuId] NVARCHAR(50) NULL,
    [price_isTaxExcluded] BIT NULL,
    [price_taxRate] DECIMAL(18,4) NULL,
    [price_cost] DECIMAL(18,4) NULL,
    [price_isBackorder] BIT NULL,
    [price_isCustomerClubSpecificPrice] BIT NULL,
    [storeIds] NVARCHAR(50) NULL,
    [size] NVARCHAR(50) NULL,
    [supplierName] NVARCHAR(255) NULL,
    [supplierId] NVARCHAR(50) NULL,
    [supplierSkuId] NVARCHAR(50) NULL,
    [supplierPackagingQuantity] DECIMAL(18,4) NULL,
    [cost] DECIMAL(18,4) NULL,
    [costCurrency] NVARCHAR(50) NULL,
    [isVirtual] BIT NULL
);
