CREATE VIEW [fo_cus].[v_stock_level]
AS

    SELECT
        CAST(sl.ITEMNUMBER + CASE WHEN sl.[PRODUCTCONFIGURATIONID] IS NULL OR sl.[PRODUCTCONFIGURATIONID] = '' THEN '' ELSE '-' + ISNULL(sl.PRODUCTCONFIGURATIONID, '') END AS NVARCHAR(255)) AS ITEM_NO,
        CAST(ISNULL(sl.INVENTORYWAREHOUSEID, '') AS NVARCHAR(255)) AS LOCATION_NO,
        CAST('21000101' AS DATE) AS EXPIRE_DATE,
        SUM(CAST(sl.ONHANDQUANTITY AS DECIMAL(18,4))) AS STOCK_UNITS
    FROM
        fo.StockLevel sl
	GROUP BY sl.ITEMNUMBER, sl.INVENTORYWAREHOUSEID, sl.TOTALAVAILABLEQUANTITY, sl.PRODUCTCONFIGURATIONID

