CREATE VIEW [fo_cus].[v_UNDELIVERED_TRANSFER_ORDER]
AS

    SELECT
        CAST(tol.TRANSFERORDERNUMBER AS NVARCHAR(128)) AS [transfer_order_no],
	    CAST(tol.ITEMNUMBER + CASE WHEN tol.[PRODUCTCONFIGURATIONID] IS NULL OR tol.[PRODUCTCONFIGURATIONID] = '' THEN '' ELSE '-' + ISNULL(tol.PRODUCTCONFIGURATIONID, '') END AS NVARCHAR(255)) AS ITEM_NO,
        CAST(toh.SHIPPINGWAREHOUSEID AS NVARCHAR(255)) AS [order_from_location_no], 
        CAST(toh.RECEIVINGWAREHOUSEID AS NVARCHAR(255)) AS [location_no],
		CAST(tol.REQUESTEDRECEIPTDATE AS DATE) AS [delivery_date],
        SUM(CAST(tol.TRANSFERQUANTITY AS DECIMAL(18,4))) AS [quantity]

    FROM fo.[TransferOrderLines] tol
	LEFT JOIN fo_cus.TransferOrderHeader toh ON tol.TRANSFERORDERNUMBER = toh.TRANSFERORDERNUMBER
	WHERE CAST(tol.REQUESTEDRECEIPTDATE AS DATE) >= GETDATE() AND toh.TransferOrderStatus IN ('Created', 'Shipped')
	GROUP BY CAST(tol.TRANSFERORDERNUMBER AS NVARCHAR(128)),
             CAST(tol.ITEMNUMBER + CASE
             WHEN tol.[PRODUCTCONFIGURATIONID] IS NULL
             OR tol.[PRODUCTCONFIGURATIONID] = '' THEN
             ''
             ELSE
             '-' + ISNULL(tol.PRODUCTCONFIGURATIONID, '')
             END AS NVARCHAR(255)),
             CAST(toh.SHIPPINGWAREHOUSEID AS NVARCHAR(255)),
             CAST(toh.RECEIVINGWAREHOUSEID AS NVARCHAR(255)),
             CAST(tol.REQUESTEDRECEIPTDATE AS DATE)

