CREATE TABLE [cus].[ICITEM] (
    [ITEMNO] NVARCHAR(24) NOT NULL,
    [DESC] NVARCHAR(60) NOT NULL,
    [INACTIVE] SMALLINT NOT NULL,
    [SVALUES] INT NULL,
    [VALUES] INT NULL,
    [LVALUES] INT NULL,
    [WEIGHTUNIT] NVARCHAR(10) NULL,
    [UNITWGT] DECIMAL(20,4) NULL,
    [STOCKUNIT] NVARCHAR(10) NULL
);
