CREATE TABLE [cus].[OEINVD] (
    [INVUNIQ] DECIMAL(19,0) NOT NULL,
    [ORDNUMBER] NVARCHAR(22) NOT NULL,
    [ITEM] NVARCHAR(24) NULL,
    [LOCATION] NVARCHAR(6) NULL,
    [QTYSHIPPED] DECIMAL(19,4) NULL
);
