CREATE TABLE [cus].[OEINVH] (
    [INVUNIQ] DECIMAL(19,0) NOT NULL,
    [INVNUMBER] NVARCHAR(22) NOT NULL,
    [ORDNUMBER] NVARCHAR(22) NOT NULL,
    [LOCATION] NVARCHAR(6) NOT NULL,
    [INVDATE] DECIMAL(10,0) NULL,
    [CUSTOMER] NVARCHAR(12) NULL,
    [REFERENCE] NVARCHAR(60) NULL
);
