CREATE TABLE [cus].[OEORDH] (
    [ORDUNIQ] DECIMAL(19,0) NOT NULL,
    [ORDNUMBER] NVARCHAR(22) NOT NULL,
    [CUSTOMER] NVARCHAR(12) NOT NULL,
    [SHIPDATE] DECIMAL(18,9) NULL,
    [EXPDATE] DECIMAL(18,9) NULL,
    [TYPE] SMALLINT NULL,
    [ONHOLD] SMALLINT NULL,
    [COMPLETE] SMALLINT NULL
);
