CREATE TABLE [ax_cus].[ECORESCATEGORY] (
    [CATEGORYHIERARCHY] BIGINT NOT NULL,
    [PARENTCATEGORY] BIGINT NOT NULL,
    [NAME] NVARCHAR(254) NOT NULL,
    [ISACTIVE] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL
);
