CREATE TABLE [ax_cus].[INVENTTABLE] (
    [ITEMID] NVARCHAR(20) NULL,
    [NAMEALIAS] NVARCHAR(20) NULL,
    [PRIMARYVENDORID] NVARCHAR(20) NULL,
    [ITEMBUYERGROUPID] NVARCHAR(15) NULL,
    [NETWEIGHT] DECIMAL(32,10) NULL,
    [UNITVOLUME] DECIMAL(32,10) NULL,
    [PRODUCT] BIGINT NULL,
    [AGRORDERFREQUENCY] INT NOT NULL,
    [AGRBLOCKED] INT NOT NULL,
    [AGRRESPONSIBLE] NVARCHAR(20) NOT NULL,
    [REQGROUPID] NVARCHAR(10) NOT NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL,
    [DATAAREAID] NVARCHAR(4) NULL
);
