CREATE TABLE [ax_cus].[INVENTMODELGROUPITEM] (
    [ITEMDATAAREAID] NVARCHAR(4) NOT NULL,
    [MODELGROUPID] NVARCHAR(10) NOT NULL,
    [ITEMID] NVARCHAR(20) NOT NULL,
    [MODELGROUPDATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_erp_cus_INVENTMODELGROUPITEM] PRIMARY KEY (RECID)
);
