CREATE TABLE [ax_cus].[inventtrans_first] (
    [ITEMID] NVARCHAR(20) NULL,
    [STATUSISSUE] INT NULL,
    [DATEPHYSICAL] DATETIME NULL,
    [QTY] DECIMAL(32,10) NULL,
    [DATEEXPECTED] DATETIME NULL,
    [INVENTDIMID] NVARCHAR(20) NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL,
    [INVENTTRANSORIGIN] BIGINT NULL,
    [INVOICEID] NVARCHAR(20) NULL,
    [PROJID] NVARCHAR(20) NULL,
    [MODIFIEDDATETIME] DATETIME NULL
);
