CREATE TABLE [ax_cus].[PRODUCT_PURCHASE_INFO_UNIT_CONVERSION] (
    [NO] NVARCHAR(255) NOT NULL,
    [PRODUCT_NO] NVARCHAR(255) NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [purch_unit] NVARCHAR(10) NULL,
    [invent_unit] NVARCHAR(10) NULL,
    [FACTOR] NUMERIC(32,16) NULL,
    [FACTOR2] NUMERIC(32,16) NULL,
    [ORDER_MULTIPLE] NUMERIC(32,16) NULL,
    [purch_CESECONDARYUNITID] NVARCHAR(10) NULL,
    [condition] INT NOT NULL,
    CONSTRAINT [PK_raw_cus_PRODUCT_PURCHASE_INFO_UNIT_CONVERSION] PRIMARY KEY (NO)
);
