CREATE TABLE [ax_cus].[PURCHLINE] (
    [PURCHID] NVARCHAR(20) NULL,
    [ITEMID] NVARCHAR(20) NULL,
    [PURCHSTATUS] INT NULL,
    [DELIVERYDATE] DATETIME NULL,
    [REMAINPURCHPHYSICAL] DECIMAL(32,10) NULL,
    [CONFIRMEDDLV] DATETIME NULL,
    [INVENTDIMID] NVARCHAR(20) NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL,
    [QTYORDERED] NUMERIC(32,16) NOT NULL
);
