CREATE TABLE [ax_cus].[ReqItemTable] (
    [ITEMID] NVARCHAR(20) NULL,
    [MININVENTONHAND] DECIMAL(32,10) NULL,
    [REQPOTYPEACTIVE] INT NOT NULL,
    [REQGROUPID] NVARCHAR(10) NULL,
    [REQPOTYPE] INT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [RECID] BIGINT NULL,
    [PARTITION] BIGINT NOT NULL,
    [COVINVENTDIMID] NVARCHAR(20) NULL,
    [INVENTLOCATIONIDREQMAIN] NVARCHAR(15) NULL,
    [MAXINVENTONHAND] DECIMAL(18,4) NULL,
    [LEADTIMEPURCHASE] INT NOT NULL
);
