CREATE TABLE [ax_cus].[RETAILGROUPMEMBERLINE] (
    [CATEGORY] BIGINT NOT NULL,
    [PRODUCT] BIGINT NOT NULL,
    [VARIANT] BIGINT NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_erp_cus_RETAILGROUPMEMBERLINE] PRIMARY KEY (RECID)
);
