CREATE TABLE [ax_cus].[RETAILASSORTMENTPRODUCTLINE] (
    [ASSORTMENTRECID] BIGINT NOT NULL,
    [LINETYPE] INT NOT NULL,
    [RETAILGROUPMEMBERLINEID] BIGINT NOT NULL,
    [STATUS] INT NOT NULL,
    [MODIFIEDDATETIME] DATETIME NOT NULL,
    [CREATEDDATETIME] DATETIME NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_ax_cus_RETAILASSORTMENTPRODUCTLINE] PRIMARY KEY (RECID)
);
