CREATE TABLE [ax_cus].[RETAILASSORTMENTLOOKUP] (
    [ASSORTMENTID] BIGINT NOT NULL,
    [LINETYPE] INT NOT NULL,
    [PRODUCTID] BIGINT NOT NULL,
    [VALIDFROM] DATETIME NOT NULL,
    [VALIDTO] DATETIME NOT NULL,
    [VARIANTID] BIGINT NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [CREATEDDATETIME] DATETIME NOT NULL,
    CONSTRAINT [PK_ax_cus_RETAILASSORTMENTLOOKUP] PRIMARY KEY (RECID)
);
