CREATE TABLE [ax_cus].[RETAILASSORTMENTTABLE] (
    [ASSORTMENTID] NVARCHAR(10) NOT NULL,
    [NAME] NVARCHAR(60) NOT NULL,
    [PUBLISHEDDATETIME] DATETIME NOT NULL,
    [PUBLISHEDDATETIMETZID] INT NOT NULL,
    [STATUS] INT NOT NULL,
    [VALIDFROM] DATETIME NOT NULL,
    [VALIDTO] DATETIME NOT NULL,
    [MODIFIEDDATETIME] DATETIME NOT NULL,
    [CREATEDDATETIME] DATETIME NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_erp_cus_RETAILASSORTMENTTABLE] PRIMARY KEY (RECID)
);
