CREATE TABLE [ax_cus].[UNITOFMEASURECONVERSION] (
    [FROMUNITOFMEASURE] BIGINT NOT NULL,
    [TOUNITOFMEASURE] BIGINT NOT NULL,
    [PRODUCT] BIGINT NOT NULL,
    [FACTOR] NUMERIC(32,16) NOT NULL,
    [NUMERATOR] INT NOT NULL,
    [DENOMINATOR] INT NOT NULL,
    [INNEROFFSET] NUMERIC(32,16) NOT NULL,
    [OUTEROFFSET] NUMERIC(32,16) NOT NULL,
    [ROUNDING] INT NOT NULL,
    [MODIFIEDDATETIME] DATETIME NOT NULL,
    [RECVERSION] INT NOT NULL,
    [PARTITION] BIGINT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [PK_erp_cus_UNITOFMEASURECONVERSION] PRIMARY KEY (RECID)
);
