CREATE TABLE [ax_cus].[VENDTABLE] (
    [PARTITION] BIGINT NULL,
    [RECID] BIGINT NULL,
    [ACCOUNTNUM] NVARCHAR(20) NULL,
    [BLOCKED] INT NULL,
    [AGRORDERFREQUENCY] INT NOT NULL,
    [AGRRESPONSIBLE] NVARCHAR(20) NOT NULL,
    [AGRDELIVERYTIME] INT NOT NULL,
    [AGRBLOCKED] INT NOT NULL,
    [VENDGROUP] NVARCHAR(10) NOT NULL,
    [ITEMBUYERGROUPID] NVARCHAR(15) NULL,
    [DATAAREAID] NVARCHAR(4) NULL,
    [PARTY] BIGINT NULL
);
