CREATE TABLE [nav_cus].[Item] (
    [No_] NVARCHAR(255) NOT NULL,
    [Vendor No_] NVARCHAR(255) NOT NULL,
    [Vendor Item No_] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(255) NOT NULL,
    [Description 2] NVARCHAR(1000) NULL,
    [Type] NVARCHAR(255) NULL,
    [Product Group Code] NVARCHAR(255) NOT NULL,
    [Item Category Code] NVARCHAR(255) NOT NULL,
    [Blocked] NVARCHAR(255) NOT NULL,
    [Gross Weight] NVARCHAR(255) NOT NULL,
    [Unit Volume] NVARCHAR(255) NOT NULL,
    [Unit Cost] NVARCHAR(255) NOT NULL,
    [Order Multiple] NVARCHAR(255) NOT NULL,
    [Maximum Inventory] NVARCHAR(255) NOT NULL,
    [Unit Price] NVARCHAR(255) NOT NULL,
    [Base Unit of Measure] NVARCHAR(255) NOT NULL,
    [Minimum Order Quantity] NVARCHAR(255) NOT NULL,
    [Price Includes VAT] NVARCHAR(255) NOT NULL,
    [Production BOM No_] NVARCHAR(255) NOT NULL,
    [Last Direct Cost] NVARCHAR(255) NOT NULL,
    [Lead Time Calculation] NVARCHAR(255) NOT NULL,
    [Replenishment System] NVARCHAR(255) NULL,
    [Purch_ Unit of Measure] NVARCHAR(255) NOT NULL,
    [Reordering Policy] NVARCHAR(255) NOT NULL,
    [Safety Stock Quantity] NVARCHAR(255) NULL,
    [Reorder Point] NVARCHAR(255) NULL,
    CONSTRAINT [PK_nav_cus_Item2] PRIMARY KEY (No_)
);
