
CREATE VIEW [cus].[v_BOM_CONSUMPTION_HISTORY] AS
    SELECT
				CAST(ID AS NVARCHAR(255)) AS TRANSACTION_ID,
				CAST([Product.Code] AS NVARCHAR(255)) AS ITEM_NO,
				CAST((SELECT TOP 1 Code FROM cus.Branch) AS NVARCHAR(255)) AS LOCATION_NO,
				CAST([_Owner_.Date] AS DATE)          AS [DATE],
				CAST(-Quantity AS DECIMAL(18,4)) AS [UNIT_QTY]
			FROM cus.BOMConsumption

