
CREATE VIEW [cus].[v_CUSTOMER] AS
	SELECT
        CAST([Code] AS NVARCHAR(255)) AS [NO],
        CAST([Name] AS NVARCHAR(255)) AS [NAME],
		CAST(NULL AS NVARCHAR(255)) AS CUSTOMER_GROUP_NO
    FROM cus.Customer

