CREATE TABLE [bc_rest_cus].[MC_LEGACY_SALES_01072025_DFS] (
    [ITEM_NO] NVARCHAR(MAX) NULL,
    [SALE] INT NULL,
    [REFERENCE_NO] INT NULL,
    [DATE] NVARCHAR(MAX) NULL,
    [CUSTOMER_NO] NVARCHAR(MAX) NULL
);
