CREATE TABLE [fo_cus].[InventTrans] (
    [RECIDTRANS] NVARCHAR(155) NULL,
    [DATEPHYSICAL] NVARCHAR(155) NULL,
    [INVENTDIMID] NVARCHAR(155) NULL,
    [INVENTTRANSID] NVARCHAR(155) NULL,
    [ITEMID] NVARCHAR(155) NULL,
    [QTY] NVARCHAR(155) NULL,
    [REFERENCECATEGORY] NVARCHAR(155) NULL,
    [REFERENCEID] NVARCHAR(155) NULL,
    [STATUSISSUE] NVARCHAR(155) NULL
);
