CREATE TABLE [fo_cus].[Products] (
    [ITEMNUMBER] NVARCHAR(155) NULL,
    [ALTERNATIVEPRODUCTSIZEID] NVARCHAR(155) NULL,
    [PURCHASEPRICE] NVARCHAR(155) NULL,
    [PURCHASEPRICEQUANTITY] NVARCHAR(155) NULL,
    [SALESPRICE] NVARCHAR(155) NULL,
    [PRODUCTGROUPID] NVARCHAR(155) NULL,
    [PRIMARYVENDORACCOUNTNUMBER] NVARCHAR(155) NULL,
    [BUYERGROUPID] NVARCHAR(155) NULL,
    [PURCHASEUNITSYMBOL] NVARCHAR(155) NULL,
    [PRODUCTVOLUME] NVARCHAR(155) NULL,
    [NETPRODUCTWEIGHT] NVARCHAR(155) NULL,
    [PRODUCTLIFECYCLESTATEID] NVARCHAR(155) NULL,
    [UNITCOST] NVARCHAR(155) NULL,
    [UNITCOSTQUANTITY] NVARCHAR(155) NULL,
    [SEARCHNAME] NVARCHAR(155) NULL
);
