CREATE TABLE [fo_cus].[ProductCategories] (
    [PRODUCTCATEGORYHIERARCHYNAME] NVARCHAR(255) NULL,
    [CATEGORYNAME] NVARCHAR(255) NULL,
    [CATEGORYCODE] NVARCHAR(255) NULL,
    [CATEGORYDESCRIPTION] NVARCHAR(1000) NULL,
    [CATEGORYKEYWORDS] NVARCHAR(255) NULL,
    [CATEGORYRECORDID] NVARCHAR(255) NULL,
    [DEFAULTPROJECTGLOBALCATEGORYID] NVARCHAR(255) NULL,
    [EXTERNALID] NVARCHAR(255) NULL,
    [FRIENDLYCATEGORYNAME] NVARCHAR(255) NULL,
    [ISCATEGORYINHERITINGPARENTCATEGORYATTRIBUTES] NVARCHAR(255) NULL,
    [ISCATEGORYINHERITINGPARENTPRODUCTATTRIBUTES] NVARCHAR(255) NULL,
    [ISTANGIBLEPRODUCT] NVARCHAR(255) NULL,
    [PARENTPRODUCTCATEGORYCODE] NVARCHAR(255) NULL,
    [PARENTPRODUCTCATEGORYHIERARCHYNAME] NVARCHAR(255) NULL,
    [PARENTPRODUCTCATEGORYNAME] NVARCHAR(255) NULL,
    [PROJECTCATEGORYNAME] NVARCHAR(255) NULL
);
