CREATE TABLE [fo_cus].[SalesOrderLines] (
    [INVENTORYLOTID] NVARCHAR(155) NULL,
    [CONFIRMEDRECEIPTDATE] NVARCHAR(155) NULL,
    [DELIVERYADDRESSCITY] NVARCHAR(155) NULL,
    [DELIVERYADDRESSNAME] NVARCHAR(155) NULL,
    [ITEMNUMBER] NVARCHAR(155) NULL,
    [ORDEREDSALESQUANTITY] NVARCHAR(155) NULL,
    [SALESORDERLINESTATUS] NVARCHAR(155) NULL,
    [SALESORDERNUMBER] NVARCHAR(155) NULL,
    [SHIPPINGWAREHOUSEID] NVARCHAR(155) NULL,
    [CONFIRMEDSHIPDATE] NVARCHAR(155) NULL
);
