CREATE TABLE [fo_cus].[PurchaseOrderHeaders] (
    [PURCHASEORDERNUMBER] NVARCHAR(255) NULL,
    [AGR] NVARCHAR(255) NULL,
    [CONFIRMEDDELIVERYDATE] NVARCHAR(255) NULL,
    [CONFIRMEDSHIPDATE] NVARCHAR(255) NULL,
    [DEFAULTRECEIVINGSITEID] NVARCHAR(255) NULL,
    [DEFAULTRECEIVINGWAREHOUSEID] NVARCHAR(255) NULL,
    [DELIVERYADDRESSCITY] NVARCHAR(255) NULL,
    [DELIVERYADDRESSDESCRIPTION] NVARCHAR(255) NULL,
    [DELIVERYADDRESSNAME] NVARCHAR(255) NULL,
    [EMAIL] NVARCHAR(255) NULL,
    [INVOICEVENDORACCOUNTNUMBER] NVARCHAR(255) NULL,
    [PURCHASEORDERNAME] NVARCHAR(255) NULL,
    [PURCHASEORDERSTATUS] NVARCHAR(255) NULL,
    [REQUESTEDDELIVERYDATE] NVARCHAR(255) NULL,
    [REQUESTEDSHIPDATE] NVARCHAR(255) NULL
);
