CREATE TABLE [fo_cus].[PurchaseOrderLines] (
    [PURCHASEORDERNUMBER] NVARCHAR(155) NULL,
    [CONFIRMEDDELIVERYDATE] NVARCHAR(155) NULL,
    [ITEMNUMBER] NVARCHAR(155) NULL,
    [ORDEREDPURCHASEQUANTITY] NVARCHAR(155) NULL,
    [RECEIVINGWAREHOUSEID] NVARCHAR(155) NULL,
    [REQUESTEDDELIVERYDATE] NVARCHAR(155) NULL
);
