


CREATE VIEW [fo_cus].[v_BOM_COMPONENT]
AS

SELECT DISTINCT
    CASE 
        WHEN bh.ENGCHGDISPLAYPRODUCTNUMBER LIKE '% :  :  :  : S01 :%' THEN 
            REPLACE(bh.ENGCHGDISPLAYPRODUCTNUMBER, ' :  :  :  : S01 :', '')
        ELSE 
            bh.ENGCHGDISPLAYPRODUCTNUMBER 
    END AS ITEM_NO,
    CAST(bl.ITEMNUMBER AS NVARCHAR(255)) AS COMPONENT_ITEM_NO,
	SUM(CAST(bl.QUANTITY AS DECIMAL(18, 4))) AS QUANTITY
FROM 
    fo.BOMLines bl

LEFT JOIN fo.BOMHeaders bh ON bh.BOMID = bl.BOMID
	WHERE 1 = 0
	GROUP BY bh.ENGCHGDISPLAYPRODUCTNUMBER, bl.ITEMNUMBER


