CREATE VIEW [fo_cus].[v_UNDELIVERED_PURCHASE_ORDER]
AS

WITH ReceivedQty AS (
    SELECT 
        INVENTTRANSID,
        CAST(SUM(CAST(QTY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS total_qty
    FROM fo_cus.InventTrans
    WHERE STATUSRECEIPT = 'Registered'
    GROUP BY INVENTTRANSID
)

SELECT
    CAST(pol.PURCHASEORDERNUMBER AS NVARCHAR(128)) AS [purchase_order_no],
    CAST(pol.ITEMNUMBER AS NVARCHAR(255)) AS [ITEM_NO],
    CAST(pol.RECEIVINGWAREHOUSEID AS NVARCHAR(255)) AS [location_no],
    CAST(
        SUM(CAST(pol.REMAINPURCHPHYSICAL AS DECIMAL(18,4))) - 
        SUM(CAST(ISNULL(rq.total_qty, 0) AS DECIMAL(18,4)))
    AS DECIMAL(18,4)) AS [quantity],
    CASE 
        WHEN pol.CONFIRMEDDELIVERYDATE LIKE '19%' 
        THEN CAST(pol.REQUESTEDDELIVERYDATE AS DATE) 
        ELSE CAST(pol.CONFIRMEDDELIVERYDATE AS DATE)
    END AS [delivery_date]
FROM fo_cus.PurchaseOrderLines pol
LEFT JOIN ReceivedQty rq ON rq.INVENTTRANSID = pol.INVENTORYLOTID
WHERE 
    pol.ITEMNUMBER IS NOT NULL 
    AND pol.RECEIVINGWAREHOUSEID IS NOT NULL 
    AND CAST(pol.REMAINPURCHPHYSICAL AS DECIMAL(18,4)) > 0
GROUP BY 
    pol.PURCHASEORDERNUMBER,
    pol.ITEMNUMBER,
    pol.RECEIVINGWAREHOUSEID,
    CASE 
        WHEN pol.CONFIRMEDDELIVERYDATE LIKE '19%' 
        THEN CAST(pol.REQUESTEDDELIVERYDATE AS DATE) 
        ELSE CAST(pol.CONFIRMEDDELIVERYDATE AS DATE)
    END;


