create VIEW [cus].[v_CC_item_group_no]
AS

	SELECT
		CAST(it.ITEMID AS NVARCHAR(255))			AS [NO],
		CAST(cig.MAJORGROUPID AS NVARCHAR(255))		AS [ITEM_GROUP_NO_LVL_1],
		CAST(it.ITEMGROUPID AS NVARCHAR(255))		AS [ITEM_GROUP_NO_LVL_2]
		FROM cus.INVENTTABLE  it 
			INNER JOIN cus.CEBPLINVENTITEMMAJORGROUP cig ON it.CEBplItemMajorGroupId = cig.MAJORGROUPID AND it.ITEMGROUPID = cig.ITEMGROUPID AND it.DATAAREAID = cig.DATAAREAID



