CREATE VIEW [cus].[v_ITEM_GROUP]
AS

	SELECT
		CAST(iig.ITEMGROUPID AS NVARCHAR(255))              AS [NO],
		CAST(ISNULL(iig.NAME,'') AS NVARCHAR(255))			AS [NAME]
	FROM cus.INVENTITEMGROUP iig 
	INNER JOIN cus.DataAreas da ON iig.dataareaId=da.company_id

	UNION ALL
	SELECT 
		CAST(c.MAJORGROUPID + '-' + c.NAME AS NVARCHAR(255))		AS [NO],
		CAST(ISNULL(c.NAME,'') AS NVARCHAR(255))	AS [NAME]
	FROM cus.CEBPLINVENTITEMMAJORGROUP c 
	INNER JOIN cus.DataAreas da ON c.dataareaId=da.company_id
	INNER JOIN cus.INVENTITEMGROUP ig ON ig.ITEMGROUPID = c.ITEMGROUPID
	GROUP BY c.MAJORGROUPID, c.NAME

