CREATE VIEW [cus].[v_LOCATION]
AS

    SELECT
        CAST(INVENTLOCATIONID AS NVARCHAR(255))     AS [NO],
        CAST(NAME AS NVARCHAR(255))   AS [NAME]
    FROM cus.INVENTLOCATION
	WHERE INVENTLOCATIONID IN ('ADF','F-TOLLUR','AFK')

