
CREATE VIEW cus.v_OPEN_SALES_ORDER 
AS 
	SELECT
		CONCAT(
			CAST(inv.RECID AS NVARCHAR(128)),'-',
			CAST(CAST(it.DATEEXPECTED AS DATE) AS NVARCHAR(255)))
																				AS [SALES_ORDER_NO],
		CAST(it.ITEMID AS NVARCHAR(255)) 										AS [ITEM_NO],
		CAST(inv.INVENTLOCATIONID AS NVARCHAR(255))								AS [LOCATION_NO],
		CAST(ISNULL( SUM(-it.QTY/ NULLIF(uc.Factor, 0)), -9999.) AS BIGINT)		AS [QUANTITY],
		CAST(NULL AS NVARCHAR(255))												AS [CUSTOMER_NO],
		CAST(it.DATEEXPECTED AS DATE)											AS [DELIVERY_DATE]
	FROM [cus].INVENTTRANS it
		INNER JOIN [cus].INVENTDIM inv ON 
		(
		inv.INVENTDIMID = it.INVENTDIMID
		AND inv.DATAAREAID = it.DATAAREAID
		)
		INNER JOIN cus.UnitConvert uc
		ON 
		(
		it.ITEMID = uc.ITEMID
		AND it.DATAAREAID = uc.DATAAREAID
		AND	uc.TOUNIT = 'ks'
		)
	WHERE 
		it.STATUSISSUE IN (2,4,6) AND it.TRANSREFID LIKE 'SP%'
	GROUP BY 
		CONCAT(
			CAST(inv.RECID AS NVARCHAR(128)),'-',
			CAST(CAST(it.DATEEXPECTED AS DATE) AS NVARCHAR(255))),
		it.ITEMID,
		inv.INVENTLOCATIONID,
		CAST(it.DATEEXPECTED AS DATE),
		CAST(it.DATAAREAID AS NVARCHAR(4))

