
CREATE VIEW [cus].[v_PURCHASE_ORDER_RECEIVED_HISTORY] AS

	SELECT  -- THII 2025.02.18 added distinct due to dublicates
        CAST(pl.PURCHID AS NVARCHAR(255))		AS PURCHASE_ORDER_NO,
		CAST(NULL AS VARCHAR(128))				AS [AGR_ORDER_ID],
        CAST(pl.ITEMID AS NVARCHAR(100))		AS [ITEM_NO],
		CAST(pl.DATAAREAID  AS NVARCHAR(255))				AS [LOCATION_NO],
		CAST(pl.VENDACCOUNT AS NVARCHAR(50))	AS [VENDOR_NO], 
		CAST(pl.CREATEDDATETIME  AS DATE)			AS [ORDER_DATE],
		CAST(it.DATEPHYSICAL AS DATE)					AS [DELIVERY_DATE],
		CAST(SUM(pl.QTYORDERED/uc.FACTOR) AS DECIMAL(18,4))		AS [ORDERED_QTY],
		CAST(sum(it.QTY/uc.FACTOR) AS DECIMAL(18,4))		AS [DELIVERED_QTY],
		CAST(NULL AS DECIMAL(18, 4)) AS [PURCHASE_PRICE],
	    CAST(NULL AS INT) AS [LEAD_TIME_CALCULATION_DAYS]
    FROM
        cus.PURCHLINE pl
		INNER JOIN cus.INVENTTRANS it ON pl.INVENTTRANSID = it.INVENTTRANSID
		INNER JOIN cus.UNITCONVERT uc ON uc.ITEMID = pl.ITEMID AND uc.FROMUNIT = pl.PURCHUNIT AND uc.DATAAREAID = pl.DATAAREAID
    WHERE
		CAST(pl.REMAINPURCHPHYSICAL AS DECIMAL(18, 4)) = 0
        AND CAST(pl.CREATEDDATETIME AS DATE) > '2022-01-01'
		AND uc.ToUnit='ks'
		AND uc.FACTOR <> 0.0
	GROUP BY 
		CAST(pl.PURCHID AS NVARCHAR(255)), 
		CAST(pl.ITEMID AS NVARCHAR(100)), 
		CAST(pl.DATAAREAID  AS NVARCHAR(255)), 
		CAST(pl.VENDACCOUNT AS NVARCHAR(50)), 
		CAST(pl.CREATEDDATETIME  AS DATE),
		CAST(it.DATEPHYSICAL AS DATE)

