CREATE VIEW	cus.v_UNDELIVERED_PURCHASE_ORDER
AS
WITH undelivered AS (
	SELECT
		pl.PURCHID							AS [PURCHASE_ORDER_NO],
		i.ITEMID							AS [ITEM_NO],
		id.DATAAREAID					AS [LOCATION_NO],
		pt.DELIVERYDATE						AS [DELIVERY_DATE],
		pl.REMAINPURCHPHYSICAL / uc.FACTOR	AS [QUANTITY]
	FROM cus.PURCHLINE pl 
		INNER JOIN cus.INVENTDIM AS id ON pl.INVENTDIMID = id.INVENTDIMID AND pl.DATAAREAID = id.DATAAREAID
		INNER JOIN cus.UNITCONVERT uc ON uc.ITEMID = pl.ITEMID AND uc.FROMUNIT = pl.PURCHUNIT AND uc.DATAAREAID = pl.DATAAREAID
		INNER JOIN cus.PURCHTABLE pt ON pt.PURCHID = pl.PURCHID AND pt.DATAAREAID = pl.DATAAREAID
		INNER JOIN cus.INVENTTABLE i ON i.ITEMID = pl.ItemID
		INNER JOIN cus.DataAreas da ON da.company_id = pl.DATAAREAID
	WHERE pl.PurchStatus IN (0,1)
		AND uc.ToUnit='ks'
		AND pt.PurchaseType = 3	
		AND pt.Documentstatus IN (2,6,0)
		AND pt.purchstatus = 1
		AND uc.FACTOR <> 0.0
		AND pl.RemainPurchPhysical> 0

	UNION ALL 

	SELECT 
		pl.PURCHID							AS [PURCHASE_ORDER_NO],
		i.ITEMID							AS [ITEM_NO], 
		id.DATAAREAID					AS [LOCATION_NO],
		pt.DELIVERYDATE						AS [DELIVERY_DATE], 
		pl.PURCHQTY / uc.FACTOR				AS [QUANTITY]
	FROM cus.PURCHLINE pl INNER JOIN cus.INVENTDIM AS id ON pl.INVENTDIMID = id.INVENTDIMID AND pl.DATAAREAID=id.DATAAREAID
		INNER JOIN cus.UNITCONVERT uc ON uc.ITEMID =pl.ITEMID AND uc.FROMUNIT = pl.PURCHUNIT AND uc.DATAAREAID=pl.DATAAREAID
		INNER JOIN cus.PURCHTABLE pt ON pt.PURCHID=pl.PURCHID AND pt.DATAAREAID=pl.DATAAREAID
		INNER JOIN cus.INVENTTABLE i ON i.ITEMID=pl.ITEMID
		INNER JOIN cus.DataAreas da ON da.company_id=pl.DATAAREAID
		WHERE  pl.PURCHSTATUS IN (1,2)
		AND uc.TOUNIT='ks'
		AND pt.PURCHASETYPE=3
		AND pt.DOCUMENTSTATUS IN (5)
		AND pt.PURCHSTATUS = 1
		AND uc.FACTOR <> 0.0
		AND pl.PURCHQTY > 0

	UNION ALL

	SELECT 
		CAST(ROW_NUMBER() OVER (ORDER BY i.ITEMID) AS VARCHAR)+ 'TOLLUR'	AS [PURCHASE_ORDER_NO],
		i.ITEMID															AS [ITEM_NO],
		id.DATAAREAID													AS [LOCATION_NO],
		GETDATE()															AS [DELIVERY_DATE],
		SUM(ins.PHYSICALINVENT / uc.FACTOR)									AS [QUANTITY]
	FROM cus.INVENTSUM ins INNER JOIN cus.INVENTDIM id ON ins.DATAAREAID=id.DATAAREAID AND id.INVENTDIMID=ins.INVENTDIMID
		INNER JOIN cus.UNITCONVERT uc ON uc.ITEMID=ins.ITEMID AND uc.DATAAREAID=ins.DATAAREAID
		INNER JOIN cus.INVENTTABLEMODULE itm ON itm.ITEMID=ins.ITEMID AND itm.DATAAREAID=ins.DATAAREAID AND itm.unitid=uc.FROMUNIT
		INNER JOIN cus.INVENTTABLE i ON i.ITEMID=ins.ITEMID
	WHERE itm.MODULETYPE=0 
		AND uc.TOUNIT='ks'
		AND id.INVENTLOCATIONID='TOLLUR'
		AND uc.FACTOR <> 0.0
		AND ins.PhysicalInvent > 0
	GROUP BY i.ITEMID,id.DATAAREAID	

	UNION ALL

	SELECT 
		CAST(ROW_NUMBER() OVER (ORDER BY i.ITEMID) AS VARCHAR)+ 'F-TOLLUR'	AS [PURCHASE_ORDER_NO],
		i.ITEMID															AS [ITEM_NO],
		id.DATAAREAID													AS [LOCATION_NO],
		GETDATE()															AS [DELIVERY_DATE],
		SUM(ins.PHYSICALINVENT / uc.FACTOR)									AS [QUANTITY]
	FROM cus.INVENTSUM ins INNER JOIN cus.INVENTDIM id ON ins.DATAAREAID=id.DATAAREAID AND id.INVENTDIMID=ins.INVENTDIMID
		INNER JOIN cus.UNITCONVERT uc ON uc.ITEMID=ins.ITEMID AND uc.DATAAREAID=ins.DATAAREAID
		INNER JOIN cus.INVENTTABLEMODULE itm ON itm.ITEMID=ins.ITEMID AND itm.DATAAREAID=ins.DATAAREAID AND itm.UNITID=uc.FROMUNIT
		INNER JOIN cus.INVENTTABLE i ON i.ITEMID=ins.ITEMID
		WHERE itm.MODULETYPE=0 
		AND uc.TOUNIT='ks'
		AND id.INVENTLOCATIONID='F-TOLLUR'
		AND uc.FACTOR <> 0.0
		AND ins.PHYSICALINVENT > 0
	GROUP BY i.ITEMID,id.DATAAREAID	

	UNION ALL

	--12.4.2024 Elva added in stock in AFK-MV (Merking) 30.06.2025.BF - AF-25
	SELECT
		CAST(ROW_NUMBER() OVER (ORDER BY i.ITEMID) AS VARCHAR)+ 'AFK-MV'	AS [PURCHASE_ORDER_NO],
		i.ITEMID															AS [ITEM_NO],
		id.DATAAREAID													AS [LOCATION_NO],
		GETDATE()															AS [DELIVERY_DATE],
		SUM(ins.PhysicalInvent / uc.Factor)									AS [QUANTITY]
	FROM cus.INVENTSUM ins INNER JOIN cus.INVENTDIM id ON ins.DATAAREAID=id.DATAAREAID AND id.INVENTDIMID=ins.INVENTDIMID
		INNER JOIN cus.UNITCONVERT uc ON uc.ITEMID=ins.ITEMID AND uc.DATAAREAID=ins.DATAAREAID
		INNER JOIN cus.INVENTTABLEMODULE itm ON itm.ITEMID=ins.ITEMID AND itm.DATAAREAID=ins.DATAAREAID AND itm.UNITID=uc.FROMUNIT
		INNER JOIN cus.INVENTTABLE i ON i.ITEMID=ins.ITEMID
		WHERE itm.MODULETYPE=0
		AND uc.TOUNIT='ks'
		AND id.INVENTLOCATIONID IN ('AFK-MV','ADF-MV')
		AND ins.PHYSICALINVENT >=0
		AND uc.FACTOR <> 0.0
	GROUP BY i.ITEMID,id.DATAAREAID	

	)

	SELECT 
	[PURCHASE_ORDER_NO],
	[ITEM_NO],
	[LOCATION_NO],
	[DELIVERY_DATE],
	SUM([QUANTITY]) AS QUANTITY
	FROM undelivered
	GROUP BY 
	[PURCHASE_ORDER_NO],
	[ITEM_NO],
	[LOCATION_NO],
	[DELIVERY_DATE]

