
CREATE VIEW [ax_cus].[v_STOCK_LEVEL]
AS

SELECT
    CAST(ins.ITEMID AS NVARCHAR(255)) 					AS [ITEM_NO],
    CAST(iv.INVENTLOCATIONID AS NVARCHAR(255)) 			AS [LOCATION_NO],
    CAST(DATEFROMPARTS(2100, 1, 1) AS DATE)     		AS [EXPIRE_DATE],
    SUM(CAST(ins.AVAILPHYSICAL AS DECIMAL(18,4))) 		AS [STOCK_UNITS] --17.07.2025.DFS added to SaaS from OnPrem
FROM
    [ax_cus].INVENTSUM ins
        INNER JOIN
    [ax_cus].INVENTDIM iv
    ON	iv.INVENTDIMID		= ins.INVENTDIMID
        AND iv.DATAAREAID		= ins.DATAAREAID
        AND iv.PARTITION		= ins.PARTITION
WHERE
    CAST(ins.AVAILPHYSICAL AS DECIMAL(18,4)) > 0 --17.07.2025.DFS added to SaaS from OnPrem
  AND iv.INVENTLOCATIONID <> ''
GROUP BY
    ins.[ITEMID], iv.INVENTLOCATIONID

