CREATE VIEW [ax_cus].[v_UNDELIVERED_TRANSFER_ORDER] 
AS

       SELECT
            CAST(itl.TRANSFERID AS VARCHAR(128))               AS [TRANSFER_ORDER_NO],
            CAST(iv.NO AS NVARCHAR(255))                  AS [ITEM_NO],
            CAST(itt.INVENTLOCATIONIDTO AS NVARCHAR(255))      AS [LOCATION_NO],
            CAST(itl.RECEIVEDATE AS DATE)                      AS [DELIVERY_DATE],
            SUM(CAST(itl.QTYREMAINRECEIVE AS DECIMAL(18,4)))   AS [QUANTITY],
            CAST(itt.INVENTLOCATIONIDFROM AS NVARCHAR(255))    AS [ORDER_FROM_LOCATION_NO],
            CAST(itl.DATAAREAID AS NVARCHAR(4))                AS [COMPANY]
       FROM [ax].[INVENTTRANSFERLINE] itl
		INNER JOIN [ax].[INVENTTRANSFERTABLE] itt ON itl.TRANSFERID = itt.TRANSFERID AND itl.DATAAREAID = itt.DATAAREAID AND itl.PARTITION = itt.PARTITION
		INNER JOIN ax_cus.Item_v iv ON iv.No_TO_JOIN_IL = itl.ITEMID
	   WHERE	
		itt.TRANSFERSTATUS < 2  
	   GROUP BY itl.TRANSFERID, iv.NO, itt.INVENTLOCATIONIDTO, itt.INVENTLOCATIONIDFROM, itl.RECEIVEDATE, CAST(itl.DATAAREAID AS NVARCHAR(4))
