CREATE VIEW [fo_cus].[v_BOM_COMPONENT]
AS
SELECT
    CAST(bh.ENGCHGDISPLAYPRODUCTNUMBER AS NVARCHAR(155))  AS ITEM_NO,
    CAST(bl.ITEMNUMBER AS NVARCHAR(255)) AS COMPONENT_ITEM_NO,
    CAST(bl.QUANTITY AS DECIMAL(18,4)) AS QUANTITY
FROM 
    fo.BOMLines bl
LEFT JOIN fo.BOMHeaders bh ON bh.BOMID = bl.BOMID
WHERE bh.ENGCHGDISPLAYPRODUCTNUMBER IS NOT NULL
