CREATE VIEW [fo_cus].[v_SALES_HISTORY]
AS

   SELECT
    CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
    CAST(sol.ITEMNUMBER AS NVARCHAR(255)) AS ITEM_NO,
    CAST(sol.SHIPPINGWAREHOUSEID AS NVARCHAR(255)) AS LOCATION_NO,
    CAST(sol.CONFIRMEDRECEIPTDATE AS DATE) AS [DATE],
    CAST(SUM(CAST(sol.ORDEREDSALESQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS SALE,
    CAST(soh.SALESORDERNUMBER AS NVARCHAR(255)) AS REFERENCE_NO,
    CAST(0 AS BIT) AS IS_EXCLUDED,
    CAST(ISNULL(c.CUSTOMERACCOUNT, '') AS NVARCHAR(255)) AS CUSTOMER_NO
FROM
     fo.SalesOrderLines sol 
LEFT JOIN fo.SalesOrderHeaders soh
	ON soh.SALESORDERNUMBER = sol.SALESORDERNUMBER
LEFT JOIN fo.Customers c
    ON soh.DELIVERYADDRESSLOCATIONID = c.DELIVERYADDRESSLOCATIONID
WHERE CAST(sol.ITEMNUMBER AS NVARCHAR(255)) IS NOT NULL
GROUP BY CAST(sol.ITEMNUMBER AS NVARCHAR(255)),
         CAST(sol.SHIPPINGWAREHOUSEID AS NVARCHAR(255)),
         CAST(sol.CONFIRMEDRECEIPTDATE AS DATE),
         CAST(soh.SALESORDERNUMBER AS NVARCHAR(255)),
         CAST(ISNULL(c.CUSTOMERACCOUNT, '') AS NVARCHAR(255))
