

CREATE VIEW [fo_cus].[v_stock_history]
AS

SELECT
    CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
    CAST(tol.ITEMNUMBER AS NVARCHAR(255)) AS ITEM_NO,
    CAST(toh.SHIPPINGWAREHOUSEID AS NVARCHAR(255)) AS LOCATION_NO,
    CAST(tol.REQUESTEDRECEIPTDATE AS DATE) AS [DATE],
	-CAST(SUM(CAST(tol.TRANSFERQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [stock_move],
    CAST(NULL AS DECIMAL(18,4)) AS [stock_level]
FROM fo.TransferOrderLines tol
	LEFT JOIN fo.TransferOrderHeader toh
	ON toh.TRANSFERORDERNUMBER = tol.TRANSFERORDERNUMBER
	LEFT JOIN fo.Customers c ON c.DELIVERYADDRESSLOCATIONID = toh.RECEIVINGWAREHOUSEID
GROUP BY CAST(tol.ITEMNUMBER AS NVARCHAR(255)),
         CAST(toh.SHIPPINGWAREHOUSEID AS NVARCHAR(255)),
         CAST(tol.REQUESTEDRECEIPTDATE AS DATE)

UNION ALL

SELECT
    CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
    CAST(tol.ITEMNUMBER AS NVARCHAR(255)) AS ITEM_NO,
    CAST(toh.RECEIVINGWAREHOUSEID AS NVARCHAR(255)) AS LOCATION_NO,
    CAST(tol.REQUESTEDRECEIPTDATE AS DATE) AS [DATE],
	CAST(SUM(CAST(tol.TRANSFERQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [stock_move],
    CAST(NULL AS DECIMAL(18,4)) AS [stock_level]
FROM fo.TransferOrderLines tol
	LEFT JOIN fo.TransferOrderHeader toh
	ON toh.TRANSFERORDERNUMBER = tol.TRANSFERORDERNUMBER
	LEFT JOIN fo.Customers c ON c.DELIVERYADDRESSLOCATIONID = toh.RECEIVINGWAREHOUSEID
GROUP BY CAST(tol.ITEMNUMBER AS NVARCHAR(255)),
         CAST(toh.RECEIVINGWAREHOUSEID AS NVARCHAR(255)),
         CAST(tol.REQUESTEDRECEIPTDATE AS DATE)

UNION ALL

SELECT
    CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
    CAST(sol.ITEMNUMBER AS NVARCHAR(255)) AS ITEM_NO,
    CAST(sol.SHIPPINGWAREHOUSEID AS NVARCHAR(255)) AS LOCATION_NO,
    CAST(sol.CONFIRMEDRECEIPTDATE AS DATE) AS [DATE],
    -CAST(SUM(CAST(sol.ORDEREDSALESQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [stock_move],
    CAST(NULL AS DECIMAL(18,4)) AS [stock_level]
FROM
     fo.SalesOrderLines sol 
LEFT JOIN fo.SalesOrderHeaders soh
	ON soh.SALESORDERNUMBER = sol.SALESORDERNUMBER
LEFT JOIN fo.Customers c
    ON soh.DELIVERYADDRESSLOCATIONID = c.DELIVERYADDRESSLOCATIONID
WHERE CAST(sol.ITEMNUMBER AS NVARCHAR(255)) IS NOT NULL
GROUP BY CAST(sol.ITEMNUMBER AS NVARCHAR(255)),
         CAST(sol.SHIPPINGWAREHOUSEID AS NVARCHAR(255)),
         CAST(sol.CONFIRMEDRECEIPTDATE AS DATE)

UNION ALL

SELECT
    CAST(NULL AS NVARCHAR(128)) AS [Transaction_id],
    CAST(pol.ITEMNUMBER AS NVARCHAR(255)) AS [ITEM_NO],
    CAST(pol.RECEIVINGWAREHOUSEID AS NVARCHAR(255)) AS [location_no],
	CAST(pol.CONFIRMEDDELIVERYDATE AS DATE) AS [date],
    CAST(SUM(CAST(pol.ORDEREDPURCHASEQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [stock_move],
	CAST(NULL AS DECIMAL(18,4)) AS [stock_level]
FROM fo_cus.[PurchaseOrderLines] pol
WHERE CAST(pol.ITEMNUMBER AS NVARCHAR(255)) IS NOT NULL
GROUP BY 
    pol.ITEMNUMBER,
    pol.RECEIVINGWAREHOUSEID,
    pol.CONFIRMEDDELIVERYDATE

