CREATE VIEW [fo_cus].[v_TRANSFER_HISTORY]
AS

   SELECT
    CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
    CAST(tol.ITEMNUMBER AS NVARCHAR(255)) AS ITEM_NO,
    CAST(toh.SHIPPINGWAREHOUSEID AS NVARCHAR(255)) AS FROM_LOCATION_NO,
    CAST(toh.RECEIVINGWAREHOUSEID AS NVARCHAR(255)) AS TO_LOCATION_NO,
    CAST(tol.REQUESTEDRECEIPTDATE AS DATE) AS [DATE],
	CAST(SUM(CAST(tol.TRANSFERQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [TRANSFER],
    CAST(toh.TRANSFERORDERNUMBER AS NVARCHAR(255)) AS REFERENCE_NO,
    CAST(0 AS BIT) AS IS_EXCLUDED,
    CAST(ISNULL(c.CUSTOMERACCOUNT, '') AS NVARCHAR(255)) AS CUSTOMER_NO -- Replace NULL with ''
FROM fo.TransferOrderLines tol
	LEFT JOIN fo.TransferOrderHeader toh
	ON toh.TRANSFERORDERNUMBER = tol.TRANSFERORDERNUMBER
	LEFT JOIN fo.Customers c ON c.DELIVERYADDRESSLOCATIONID = toh.RECEIVINGWAREHOUSEID
GROUP BY CAST(tol.ITEMNUMBER AS NVARCHAR(255)),
         CAST(toh.SHIPPINGWAREHOUSEID AS NVARCHAR(255)),
         CAST(toh.RECEIVINGWAREHOUSEID AS NVARCHAR(255)),
         CAST(tol.REQUESTEDRECEIPTDATE AS DATE),
         CAST(toh.TRANSFERORDERNUMBER AS NVARCHAR(255)),
         CAST(ISNULL(c.CUSTOMERACCOUNT, '') AS NVARCHAR(255))
