CREATE VIEW [fo_cus].[v_UNDELIVERED_PURCHASE_ORDER]
AS

SELECT
    CAST(pol.PURCHASEORDERNUMBER AS NVARCHAR(128)) AS [purchase_order_no],
    CAST(pol.ITEMNUMBER AS NVARCHAR(255)) AS [ITEM_NO],
    CAST(pol.RECEIVINGWAREHOUSEID AS NVARCHAR(255)) AS [location_no],
    CAST(SUM(CAST(pol.ORDEREDPURCHASEQUANTITY AS DECIMAL(18,4))) AS DECIMAL(18,4)) AS [quantity],
    CAST(pol.CONFIRMEDDELIVERYDATE AS DATE) AS [delivery_date]
FROM fo_cus.[PurchaseOrderLines] pol
WHERE 
    CAST(pol.ITEMNUMBER AS NVARCHAR(255)) IS NOT NULL
GROUP BY 
    pol.PURCHASEORDERNUMBER,
    pol.ITEMNUMBER,
    pol.RECEIVINGWAREHOUSEID,
    pol.CONFIRMEDDELIVERYDATE
