CREATE TABLE [cus].[epicor_sql_columns] (
    [TABLE_TYPE] VARCHAR(10) NULL,
    [TABLE_SCHEMA] NVARCHAR(128) NULL,
    [TABLE_NAME] NVARCHAR(128) NULL,
    [COLUMN_NAME] NVARCHAR(128) NULL,
    [DATA_TYPE] NVARCHAR(128) NULL,
    [CHARACTER_MAXIMUM_LENGTH] INT NULL,
    [NUMERIC_PRECISION] TINYINT NULL,
    [NUMERIC_SCALE] INT NULL,
    [IS_PRIMARY_KEY] VARCHAR(3) NULL
);
