CREATE TABLE [cus].[SALE_HISTORY_LEGACY_2023] (
    [LOCATION_NO] NVARCHAR(255) NULL,
    [ITEM_NO] NVARCHAR(255) NULL,
    [DATE] NVARCHAR(255) NULL,
    [SALE] DECIMAL(18,10) NULL,
    [CustID] NVARCHAR(255) NULL
);
