CREATE TABLE [cos_cus].[AGR_STOCK_HISTORY] (
    [TRANSACTION_ID] BIGINT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DATE] DATE NOT NULL,
    [STOCK_MOVE] DECIMAL(18,4) NULL,
    [STOCK_LEVEL] DECIMAL(18,4) NULL
);
