CREATE TABLE [cos_cus].[AGR_SALES_HISTORY] (
    [TRANSACTION_ID] BIGINT NULL,
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [LOCATION_NO] NVARCHAR(255) NOT NULL,
    [DATE] DATE NOT NULL,
    [SALE] DECIMAL(18,4) NULL,
    [CUSTOMER_NO] NVARCHAR(255) NULL,
    [REFERENCE_NO] NVARCHAR(255) NULL,
    [IS_SALES_ORDER] BIT NULL,
    [IS_EXCLUDED] BIT NULL DEFAULT ((0))
);
