CREATE TABLE [bc_rest_cus].[item] (
    [No] NVARCHAR(20) NOT NULL,
    [VendorNo] NVARCHAR(20) NOT NULL,
    [VendorItemNo] NVARCHAR(50) NOT NULL,
    [ManufacturerCode] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(100) NOT NULL,
    [Description2] NVARCHAR(50) NULL,
    [ItemCategoryCode] NVARCHAR(20) NOT NULL,
    [PurchasingBlocked] BIT NOT NULL,
    [SalesBlocked] BIT NOT NULL,
    [Blocked] BIT NOT NULL,
    [GrossWeight] DECIMAL(38,20) NOT NULL,
    [UnitVolume] DECIMAL(38,20) NOT NULL,
    [UnitCost] DECIMAL(38,20) NOT NULL,
    [OrderMultiple] DECIMAL(38,20) NOT NULL,
    [MaximumInventory] DECIMAL(38,20) NOT NULL,
    [UnitPrice] DECIMAL(38,20) NOT NULL,
    [BaseUnitofMeasure] NVARCHAR(10) NOT NULL,
    [MinimumOrderQuantity] DECIMAL(38,20) NOT NULL,
    [PriceIncludesVAT] BIT NOT NULL,
    [ProductionBOMNo] NVARCHAR(20) NOT NULL,
    [LastDirectCost] DECIMAL(38,20) NOT NULL,
    [LeadTimeCalculation] NVARCHAR(32) NULL,
    [ReplenishmentSystem] NVARCHAR(100) NULL,
    [Type] NVARCHAR(100) NULL,
    [PurchUnitofMeasure] NVARCHAR(10) NULL,
    [ReorderingPolicy] NVARCHAR(100) NOT NULL,
    [SafetyStockQuantity] DECIMAL(38,20) NOT NULL,
    [ReorderPoint] DECIMAL(38,20) NOT NULL,
    CONSTRAINT [pk_bc_rest_item] PRIMARY KEY (No)
);
