CREATE TABLE [bc_rest_cus].[AGR_Price_List_Lines] (
    [Price_List_Code] NVARCHAR(20) NULL,
    [Line_No] INT NULL,
    [Status] NVARCHAR(30) NULL,
    [Source_Type] NVARCHAR(30) NULL,
    [Source_No] NVARCHAR(20) NULL,
    [Asset_Type] NVARCHAR(30) NULL,
    [Asset_No] NVARCHAR(20) NULL,
    [Description] NVARCHAR(100) NULL,
    [Variant_Code] NVARCHAR(10) NULL,
    [Unit_of_Measure_Code] NVARCHAR(10) NULL,
    [Minimum_Quantity] DECIMAL(28,10) NULL,
    [Amount_Type] NVARCHAR(30) NULL,
    [Currency_Code] NVARCHAR(10) NULL,
    [Unit_Price] DECIMAL(28,10) NULL,
    [DirectUnitCost] DECIMAL(28,10) NULL,
    [Unit_Cost] DECIMAL(28,10) NULL,
    [Starting_Date] DATE NULL,
    [Ending_Date] DATE NULL
);
