
CREATE VIEW [ax_cus].[v_STOCK_HISTORY] 
AS
       SELECT
            CAST(CONCAT(CONVERT(VARCHAR, CAST(it.DATEPHYSICAL AS DATE), 112),100000000+(ROW_NUMBER() OVER (PARTITION BY it.DATEPHYSICAL ORDER BY MAX(it.MODIFIEDDATETIME)))) AS BIGINT) AS [TRANSACTION_ID],
            CAST(it.ITEMID AS NVARCHAR(255))            AS [ITEM_NO],
            CAST(id.INVENTLOCATIONID AS NVARCHAR(255))  AS [LOCATION_NO],
            CAST(it.DATEPHYSICAL AS DATE)               AS [DATE],
            SUM(CAST(it.QTY AS DECIMAL(18,4)))          AS [STOCK_MOVE],
            CAST(NULL AS DECIMAL(18, 4))                AS [STOCK_LEVEL]
      FROM ax.INVENTTRANS it
	INNER JOIN ax_cus.INVENTTRANSORIGIN ito 
		ON it.INVENTTRANSORIGIN = ito.RECID
		AND it.DATAAREAID = ito.DATAAREAID
		AND it.[PARTITION] = ito.[PARTITION]
		AND it.DATEPHYSICAL <> '1900-01-01 00:00:00.000'
	INNER JOIN ax_cus.INVENTDIM id
		ON id.INVENTDIMID = it.INVENTDIMID
		AND id.DATAAREAID = it.DATAAREAID
		AND id.[PARTITION] = it.[PARTITION]
	GROUP BY
		it.DATEPHYSICAL,
		it.ITEMID,
		id.INVENTLOCATIONID 

