CREATE TABLE [fo_cus].[InventTrans] (
    [RECID1] NVARCHAR(155) NULL,
    [COSTAMOUNTPHYSICAL] NVARCHAR(155) NULL,
    [DATAAREAID1] NVARCHAR(155) NULL,
    [DATEINVENT] NVARCHAR(155) NULL,
    [DATEPHYSICAL] NVARCHAR(155) NULL,
    [INVENTDIMID] NVARCHAR(155) NULL,
    [INVENTTRANSID] NVARCHAR(155) NULL,
    [INVOICEID] NVARCHAR(155) NULL,
    [ITEMID] NVARCHAR(155) NULL,
    [PACKINGSLIPID] NVARCHAR(155) NULL,
    [QTY] NVARCHAR(155) NULL,
    [RECEIPTID] NVARCHAR(155) NULL,
    [REFERENCECATEGORY] NVARCHAR(155) NULL,
    [REFERENCEID] NVARCHAR(155) NULL,
    [STATUSISSUE] NVARCHAR(155) NULL,
    [STATUSRECEIPT] NVARCHAR(155) NULL
);
