CREATE TABLE [fo_cus].[InventDim] (
    [INVENTDIMID] NVARCHAR(155) NULL,
    [CONFIGID] NVARCHAR(155) NULL,
    [INVENTLOCATIONID] NVARCHAR(155) NULL,
    [INVENTSITEID] NVARCHAR(155) NULL,
    [RECID1] NVARCHAR(155) NULL
);
