CREATE TABLE [fo_cus].[ProductExtraInfo] (
    [ITEMNUMBER] NVARCHAR(155) NULL,
    [COVERAGEWAREHOUSEID] NVARCHAR(155) NULL,
    [COVERAGEPRODUCTCONFIGURATIONID] NVARCHAR(155) NULL,
    [COVERAGESITEID] NVARCHAR(155) NULL,
    [PRODUCTCOVERAGEGROUPID] NVARCHAR(155) NULL,
    [MAXIMUMONHANDINVENTORYQUANTITY] NVARCHAR(155) NULL,
    [MINIMUMONHANDINVENTORYQUANTITY] NVARCHAR(155) NULL,
    [PROCUREMENTLEADTIMEDAYS] NVARCHAR(155) NULL,
    [REORDERPOINT] NVARCHAR(155) NULL,
    [VENDORACCOUNTNUMBER] NVARCHAR(155) NULL
);
