CREATE TABLE [fo_cus].[ReqPo] (
    [RECID1] NVARCHAR(155) NULL,
    [BEA001BRANDID] NVARCHAR(155) NULL,
    [BEA420INVENTVERSIONID1] NVARCHAR(155) NULL,
    [COSTAMOUNT] NVARCHAR(155) NULL,
    [ITEMID] NVARCHAR(155) NULL,
    [PURCHID] NVARCHAR(155) NULL,
    [PURCHQTY] NVARCHAR(155) NULL,
    [PURCHUNIT] NVARCHAR(155) NULL,
    [QTY] NVARCHAR(155) NULL,
    [REFTYPE] NVARCHAR(155) NULL,
    [REQDATE] NVARCHAR(155) NULL,
    [VENDID] NVARCHAR(155) NULL
);
