CREATE TABLE [cus].[Prod] (
    [ProdNo] NVARCHAR(250) NOT NULL,
    [Descr] NVARCHAR(250) NOT NULL,
    [ProdGr] INT NOT NULL,
    [VolU] DECIMAL(18,4) NULL,
    [PictNo] NVARCHAR(250) NULL,
    [ExcPrint] INT NULL,
    [ProdTp] INT NULL,
    [StSaleUn] INT NOT NULL,
    [NWgtU] DECIMAL(28,6) NOT NULL,
    [TareU] DECIMAL(28,6) NOT NULL,
    [Buyer] INT NOT NULL,
    [Inf] NVARCHAR(40) NULL,
    [Inf2] NVARCHAR(40) NULL,
    [Inf3] NVARCHAR(40) NULL,
    [Inf4] NVARCHAR(40) NULL,
    [Inf5] NVARCHAR(40) NULL,
    [Inf6] NVARCHAR(40) NULL,
    [Inf7] NVARCHAR(40) NULL,
    [Inf8] NVARCHAR(40) NULL,
    [GR] INT NULL,
    [GR2] INT NULL,
    [GR3] INT NULL,
    [GR4] INT NULL,
    [GR5] INT NULL,
    [GR6] INT NULL,
    [GR7] INT NULL,
    [GR8] INT NULL,
    [GR9] INT NULL,
    [GR10] INT NULL,
    [GR11] INT NULL,
    [GR12] INT NULL,
    [ProdTp2] INT NULL,
    [ProdTp3] INT NULL,
    [ProdTp4] INT NULL,
    [ProdPrGr] NVARCHAR(50) NULL,
    CONSTRAINT [PK_cus_Prod] PRIMARY KEY (ProdNo)
);
