CREATE TABLE [cus].[ProdTr] (
    [JNo] NVARCHAR(250) NOT NULL,
    [TrNo] NVARCHAR(250) NOT NULL,
    [TrDt] NVARCHAR(250) NOT NULL,
    [ProdNo] NVARCHAR(250) NOT NULL,
    [FrStc] NVARCHAR(250) NOT NULL,
    [PrTp] NVARCHAR(250) NOT NULL,
    [StcMov] DECIMAL(18,4) NULL,
    [CustNo] NVARCHAR(250) NOT NULL,
    [TrTp] NVARCHAR(250) NULL,
    [InvoCust] NVARCHAR(250) NULL,
    [OrdNo] NVARCHAR(250) NULL,
    [FinDt] NVARCHAR(250) NOT NULL,
    [TransSt] NVARCHAR(250) NULL,
    [NoInvoAb] NVARCHAR(250) NULL,
    [InvoDt] NVARCHAR(250) NULL,
    CONSTRAINT [PK_cus_ProdTr] PRIMARY KEY (JNo,TrNo)
);
