CREATE TABLE [cus].[product_assortment] (
    [product_item_no] NVARCHAR(255) NOT NULL,
    [location_no] NVARCHAR(255) NOT NULL,
    [reorder_point] DECIMAL(18,4) NULL,
    [min_stock] DECIMAL(18,4) NULL,
    [max_stock] DECIMAL(18,4) NULL,
    [closed] BIT NOT NULL,
    [closed_for_ordering] BIT NULL,
    [responsible] NVARCHAR(255) NULL,
    [name] NVARCHAR(255) NULL,
    [description] NVARCHAR(1000) NULL,
    [primary_vendor_no] NVARCHAR(255) NULL,
    [lead_time_days] SMALLINT NULL,
    [order_frequency_days] SMALLINT NULL,
    [order_coverage_days] SMALLINT NULL,
    [min_order_qty] DECIMAL(18,4) NULL,
    [original_no] NVARCHAR(50) NULL,
    [sale_price] DECIMAL(18,4) NULL,
    [cost_price] DECIMAL(18,4) NULL,
    [purchase_price] DECIMAL(18,4) NULL,
    [order_multiple] DECIMAL(18,4) NULL,
    [qty_pallet] DECIMAL(18,4) NULL,
    [volume] DECIMAL(18,6) NULL,
    [weight] DECIMAL(18,6) NULL,
    CONSTRAINT [PK_cus_product_assortment] PRIMARY KEY (location_no,product_item_no)
);
