CREATE TABLE [cus].[product_info] (
    [no] NVARCHAR(255) NOT NULL,
    [name] NVARCHAR(255) NOT NULL,
    [product_no] NVARCHAR(255) NULL,
    [product_name] NVARCHAR(255) NULL,
    [size_no] NVARCHAR(50) NULL,
    [colour_no] NVARCHAR(50) NULL,
    [style_no] NVARCHAR(50) NULL,
    [description] NVARCHAR(1000) NULL,
    [primary_vendor_no] NVARCHAR(255) NULL,
    [lead_time_days] SMALLINT NULL,
    [order_frequency_days] SMALLINT NULL,
    [order_coverage_days] SMALLINT NULL,
    [min_order_qty] DECIMAL(18,4) NULL,
    [original_no] NVARCHAR(50) NULL,
    [closed] BIT NOT NULL,
    [closed_for_ordering] BIT NULL,
    [responsible] NVARCHAR(255) NULL,
    [sale_price] DECIMAL(18,4) NULL,
    [cost_price] DECIMAL(18,4) NULL,
    [purchase_price] DECIMAL(18,4) NULL,
    [order_multiple] DECIMAL(18,4) NULL,
    [qty_pallet] DECIMAL(18,4) NULL,
    [volume] DECIMAL(18,6) NULL,
    [weight] DECIMAL(18,6) NULL,
    [min_stock] DECIMAL(18,4) NULL,
    [max_stock] DECIMAL(18,4) NULL,
    [terminal_date] DATE NULL,
    [base_unit_of_measure] NVARCHAR(50) NULL,
    [purchase_unit_of_measure] NVARCHAR(50) NULL,
    [qty_per_purchase_unit] DECIMAL(18,4) NULL,
    [product_group_no_level_1] NVARCHAR(255) NULL,
    [product_group_no_level_2] NVARCHAR(255) NULL,
    [special_order] BIT NULL,
    [reorder_point] DECIMAL(18,4) NOT NULL,
    CONSTRAINT [PK_cus_product_info] PRIMARY KEY (no)
);
