CREATE TABLE [bc_rest_cus].[SALE_HISTORY_LEGACY_20250616] (
    [ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] NVARCHAR(255) NULL,
    [DATE] DATE NULL,
    [CUSTOMER_NO] NVARCHAR(255) NULL,
    [SALE] DECIMAL(18,4) NULL
);
