CREATE TABLE [cus].[Item_Location] (
    [PRODUCT_CODE] NVARCHAR(255) NULL,
    [LOCATION_NO] BIGINT NULL,
    [MIN_STOCK] FLOAT(53) NULL,
    [CLOSED] BIT NULL,
    [SETQTY] NVARCHAR(10) NULL,
    [VATRATE] INT NULL
);
