CREATE TABLE [cus].[Item_Extra_Info] (
    [ITEM_NO] NVARCHAR(255) NULL,
    [PURCHASE_VARIANT] BIT NULL,
    [TRANSFORMED_VARIANT] BIT NULL,
    [PURCHASING_NOTES] NVARCHAR(1000) NULL,
    [DELAYED] NVARCHAR(255) NULL
);
