CREATE TABLE [cus].[Location] (
    [NO] BIGINT NULL,
    [NAME] NVARCHAR(255) NULL,
    [DELIVERY_NAME] NVARCHAR(128) NULL,
    [DELIVERY_ADDRESS1] NVARCHAR(128) NULL,
    [DELIVERY_ADDRESS2] NVARCHAR(128) NULL,
    [DELIVERY_ADDRESS3] NVARCHAR(128) NULL,
    [DELIVERY_TOWN] NVARCHAR(128) NULL,
    [DELIVERY_COUNTY] NVARCHAR(128) NULL,
    [DELIVERY_POSTCODE] NVARCHAR(128) NULL,
    [DELIVERY_COUNTRY] NVARCHAR(128) NULL,
    [DELIVERY_TELEPHONE] NVARCHAR(128) NULL,
    [DELIVERY_COUNTRYCODE] NVARCHAR(128) NULL,
    [DELIVERY_EMAIL] NVARCHAR(128) NULL,
    [additionalpercentage] DECIMAL(28,2) NULL
);
