CREATE TABLE [cus].[Open_Sales_Order] (
    [SALES_ORDER_NO] NVARCHAR(255) NULL,
    [PRODUCT_ITEM_NO] NVARCHAR(255) NULL,
    [QUANTITY] FLOAT(53) NULL,
    [DELIVERY_DATE] NVARCHAR(255) NULL,
    [DELIVERY_STATUS] BIGINT NULL,
    [LOCATION] BIGINT NULL
);
