CREATE TABLE [cus].[Undelivered_Purchase_Order] (
    [PURCHASE_ORDER_NO] NVARCHAR(255) NULL,
    [PRODUCT_ITEM_NO] NVARCHAR(255) NULL,
    [LOCATION_NO] BIGINT NULL,
    [DELIVERY_DATE] NVARCHAR(255) NULL,
    [QUANTITY] FLOAT(53) NULL,
    [EXPIRE_DATE] NVARCHAR(255) NULL,
    [DELIV_STATUS] BIGINT NULL
);
