CREATE TABLE [cus].[Vendor_Extra_Info] (
    [VENDOR_NO] NVARCHAR(255) NULL,
    [SUPPLIER_ID] INT NULL,
    [SUPPLIER_VATRATE] INT NULL,
    [SUPPLIER_MINORDERVALUE] DECIMAL(18,2) NULL,
    [SUPPLIER_FREESHIPING] DECIMAL(18,2) NULL
);
