CREATE TABLE [cos_cus].[AGR_LOCATION] (
    [NO] NVARCHAR(255) NOT NULL,
    [NAME] NVARCHAR(255) NULL,
    [TYPE] NVARCHAR(255) NULL,
    [STOCK_LOCATION_NO] NVARCHAR(255) NULL,
    [STOCK_LOCATION_NAME] NVARCHAR(255) NULL,
    CONSTRAINT [pk_cos_cus_agr_location] PRIMARY KEY (NO)
);
