CREATE TABLE [visma_sql_cus].[Prod] (
    [ProdNo] NVARCHAR(250) NOT NULL,
    [Descr] NVARCHAR(250) NOT NULL,
    [ProdGr] INT NOT NULL,
    [VolU] DECIMAL(18,4) NULL,
    [PictNo] NVARCHAR(250) NULL,
    [ExcPrint] INT NULL,
    [ProdTp] INT NULL,
    [StSaleUn] INT NOT NULL,
    [NWgtU] DECIMAL(28,6) NOT NULL,
    [TareU] DECIMAL(28,6) NOT NULL,
    [Buyer] INT NOT NULL,
    [Inf] NVARCHAR(40) NULL,
    [Inf2] NVARCHAR(40) NULL,
    [Inf3] NVARCHAR(40) NULL,
    [Inf4] NVARCHAR(40) NULL,
    [Inf5] NVARCHAR(40) NULL,
    [Inf6] NVARCHAR(40) NULL,
    [Inf7] NVARCHAR(40) NULL,
    [Inf8] NVARCHAR(40) NULL,
    [Gr] INT NULL,
    [Gr2] INT NULL,
    [Gr3] INT NULL,
    [Gr4] INT NULL,
    [Gr5] INT NULL,
    [Gr6] INT NULL,
    [Gr7] INT NULL,
    [Gr8] INT NULL,
    [Gr9] INT NULL,
    [Gr10] INT NULL,
    [Gr11] INT NULL,
    [Gr12] INT NULL,
    [ProdTp2] INT NULL,
    [ProdTp3] INT NULL,
    [ProdTp4] INT NULL,
    [ProdPrGr] NVARCHAR(50) NULL,
    [NrmStc] INT NULL,
    [ExpStr] NVARCHAR(50) NULL,
    [ProdPrG3] INT NULL,
    [Rsp] INT NULL,
    CONSTRAINT [PK_visma_sql_cus_Prod] PRIMARY KEY (ProdNo)
);
