CREATE VIEW  [cus].[v_BOM_CONSUMPTION_HISTORY]
AS


SELECT
    CAST(ROW_NUMBER() OVER( ORDER BY X1.ID, X1.ITEM_NO, X1.LOCATION_NO, X1.DATE,X1.UNIT_QTY) AS BIGINT) AS [TRANSACTION_ID],
    X1.ITEM_NO,
    X1.LOCATION_NO,
    X1.DATE,
    X1.UNIT_QTY,
    X1.COMPANY FROM(
    SELECT
        CAST(RTRIM(MOP1.DEX_ROW_ID)AS BIGINT)               AS [ID],
        CAST(CONCAT(RTRIM(MOP1.ITEMNMBR), ' - ', MOP1.[Company]) AS NVARCHAR(255))         AS [ITEM_NO],
        CAST(RTRIM(MOP1.BACKFLUSHSITEID) AS NVARCHAR(255))  AS [LOCATION_NO],
        CAST(COALESCE(MOP0.DATERECD, GETDATE()) AS DATE)    AS [DATE],
        CAST(MOP1.QTYTOCONSUME AS DECIMAL(18,4))            AS [UNIT_QTY],
        MOP1.[Company]
    FROM
        [cus].[MOP1110] MOP1
    LEFT JOIN [cus].[MOP1100] MOP0 ON MOP0.MOPRCTNM = MOP1.MOPRCTNM ) X1
