CREATE VIEW [cus].[v_TRANSFER_HISTORY]
AS


SELECT
    CAST(ROW_NUMBER() OVER( ORDER BY X1.ID, X1.ITEM_NO, X1.FROM_LOCATION_NO, X1.TO_LOCATION_NO,X1.DATE, X1.TRANSFER) AS BIGINT) AS [TRANSACTION_ID],
    X1.ITEM_NO,
    X1.FROM_LOCATION_NO,
    X1.TO_LOCATION_NO,
    X1.DATE,
    X1.TRANSFER FROM(
        SELECT
            CAST(DEX_ROW_ID AS BIGINT) AS [ID],
            CAST(CONCAT(RTRIM(ITEMNMBR), ' - ', [Company])       AS NVARCHAR(255))   AS [ITEM_NO],
            CAST(TRXLOCTN       AS NVARCHAR(255))   AS [FROM_LOCATION_NO],
            CAST(TRNSTLOC       AS NVARCHAR(255))   AS [TO_LOCATION_NO],
            CAST(DOCDATE        AS DATE)            AS [DATE],
            CAST(TRFQTYTY       AS DECIMAL(18,4))   AS [TRANSFER]
        FROM
            [cus].[IV30300] ) X1

