
CREATE VIEW [cus].[v_UNDELIVERED_TRANSFER_ORDER]
AS
 
    SELECT
        CAST(SOPNUMBE AS NVARCHAR(128)) AS [TRANSFER_ORDER_NO],
        CAST(ITEMNMBR AS NVARCHAR(255)) AS [ITEM_NO],
        CAST(LOCNCODE AS NVARCHAR(255)) AS [LOCATION_NO],
        CAST('N/A' AS NVARCHAR(255))     AS [ORDER_FROM_LOCATION_NO], --NEEDS CONSIDERATION
        SUM(CAST(QUANTITY AS DECIMAL(18,4))) AS [QUANTITY],
		CAST(IIF(FUFILDAT='1900-01-01 00:00:00.000', GETDATE(),FUFILDAT) AS DATE) AS [DELIVERY_DATE],
        [Company]
    FROM 
        [cus].[SOP10200] 
    WHERE 1 = 0
	GROUP BY 
		SOPNUMBE, ITEMNMBR, LOCNCODE, FUFILDAT, Company
	HAVING SUM(CAST(QUANTITY AS DECIMAL(18, 4))) <> 0

