CREATE VIEW [cus].[v_UNDELIVERED_PURCHASE_ORDER]
AS

    SELECT
        CAST(RTRIM(PONUMBER) AS NVARCHAR(128)) AS [PURCHASE_ORDER_NO],
        CAST(CONCAT(RTRIM(ITEMNMBR), ' - ', [Company]) AS NVARCHAR(255)) AS [ITEM_NO],
        CAST(LOCNCODE AS NVARCHAR(255)) AS [LOCATION_NO],
        SUM(CAST(QTYUNCMTBASE AS DECIMAL(18,4))) AS [QUANTITY],
        CAST(PRMDATE AS DATE)           AS [DELIVERY_DATE],
        [Company]
    FROM
        [cus].[POP10110]
    WHERE
        POLNESTA < '5'
    GROUP BY
        RTRIM(PONUMBER), RTRIM(ITEMNMBR), LOCNCODE, PRMDATE, Company 
