CREATE TABLE [cus].[AGRINVENTTABLE] (
    [ITEMID] NVARCHAR(20) NOT NULL,
    [RELATEDITEMID] NVARCHAR(20) NOT NULL,
    [MODIFIEDDATETIME] DATETIME NOT NULL,
    [MODIFIEDBY] NVARCHAR(5) NOT NULL,
    [MODIFIEDTRANSACTIONID] BIGINT NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [pk_constraint_AGRINVENTTABLE_recid] PRIMARY KEY (RECID)
);
