CREATE TABLE [cus].[CEBPLINVENTITEMMAJORGROUP] (
    [MAJORGROUPID] NVARCHAR(10) NOT NULL,
    [NAME] NVARCHAR(60) NOT NULL,
    [ITEMGROUPID] NVARCHAR(10) NOT NULL,
    [MODIFIEDDATETIME] DATETIME NOT NULL,
    [DEL_MODIFIEDTIME] INT NOT NULL,
    [MODIFIEDBY] NVARCHAR(5) NOT NULL,
    [CREATEDDATETIME] DATETIME NOT NULL,
    [DEL_CREATEDTIME] INT NOT NULL,
    [CREATEDBY] NVARCHAR(5) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RECID] BIGINT NOT NULL
);
