CREATE TABLE [cus].[columns] (
    [TABLE_NAME] NVARCHAR(50) NOT NULL,
    [COLUMN_NAME] NVARCHAR(50) NOT NULL,
    [IS_NULLABLE] BIT NOT NULL,
    [DATA_TYPE] NVARCHAR(50) NOT NULL,
    [CHARACTER_MAXIMUM_LENGTH] INT NULL
);
