CREATE TABLE [cus].[CUSTVENDEXTERNALITEM] (
    [ITEMID] NVARCHAR(20) NOT NULL,
    [MODULETYPE] INT NOT NULL,
    [CUSTVENDRELATION] NVARCHAR(20) NOT NULL,
    [EXTERNALITEMTXT] NVARCHAR(1000) NOT NULL,
    [EXTERNALITEMID] NVARCHAR(20) NOT NULL,
    [ABCCATEGORY] INT NOT NULL,
    [DESCRIPTION] NVARCHAR(60) NOT NULL,
    [INVENTDIMID] NVARCHAR(20) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RECID] BIGINT NOT NULL
);
