CREATE TABLE [cus].[CUSTTABLE] (
    [ACCOUNTNUM] NVARCHAR(40) NOT NULL,
    [NAME] NVARCHAR(120) NOT NULL,
    [ADDRESS] NVARCHAR(500) NOT NULL,
    [PHONE] NVARCHAR(40) NOT NULL,
    [TELEFAX] NVARCHAR(40) NOT NULL,
    [INVOICEACCOUNT] NVARCHAR(40) NOT NULL,
    [CUSTGROUP] NVARCHAR(20) NOT NULL,
    [LINEDISC] NVARCHAR(20) NOT NULL,
    [PAYMTERMID] NVARCHAR(20) NOT NULL,
    [CASHDISC] NVARCHAR(20) NOT NULL,
    [STATISTICSGROUP] NVARCHAR(10) NOT NULL,
    CONSTRAINT [pk_constraint_CUSTTABLE_accountnum] PRIMARY KEY (ACCOUNTNUM)
);
