CREATE TABLE [cus].[INVENTDIM] (
    [INVENTDIMID] NVARCHAR(20) NOT NULL,
    [INVENTBATCHID] NVARCHAR(20) NOT NULL,
    [WMSLOCATIONID] NVARCHAR(10) NOT NULL,
    [INVENTSERIALID] NVARCHAR(20) NOT NULL,
    [INVENTLOCATIONID] NVARCHAR(10) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [INVENTSITEID] NVARCHAR(10) NOT NULL,
    CONSTRAINT [pk_constraint_inventdim_recid] PRIMARY KEY (RECID)
);
