CREATE TABLE [cus].[INVENTITEMGROUP] (
    [ITEMGROUPID] NVARCHAR(10) NOT NULL,
    [NAME] NVARCHAR(60) NOT NULL,
    [STANDARDITEMALLOCATEID] NVARCHAR(10) NOT NULL,
    [TAXITEMGROUPIDSALES] NVARCHAR(10) NOT NULL,
    [TAXITEMGROUPIDPURCH] NVARCHAR(10) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RECID] BIGINT NOT NULL,
    [AWSEXPIRATIONDAYS] INT NOT NULL,
    CONSTRAINT [pk_constraint_INVENTITEMGROUP_recid] PRIMARY KEY (RECID)
);
