CREATE TABLE [cus].[UNITCONVERT] (
    [FROMUNIT] NVARCHAR(10) NOT NULL,
    [TOUNIT] NVARCHAR(10) NOT NULL,
    [FACTOR] NUMERIC(18,2) NOT NULL,
    [MARKUP] NUMERIC(18,2) NOT NULL,
    [ROUNDOFF] INT NOT NULL,
    [ITEMID] NVARCHAR(20) NOT NULL,
    [DATAAREAID] NVARCHAR(4) NOT NULL,
    [RECVERSION] INT NOT NULL,
    [RECID] BIGINT NOT NULL,
    CONSTRAINT [pk_constraint_UNITCONVERT_recid] PRIMARY KEY (RECID)
);
