CREATE TABLE [cus].[OIBT] (
    [ItemCode] NVARCHAR(50) NOT NULL,
    [BatchNum] NVARCHAR(36) NULL,
    [WhsCode] NVARCHAR(8) NULL,
    [ItemName] NVARCHAR(200) NULL,
    [SuppSerial] NVARCHAR(36) NULL,
    [IntrSerial] NVARCHAR(36) NULL,
    [ExpDate] DATETIME NULL,
    [PrdDate] DATETIME NULL,
    [InDate] DATETIME NULL,
    [Located] NVARCHAR(100) NULL,
    [Quantity] NUMERIC(19,6) NULL,
    [BaseType] INT NULL,
    [BaseEntry] INT NULL,
    [BaseNum] INT NULL,
    [BaseLinNum] INT NULL,
    [CardCode] NVARCHAR(15) NULL,
    [CardName] NVARCHAR(100) NULL,
    [CreateDate] DATETIME NULL,
    [Status] CHAR(1) NULL,
    [Direction] INT NOT NULL,
    [IsCommited] NUMERIC(19,6) NULL,
    [OnOrder] INT NOT NULL,
    [Consig] INT NOT NULL,
    [DataSource] CHAR(1) NULL,
    [UserSign] SMALLINT NULL,
    [Transfered] CHAR(1) NULL,
    [Instance] SMALLINT NULL,
    [SysNumber] INT NOT NULL,
    [LogInstanc] INT NULL,
    [UserSign2] SMALLINT NULL,
    [UpdateDate] DATETIME NULL
);
