CREATE TABLE [cus].[OITM] (
    [ItemCode] NVARCHAR(50) NOT NULL,
    [ItemName] NVARCHAR(200) NULL,
    [ItmsGrpCod] SMALLINT NULL,
    [PrchseItem] CHAR(1) NULL,
    [InvntItem] CHAR(1) NULL,
    [OnHand] NUMERIC(19,6) NULL,
    [MaxLevel] NUMERIC(19,6) NULL,
    [DfltWH] NVARCHAR(8) NULL,
    [CardCode] NVARCHAR(15) NULL,
    [MinLevel] NUMERIC(19,6) NULL,
    [SVolume] NUMERIC(19,6) NULL,
    [BVolume] NUMERIC(19,6) NULL,
    [SWeight1] NUMERIC(19,6) NULL,
    [frozenFor] CHAR(1) NULL,
    [OrdrMulti] NUMERIC(19,6) NULL,
    [MinOrdrQty] NUMERIC(19,6) NULL,
    [LeadTime] INT NULL,
    [ToleranDay] INT NULL,
    [ReorderPnt] DECIMAL(19,6) NULL,
    [OrdrIntrvl] INT NULL,
    [Location] INT NULL,
    [QryGroup17] CHAR(1) NULL,
    [QryGroup16] CHAR(1) NULL,
    [QryGroup10] CHAR(1) NULL,
    [QryGroup6] CHAR(1) NULL,
    [QryGroup8] CHAR(1) NULL,
    [QryGroup9] CHAR(1) NULL,
    [QryGroup35] CHAR(1) NULL,
    [VatGourpSa] NVARCHAR(16) NULL,
    [BuyUnitMsr] NVARCHAR(100) NULL,
    [NumInBuy] DECIMAL(19,6) NULL,
    [FrgnName] NVARCHAR(100) NULL,
    [U_TRC_COLL_ITM_GROUP] NVARCHAR(255) NULL,
    [U_TRC_COLLECTION] NVARCHAR(255) NULL,
    [U_TRC_Style] NVARCHAR(255) NULL,
    [QryGroup4] NVARCHAR(2) NULL
);
