CREATE TABLE [ogl_cus].[STDepotTransfers] (
    [ref] NVARCHAR(255) NULL,
    [intref] INT NULL,
    [depot1] NVARCHAR(255) NULL,
    [depot2] NVARCHAR(255) NULL,
    [trdate] NVARCHAR(255) NULL,
    [stcode] NVARCHAR(255) NULL,
    [quan] NVARCHAR(255) NULL,
    [printind] INT NULL,
    [pordno] INT NULL,
    [puniqueno] INT NULL,
    [desc_] NVARCHAR(255) NULL,
    [recviatransf] NVARCHAR(255) NULL,
    [amendinprog] NVARCHAR(255) NULL,
    [amenduser] NVARCHAR(255) NULL,
    [cpcode] NVARCHAR(255) NULL,
    [commodity] NVARCHAR(255) NULL,
    [commcdsfx] NVARCHAR(255) NULL,
    [packedweight] NVARCHAR(255) NULL,
    [packedlnwgt] NVARCHAR(255) NULL,
    [sqldeleteflag] NVARCHAR(255) NULL
);
