CREATE TABLE [ogl_cus].[STDepotTransfers_datetypes] (
    [ref] NVARCHAR(15) NULL,
    [intref] INT NULL,
    [depot1] NVARCHAR(2) NULL,
    [depot2] NVARCHAR(2) NULL,
    [trdate] DATETIME NULL,
    [stcode] NVARCHAR(24) NULL,
    [quan] NVARCHAR(30) NULL,
    [printind] INT NULL,
    [pordno] INT NULL,
    [puniqueno] INT NULL,
    [desc_] NVARCHAR(30) NULL,
    [recviatransf] NVARCHAR(1) NULL,
    [amendinprog] NVARCHAR(50) NULL,
    [amenduser] NVARCHAR(8) NULL,
    [cpcode] NVARCHAR(7) NULL,
    [commodity] NVARCHAR(8) NULL,
    [commcdsfx] NVARCHAR(2) NULL,
    [packedweight] NVARCHAR(50) NULL,
    [packedlnwgt] NVARCHAR(30) NULL,
    [sqldeleteflag] NVARCHAR(1) NULL
);
