CREATE TABLE [ogl_cus].[WOOrders_datetypes] (
    [COLUMN_NAME] NVARCHAR(MAX) NULL,
    [DATA_TYPE] NVARCHAR(MAX) NULL,
    [MAX_LENGTH] NVARCHAR(MAX) NULL,
    [SCALE] NVARCHAR(MAX) NULL,
    [IS_NULLABLE] NVARCHAR(MAX) NULL,
    [PRIMARY_KEY] NVARCHAR(MAX) NULL
);
