CREATE VIEW [ax_cus].[v_BOM_CONSUMPTION_HISTORY]
AS
SELECT 
    CAST(it.RECID AS NVARCHAR(255))                 AS [TRANSACTION_ID],
    CAST(it.ITEMID AS NVARCHAR(255))                AS [ITEM_NO],
    CAST(idim.INVENTLOCATIONID AS NVARCHAR(255))    AS [LOCATION_NO],
    CAST(it.DATEPHYSICAL AS DATE)                   AS [DATE],
    -CAST(it.QTY AS DECIMAL(18,4))                  AS [UNIT_QTY]
FROM ax.INVENTTRANS it
INNER JOIN ax.INVENTDIM idim ON it.INVENTDIMID = idim.INVENTDIMID AND it.DATAAREAID = idim.DATAAREAID AND (it.PARTITION = idim.PARTITION OR (it.PARTITION IS NULL AND idim.PARTITION IS NULL))
INNER JOIN ax.INVENTTRANSORIGIN ito ON it.INVENTTRANSORIGIN = ito.RECID AND it.DATAAREAID = ito.DATAAREAID AND (it.PARTITION = ito.PARTITION OR (it.PARTITION IS NULL AND ito.PARTITION IS NULL))
WHERE 
    it.QTY < 0
	AND 1=0

