

CREATE VIEW [ax_cus].[v_ITEM_GROUP] 
AS

   SELECT 
        CAST(it.ITEMGROUPID AS NVARCHAR(255)) AS [NO],
        --CAST(it.NAME AS NVARCHAR(255))        AS [NAME],
		CAST(it.ITEMGROUPID AS NVARCHAR(255)) AS [NAME],
        CAST(it.DATAAREAID AS NVARCHAR(4))    AS [COMPANY]
   FROM [ax].INVENTITEMGROUP it

   UNION 

	SELECT DISTINCT 
		CAST(SUPPITEMGROUPID AS NVARCHAR(255)) AS [NO],
		--CAST(it.NAME AS NVARCHAR(255))        AS [NAME],
		CAST(SUPPITEMGROUPID AS NVARCHAR(255)) AS [NAME],
		CAST(DATAAREAID AS NVARCHAR(4))    AS [COMPANY]
	FROM [ax_cus].INVENTTABLEMODULE


