CREATE VIEW [ax_cus].[V_PURCHASE_ORDER_ROUTE]
AS
SELECT
    CAST(iips.ITEMID AS NVARCHAR(255))                  AS [ITEM_NO],
    CAST(dim.INVENTLOCATIONID AS NVARCHAR(255))         AS [LOCATION_NO],
    CAST('' AS NVARCHAR(255))							AS [VENDOR_NO],
    CAST(CASE WHEN 1 = 0 THEN 1 ELSE 0 END AS BIT)      AS [PRIMARY],
    CAST(iips.LEADTIME AS SMALLINT)                     AS [LEAD_TIME_DAYS],
    CAST(NULL AS SMALLINT)                              AS [ORDER_FREQUENCY_DAYS],
    CAST(iips.LOWESTQTY AS DECIMAL(18, 4))              AS [MIN_ORDER_QTY],
    CAST(inv.PRICE AS DECIMAL(18, 4))                   AS [COST_PRICE],
    CAST(pur.PRICE AS DECIMAL(18, 4))                   AS [PURCHASE_PRICE],
    CAST(iips.MULTIPLEQTY AS DECIMAL(18, 4))            AS [ORDER_MULTIPLE],
    CAST(NULL AS DECIMAL(18, 4))                        AS [QTY_PALLET],
    CAST(iips.DATAAREAID AS NVARCHAR(4))                AS [COMPANY]
FROM ax.INVENTITEMPURCHSETUP AS iips
INNER JOIN ax.INVENTDIM AS dim
    ON dim.INVENTDIMID = iips.INVENTDIMID
    AND dim.DATAAREAID = iips.DATAAREAID
    AND dim.PARTITION = iips.PARTITION
LEFT JOIN [ax_cus].INVENTTABLEMODULE AS inv
    ON inv.ITEMID = iips.ITEMID
    AND inv.MODULETYPE = 0 /* INVENTORY */
    AND inv.DATAAREAID = iips.DATAAREAID
    AND inv.PARTITION = iips.PARTITION
LEFT JOIN [ax_cus].INVENTTABLEMODULE AS pur
    ON pur.ITEMID = iips.ITEMID
    AND pur.MODULETYPE = 1 /* PURCHASE */
    AND pur.DATAAREAID = iips.DATAAREAID
    AND pur.PARTITION = iips.PARTITION
INNER JOIN core.location_mapping_setup lms ON lms.locationNo=dim.INVENTLOCATIONID


