
CREATE VIEW [ax_cus].[v_SALES_HISTORY]
AS

	SELECT 
		CAST(NULL AS BIGINT) 									AS [TRANSACTION_ID],
		CAST(it.ITEMID AS NVARCHAR(255))						AS [ITEM_NO],
		loc.INVENTLOCATIONID 									AS LOCATION_NO,
		it.DATEPHYSICAL 										AS [DATE],
		SUM(-CAST(it.QTY AS DECIMAL(18,4)))						AS SALE,
		CAST(IIF(agrs.[ Original customer]<>'',agrs.[ Original customer],ISNULL(cj.ORDERACCOUNT,'')) AS NVARCHAR(255))       AS [CUSTOMER_NO],
		CAST(IIF(agrs.[Original salesid]<>'',agrs.[Original salesid],ISNULL(ct.SALESID,'')) AS NVARCHAR(255))			AS [REFERENCE_NO],
		--ISNULL(CAST(cj.ORDERACCOUNT AS NVARCHAR(255)),'')       AS [CUSTOMER_NO],
		--ISNULL(CAST(ct.SALESID AS NVARCHAR(255)),'')			AS [REFERENCE_NO],
		CAST(0 AS BIT)											AS [IS_EXCLUDED]
	FROM 
		[ax].INVENTTRANS it 
		INNER JOIN [ax].INVENTTRANSORIGIN ito ON it.INVENTTRANSORIGIN = ito.RECID AND  it.PARTITION = ito.PARTITION AND it.DATAAREAID = ito.DATAAREAID
		INNER JOIN [ax].INVENTDIM id ON id.INVENTDIMID = it.INVENTDIMID AND id.DATAAREAID = it.DATAAREAID AND id.PARTITION = ito.PARTITION 
		INNER JOIN ax.INVENTLOCATION loc ON loc.INVENTLOCATIONID = id.INVENTLOCATIONID AND loc.DATAAREAID = id.DATAAREAID AND loc.PARTITION = id.PARTITION
		INNER JOIN core.location_mapping_setup lms ON lms.locationNo=loc.INVENTLOCATIONID
		LEFT JOIN ( SELECT INVOICEID,INVOICEDATE,DATAAREAID,SALESID,PARTITION 
					FROM ax_cus.CUSTINVOICETRANS 
					GROUP BY INVOICEID, INVOICEDATE, DATAAREAID,SALESID,PARTITION) ct  ON ct.INVOICEID = it.INVOICEID AND it.DATAAREAID = ct.DATAAREAID AND ct.PARTITION = it.PARTITION
		LEFT JOIN ax_cus.CUSTINVOICEJOUR cj 	 ON cj.INVOICEID = ct.INVOICEID AND cj.INVOICEDATE = ct.INVOICEDATE AND cj.DATAAREAID = ct.DATAAREAID AND cj.PARTITION = ct.PARTITION
		--LEFT JOIN ax_cus.DC_60793_AGRSupport agrs ON agrs.InvoiceId = it.INVOICEID AND agrs.InventTransOrigin = it.INVENTTRANSORIGIN AND agrs.ItemID = it.ITEMID
		-- 22.07.2025.DRG temporary until their IT guy fixes the duplications. 
		LEFT JOIN (SELECT DISTINCT * FROM ax_cus.DC_60793_AGRSupport) agrs ON agrs.InvoiceId = it.INVOICEID AND agrs.InventTransOrigin = it.INVENTTRANSORIGIN AND agrs.ItemID = it.ITEMID
	WHERE 
		it.DATEPHYSICAL > '1/1/1900'
		AND ito.REFERENCECATEGORY IN (0,12) 
		AND it.STATUSISSUE IN (0,1)
		--AND it.INVENTTRANSORIGIN='5641133115' AND it.ITEMID='P423.19.2151.6'
	GROUP BY 
		it.RECID,
		it.ITEMID ,
		loc.INVENTLOCATIONID,
		it.DATEPHYSICAL,
		CAST(IIF(agrs.[ Original customer]<>'',agrs.[ Original customer],ISNULL(cj.ORDERACCOUNT,'')) AS NVARCHAR(255)),
		CAST(IIF(agrs.[Original salesid]<>'',agrs.[Original salesid],ISNULL(ct.SALESID,'')) AS NVARCHAR(255))
		--ISNULL(CAST(cj.ORDERACCOUNT AS NVARCHAR(255)),''),
		--ISNULL(CAST(ct.SALESID AS NVARCHAR(255)),'')

		

