CREATE VIEW [ax_cus].[v_STOCK_HISTORY] 
AS
       SELECT
            CAST(CONCAT(CONVERT(VARCHAR, CAST(it.DATEPHYSICAL AS DATE), 112),100000000+(ROW_NUMBER() OVER (PARTITION BY it.DATEPHYSICAL ORDER BY MAX(it.MODIFIEDDATETIME)))) AS BIGINT) AS [TRANSACTION_ID],
            CAST(it.ITEMID AS NVARCHAR(255))            AS [ITEM_NO],
            CAST(id.INVENTLOCATIONID AS NVARCHAR(255))  AS [LOCATION_NO],
            CAST(it.DATEPHYSICAL AS DATE)               AS [DATE],
            SUM(CAST(it.QTY AS DECIMAL(18,4)))          AS [STOCK_MOVE],
            CAST(NULL AS DECIMAL(18, 4))                AS [STOCK_LEVEL]
      FROM 
		[ax].INVENTTRANS it 
		INNER JOIN [ax].INVENTTRANSORIGIN ito ON it.INVENTTRANSORIGIN = ito.RECID AND  it.PARTITION = ito.PARTITION AND it.DATAAREAID = ito.DATAAREAID
		INNER JOIN [ax].INVENTDIM id ON id.INVENTDIMID = it.INVENTDIMID AND id.DATAAREAID = it.DATAAREAID AND id.PARTITION = ito.PARTITION
		INNER JOIN core.location_mapping_setup lms ON lms.locationNo=id.INVENTLOCATIONID
	WHERE it.DATEPHYSICAL > CAST('1900-01-01' AS DATE)
		    GROUP BY it.RECID,
            it.ITEMID ,
            id.INVENTLOCATIONID ,
            it.DATEPHYSICAL

