


    CREATE VIEW [cos_cus].[v_TRANSFER_HISTORY] AS
	SELECT
		CAST(s.[TRANSACTION_ID] AS BIGINT) AS [TRANSACTION_ID],
		CAST(s.[ITEM_NO] AS NVARCHAR(255)) AS [ITEM_NO],
		CAST(
			CASE
				WHEN loc_from.STOCK_LOCATION_NO = '0259' THEN '0259'
				ELSE s.[FROM_LOCATION_NO]
			END AS NVARCHAR(255)
		) AS [FROM_LOCATION_NO],
		CAST(s.[TO_LOCATION_NO] AS NVARCHAR(255)) AS [TO_LOCATION_NO],
		CAST(s.[DATE] AS DATE) AS [DATE],
		CAST(s.[TRANSFER] AS DECIMAL(18, 4)) AS [TRANSFER]
	FROM [cos].AGR_TRANSFER_HISTORY s
	INNER JOIN cos_cus.AGR_LOCATION loc_from 
		ON loc_from.NO = s.[FROM_LOCATION_NO]
	INNER JOIN cos_cus.AGR_LOCATION loc_to 
		ON loc_to.NO = s.[TO_LOCATION_NO]
	WHERE 
	NOT (
		loc_from.STOCK_LOCATION_NO = '0259'
		AND loc_to.STOCK_LOCATION_NO = '0259'
	);

	  
	   

