CREATE VIEW [ax_cus].[V_PURCHASE_ORDER_ROUTE]
AS

	WITH customer_dupes AS (
		SELECT *,
				ROW_NUMBER() OVER (
					PARTITION BY ITEMID, CUSTVENDRELATION
					ORDER BY RECID
				) AS rn
			FROM ax_cus.CUSTVENDEXTERNALITEM
		WHERE MODULETYPE=3 --and ITEMID='0013256'
	)

	SELECT DISTINCT
		CAST(it.[ITEMID]
				+ CASE WHEN id2.INVENTSIZEID  <> '' AND id2.INVENTSIZEID IS NOT NULL THEN '_' + id2.INVENTSIZEID ELSE '' END
				+ CASE WHEN id2.INVENTCOLORID <> '' AND id2.INVENTCOLORID IS NOT NULL THEN '_' + id2.INVENTCOLORID ELSE '' END
				+ CASE WHEN id2.INVENTSTYLEID <> '' AND id2.INVENTSTYLEID IS NOT NULL THEN '_' + id2.INVENTSTYLEID ELSE '' END 
					AS NVARCHAR(255))																								AS [ITEM_NO],
		CAST(CONCAT('LAG',id.INVENTSITEID) AS NVARCHAR(255))																		AS [LOCATION_NO],
		CAST(vendext.CUSTVENDRELATION AS NVARCHAR(255))																				AS [VENDOR_NO],
		CAST(CASE
				WHEN vendext.CUSTVENDRELATION = it.PRIMARYVENDORID THEN 1
				ELSE 0 
				END AS BIT)																											AS [PRIMARY],
		CAST(CASE 
					WHEN req.REQPOTYPEACTIVE=1 AND req.LEADTIMEPURCHASEACTIVE=1 THEN req.LEADTIMEPURCHASE
					WHEN req.REQPOTYPEACTIVE=1 AND req.LEADTIMEPURCHASEACTIVE=0 THEN NULL
					WHEN (ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0 AND req.LEADTIMEPURCHASEACTIVE=1 THEN req.LEADTIMEPURCHASE
					WHEN (ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0 THEN NULL
					ELSE 1 END AS SMALLINT)																							AS LEAD_TIME_DAYS,
		CAST(NULL AS SMALLINT)																										AS ORDER_FREQUENCY_DAYS,
		CAST(CASE WHEN (req.REQPOTYPEACTIVE=1)OR((ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0) 
						THEN NULL
						ELSE 1 END AS DECIMAL(18,4))																				AS [MIN_ORDER_QTY],
		CAST(NULL AS DECIMAL(18,4))																									AS [COST_PRICE],
		CAST(NULL AS DECIMAL(18,4))																									AS [PURCHASE_PRICE],
		CAST(CASE WHEN (req.REQPOTYPEACTIVE=1)OR((ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0) THEN NULL
						ELSE 1 END AS DECIMAL(18,4))																				AS [ORDER_MULTIPLE],
		CAST(NULL AS DECIMAL(18,4))																									AS [QTY_PALLET],
		CAST(it.DATAAREAID AS NVARCHAR(255))																						AS COMPANY
	FROM 
	ax_cus.INVENTTABLE it
	inner JOIN ax_cus.REQITEMTABLE req						ON it.ITEMID = req.ITEMID  AND req.DATAAREAID = it.DATAAREAID AND req.REQPOTYPE=0 --0=purchase Order
	inner JOIN ax.INVENTDIM id								ON id.INVENTDIMID=req.COVINVENTDIMID AND id.DATAAREAID = req.DATAAREAID
	inner JOIN customer_dupes vendext						ON req.ITEMID = vendext.ITEMID AND vendext.DATAAREAID = req.DATAAREAID AND it.[PARTITION]=vendext.[PARTITION] AND vendext.rn = 1
    inner JOIN ax.INVENTDIM id2							    ON id2.INVENTDIMID=vendext.INVENTDIMID AND id.DATAAREAID = vendext.DATAAREAID
	    --INNER JOIN core.location_mapping_setup lms				ON lms.locationNo = CONCAT('LAG',id.INVENTSITEID)
	INNER JOIN ax_cus.INVENTLOCATION il						ON CONCAT('LAG',id.INVENTSITEID)=il.INVENTLOCATIONID
