



CREATE VIEW [ax_cus].[V_PURCHASE_ORDER_ROUTE_TEST]
AS

	WITH customer_dupes AS (
		SELECT *,
				ROW_NUMBER() OVER (
					PARTITION BY ITEMID, CUSTVENDRELATION
					ORDER BY RECID
				) AS rn
			FROM ax_cus.CUSTVENDEXTERNALITEM
		WHERE ITEMID='0013256'
	)

	SELECT DISTINCT
		CAST(it.[ITEMID]
				+ CASE WHEN id2.INVENTSIZEID  <> '' AND id2.INVENTSIZEID IS NOT NULL THEN '_' + id2.INVENTSIZEID ELSE '' END
				+ CASE WHEN id2.INVENTCOLORID <> '' AND id2.INVENTCOLORID IS NOT NULL THEN '_' + id2.INVENTCOLORID ELSE '' END
				+ CASE WHEN id2.INVENTSTYLEID <> '' AND id2.INVENTSTYLEID IS NOT NULL THEN '_' + id2.INVENTSTYLEID ELSE '' END 
				AS NVARCHAR(255))																									AS [ITEM_NO],
		CASE
			WHEN
				id.INVENTSITEID IS NULL
				THEN id2.INVENTLOCATIONID
			ELSE
				CONCAT('LAG',id.INVENTSITEID)	
			END																														AS [LOCATION_NO],
		CASE
			WHEN
				req.INVENTLOCATIONIDREQMAIN IS NULL
				THEN it.PRIMARYVENDORID
			ELSE
				IIF(req.INVENTLOCATIONIDREQMAIN = '',it.PRIMARYVENDORID,req.INVENTLOCATIONIDREQMAIN)
		END																															AS [VENDOR_NO],
		CAST(CASE
				WHEN vendext.CUSTVENDRELATION = it.PRIMARYVENDORID THEN 1
				ELSE 0 
				END AS BIT)																											AS [PRIMARY],
		CAST(CASE 
					WHEN req.REQPOTYPEACTIVE=1 AND req.LEADTIMEPURCHASEACTIVE=1 THEN req.LEADTIMEPURCHASE
					WHEN req.REQPOTYPEACTIVE=1 AND req.LEADTIMEPURCHASEACTIVE=0 THEN NULL
					WHEN (ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0 AND req.LEADTIMEPURCHASEACTIVE=1 THEN req.LEADTIMEPURCHASE
					WHEN (ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0 THEN NULL
					ELSE 1 END AS SMALLINT)																							AS LEAD_TIME_DAYS,
		CAST(NULL AS SMALLINT)																										AS ORDER_FREQUENCY_DAYS,
		CAST(CASE WHEN (req.REQPOTYPEACTIVE=1)OR((ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0) 
						THEN NULL
						ELSE 1 END AS DECIMAL(18,4))																				AS [MIN_ORDER_QTY],
		CAST(NULL AS DECIMAL(18,4))																									AS [COST_PRICE],
		CAST(NULL AS DECIMAL(18,4))																									AS [PURCHASE_PRICE],
		CAST(CASE WHEN (req.REQPOTYPEACTIVE=1)OR((ISNULL(req.REQPOTYPEACTIVE, 0)=0)AND il.REQREFILL=0) THEN NULL
						ELSE 1 END AS DECIMAL(18,4))																				AS [ORDER_MULTIPLE],
		CAST(NULL AS DECIMAL(18,4))																									AS [QTY_PALLET],
		CAST(it.DATAAREAID AS NVARCHAR(255))																						AS COMPANY
	FROM 
		ax_cus.INVENTTABLE it
		LEFT JOIN ax_cus.REQITEMTABLE req	ON req.ITEMID = it.ITEMID
		LEFT JOIN ax.INVENTDIM id			ON id.INVENTDIMID = req.COVINVENTDIMID AND ISNULL(id.DATAAREAID,'byko') = it.DATAAREAID		
		LEFT JOIN ax.INVENTTRANS itt		ON itt.ITEMID = it.ITEMID AND itt.DATAAREAID = it.DATAAREAID
		LEFT JOIN ax.INVENTDIM id2			ON id2.INVENTDIMID = itt.INVENTDIMID AND id2.DATAAREAID = itt.DATAAREAID
		INNER JOIN core.location_mapping_setup lms ON lms.locationNo = id2.INVENTLOCATIONID AND lms.isVirtual = 0
		INNER JOIN customer_dupes vendext	ON req.ITEMID = vendext.ITEMID AND vendext.DATAAREAID = req.DATAAREAID AND it.[PARTITION]=vendext.[PARTITION] AND vendext.rn = 1
		INNER JOIN ax_cus.INVENTLOCATION il						ON lms.locationNo=il.INVENTLOCATIONID


