


CREATE VIEW [ax_cus].[v_SALES_HISTORY]
AS

		SELECT
			CAST(NULL AS BIGINT) 																								AS TRANSACTION_ID,
			CAST(it.[ITEMID]
				+ CASE WHEN id.INVENTSIZEID  <> '' AND id.INVENTSIZEID IS NOT NULL THEN '_' + id.INVENTSIZEID ELSE '' END
				+ CASE WHEN id.INVENTCOLORID <> '' AND id.INVENTCOLORID IS NOT NULL THEN '_' + id.INVENTCOLORID ELSE '' END
				+ CASE WHEN id.INVENTSTYLEID <> '' AND id.INVENTSTYLEID IS NOT NULL THEN '_' + id.INVENTSTYLEID ELSE '' END 
				AS NVARCHAR(255))																								AS ITEM_NO,
			CAST(CASE WHEN it.DATEPHYSICAL <= '2025-07-01' AND loc.locationNo = 'LAG305' THEN 'LAG212'
					ELSE loc.locationNo END AS NVARCHAR(255)) 																	AS LOCATION_NO,
			CAST(it.DATEPHYSICAL AS DATE) 																						AS [DATE],
			CAST(-SUM(it.QTY) AS DECIMAL(18,4))																					AS SALE,
			CAST('' AS NVARCHAR(255))																							AS [CUSTOMER_NO],
            CAST('' AS NVARCHAR(255))																							AS [REFERENCE_NO],
            CAST(0 AS BIT)																										AS [IS_EXCLUDED]
		FROM ax.INVENTTRANS it
			INNER JOIN ax_cus.INVENTTRANSORIGIN ito		ON it.INVENTTRANSORIGIN = ito.RECID AND it.DATAAREAID = ito.DATAAREAID AND it.[PARTITION] = ito.[PARTITION]
			INNER JOIN ax.INVENTDIM id					ON id.inventdimid = it.inventdimid AND id.DATAAREAID = it.DATAAREAID AND id.[PARTITION] = ito.[PARTITION]
			INNER JOIN core.location_mapping_setup loc	ON loc.locationNo = id.INVENTLOCATIONID
		WHERE 
			it.DATEPHYSICAL <> '1900-01-01 00:00:00.000'
			AND NOT (CAST(it.MODIFIEDDATETIME AS DATE) = '2020-01-09' AND it.DATEPHYSICAL = '2020-01-08 00:00:00.000')
			AND it.qty BETWEEN -10000000 AND 10000000
			AND ito.REFERENCECATEGORY = 0 -- sale
			--AND (it.[ITEMID]
			--				+ CASE WHEN id.INVENTSIZEID  <> '' AND id.INVENTSIZEID IS NOT NULL THEN '_' + id.INVENTSIZEID ELSE '' END
			--				+ CASE WHEN id.INVENTCOLORID <> '' AND id.INVENTCOLORID IS NOT NULL THEN '_' + id.INVENTCOLORID ELSE '' END
			--				+ CASE WHEN id.INVENTSTYLEID <> '' AND id.INVENTSTYLEID IS NOT NULL THEN '_' + id.INVENTSTYLEID ELSE '' END)='30350006'
		GROUP BY 
			CAST(it.[ITEMID]
							+ CASE WHEN id.INVENTSIZEID  <> '' AND id.INVENTSIZEID IS NOT NULL THEN '_' + id.INVENTSIZEID ELSE '' END
							+ CASE WHEN id.INVENTCOLORID <> '' AND id.INVENTCOLORID IS NOT NULL THEN '_' + id.INVENTCOLORID ELSE '' END
							+ CASE WHEN id.INVENTSTYLEID <> '' AND id.INVENTSTYLEID IS NOT NULL THEN '_' + id.INVENTSTYLEID ELSE '' END 
							AS NVARCHAR(255)),
			it.DATEPHYSICAL,
			CAST(CASE WHEN it.DATEPHYSICAL <= '2025-07-01'	AND loc.locationNo = 'LAG305' THEN 'LAG212'
								ELSE loc.locationNo END AS NVARCHAR(255))
		HAVING SUM(it.QTY) <> 0

	


