CREATE VIEW [cus].[v_BOM_CONSUMPTION_HISTORY] AS
    SELECT
        CAST(NULL AS NVARCHAR(255)) AS TRANSACTION_ID,
        CAST(NULL AS NVARCHAR(255)) AS ITEM_NO,
        CAST(NULL AS NVARCHAR(255)) AS LOCATION_NO,
        CAST(NULL AS DATE)          AS [DATE],
        CAST(NULL AS DECIMAL(18,4)) AS [UNIT_QTY]
    WHERE 1 = 0

