CREATE VIEW [cus].[v_CUSTOMER] AS
	SELECT
        CAST([NO] AS NVARCHAR(255)) AS [no],
        CAST([NAME] AS NVARCHAR(255)) AS [name],
		CAST(NULL AS NVARCHAR(255))     AS [CUSTOMER_GROUP_NO]
    FROM [cus].[AGR_CUSTOMER]
