CREATE VIEW [cus].[v_PURCHASE_ORDER_ROUTE] AS
       SELECT
        CAST(ITEM_NO AS NVARCHAR(255))          AS [ITEM_NO],
        CAST(LOCATION_NO AS NVARCHAR(255))      AS [LOCATION_NO],
        CAST(VENDOR_NO AS NVARCHAR(255))        AS [VENDOR_NO],
        CAST([PRIMARY] AS BIT)                  AS [PRIMARY],
        CAST(LEAD_TIME_DAYS AS SMALLINT)        AS [LEAD_TIME_DAYS],
        CAST(ORDER_FREQUENCY_DAYS AS SMALLINT)  AS [ORDER_FREQUENCY_DAYS],
        CAST(MIN_ORDER_QTY AS DECIMAL(18,4))    AS [MIN_ORDER_QTY],    
        CAST(COST_PRICE AS DECIMAL(18,4))       AS [COST_PRICE],
        CAST(PURCHASE_PRICE AS DECIMAL(18,4))   AS [PURCHASE_PRICE],
        CAST(ORDER_MULTIPLE AS DECIMAL(18,4))   AS [ORDER_MULTIPLE],  
        CAST(QTY_PALLET AS DECIMAL(18,4))       AS [QTY_PALLET]
    FROM [cus].[AGR_PURCHASE_ORDER_ROUTE]
