 CREATE VIEW [cus].[v_STOCK_HISTORY] AS
       SELECT
		CAST(NULL AS BIGINT)               AS [TRANSACTION_ID],
		CAST(ITEM_NO AS NVARCHAR(255))               AS [ITEM_NO],
		CAST(LOCATION_NO AS NVARCHAR(255))           AS [LOCATION_NO],
		CONVERT(DATE, [DATE], 103)					 AS [DATE],  
		CAST(STOCK_MOVE AS DECIMAL(18,4))            AS [STOCK_MOVE],
		CAST(STOCK_LEVEL AS DECIMAL(18,4))           AS [STOCK_LEVEL]
	   FROM [cus].[AGR_STOCK_HISTORY]

