CREATE TABLE [cos_cus].[AGR_LOCATION] (
    [NO] NVARCHAR(255) NOT NULL,
    [NAME] NVARCHAR(255) NULL,
    [TYPE] NVARCHAR(255) NULL,
    [ADDRESS_1] NVARCHAR(500) NULL,
    [ADDRESS_2] NVARCHAR(500) NULL,
    [POSTCODE] NVARCHAR(255) NULL,
    [COUNTY] NVARCHAR(255) NULL,
    [COUNTRY] NVARCHAR(255) NULL,
    [CONTACT_NAME] NVARCHAR(255) NULL,
    [CONTACT_TELEPHONE] NVARCHAR(255) NULL,
    CONSTRAINT [pk_cos_cus_agr_location] PRIMARY KEY (NO)
);
