CREATE TABLE [cus].[Item] (
    [vad_id] NVARCHAR(MAX) NULL,
    [vad_variant_code] NVARCHAR(MAX) NULL,
    [vad_description] NVARCHAR(MAX) NULL,
    [vasd_sd_id] NVARCHAR(MAX) NULL,
    [vasd_guide_lead_time] NVARCHAR(MAX) NULL,
    [vasd_minimum_order_qty] NVARCHAR(MAX) NULL,
    [vasd_supplier_part_number] NVARCHAR(MAX) NULL,
    [Closed] NVARCHAR(MAX) NULL,
    [cost_price] NVARCHAR(MAX) NULL,
    [vasd_standard_cost] NVARCHAR(MAX) NULL,
    [vasd_multiplier_qty] NVARCHAR(MAX) NULL,
    [vad_volume] NVARCHAR(MAX) NULL,
    [vad_weight] NVARCHAR(MAX) NULL,
    [ctn_parent_id] NVARCHAR(MAX) NULL,
    [vac_ctn_id] NVARCHAR(MAX) NULL,
    [vaea_c_14] NVARCHAR(MAX) NULL,
    [vaea_c_141] NVARCHAR(MAX) NULL,
    [special_order] NVARCHAR(MAX) NULL,
    [vafp_rsp_exc_vat] NVARCHAR(MAX) NULL,
    [vafp_price_per] NVARCHAR(MAX) NULL,
    [vuq_id] DECIMAL(18,4) NULL
);
