CREATE TABLE [bc_rest_cus].[prep_BOM_COMPONENT] (
    [ITEM_NO] NVARCHAR(255) NOT NULL,
    [COMPONENT_ITEM_NO] NVARCHAR(255) NOT NULL,
    [QUANTITY] DECIMAL(18,4) NOT NULL,
    CONSTRAINT [pk_bc_rest_cus_prep_bom_component] PRIMARY KEY (COMPONENT_ITEM_NO,ITEM_NO)
);
